### ISSUE TITLE
Mixins: base classes or data members?

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#1000]
The [class design](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/classes.md) identifies a [mixin use case](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/classes.md#mixins) for supporting code reuse without multiple inheritance. The way we avoid the problems of multiple inheritance with mixins is that they don't participate in [subtyping](https://en.wikipedia.org/wiki/Subtyping).

#### Game object

An object in the game may have many different axes along which its behavior varies:
- Might be visible but static, visible and animated, or invisible
- Might be stationary, walking, or flying
- Might be damageable or invincible

Each of those could be a mixin providing a definition of some virtual method defined in the game object base class, or an implementation of an interface.

#### Intrusive reference count

A main type `Managed` would include mixin `RefCounted` that holds the counter needed to keep track of the number of `Ref(Managed)` smart pointers currently referencing a given `Managed` object, so it can be freed once there are no more references. The `Ref(T)` type would be a friend of `RefCounted for T`.

#### Intrusive linked list

See [an example of this in Boost](https://www.boost.org/doc/libs/1_63_0/doc/html/intrusive.html). This is similar to the previous example, with the mixin holding a next pointer instead of a reference count. One difference for this use case is that it would be reasonable for a single object to simultaneously be in multiple lists and so would have to include the mixin multiple times (possibly with different parameters). For example, a game object might be in both the "move using physics simulation" and "visible on screen" lists.

#### Serializable

A mixin for serializing an object would need to be templated on the main type, rather than being able to be type checked separately, so it could iterate through the data members using reflection when serialization is requested. Note that the body of the function here is dependent (in the template sense) on the main type, but not the list of members contributed by the mixin.

### Mixin capabilities

- Implicitly parameterized by the main type. Like [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) in C++, but with language support enforcing that the parameter is actually the main type.
- Can be parameterized
- Can have requirements: interfaces implemented, field or method members, extending some base class
- Can provide: functions, methods, interface implementations, data fields
- Provided things could either be final or just a default that can be overridden.

### Base class option
In this approach, a mixin is something listed in the first line of a class declaration, like an `extends` clause for a base class. The members of the mixin become members of the main type.
```
interface Returns(T:! Type) {
  fn Required[me: Self]() -> T;
}
mixin MixinName(T:! Type) for Self:! Returns(T) {
  // `Self` is the main type that contains `MixinName`.

  // Do we need to distinguish private to
  // `MixinName` from private to `Self`?
  private var data: T;

  fn Provided[me: Self]() -> T {
    // `Self` is constrained to implement `Returns(T)`
    // and so has a method `Required` returning `T`.
    return me.Required();
    // Equivalent to: return me.(Returns(T).Required)();
  }
  default fn Overridable[me: Self]() {
    // Members of MixinName(T) are also available
    me.data = me.Provided();
  }
  fn CallsOverridable[me:Self]() {
    // Will see the definition of `Overridable` from
    // `MainType`.
    me.Overridable();
  }
}
class MainType with MixinName(i32) {
  // (Non-private?) members of `MixinName` are
  // members of `MainType`.

  // Have to implement `Returns(i32)` to satisfy
  // the requirements of `MixinName(i32)`.
  impl as Returns(i32) {
    fn Required[me: Self]() -> T { ... }
  }

  // This declaration overrides the definition of
  // `Overridable` from `MixinName`. The
  // override is done statically, not through a
  // vtable. This is safe since `MainType` doesn't
  // have `MixinName` as a subobject or supertype.
  impl fn Overridable[me: Self]() -> i32 { ... }
}
```
Advantages:
- Traditional approach common to many object-oriented languages.
- Easy for mixins to contribute to the API of the main type.

Disadvantages:
- Unclear how to initialize the members of the mixin when constructing the main type.
- Concerns about name conflicts.
- Awkward to support mixing in the same mixin multiple times. They could be distinguished by giving them an extra parameter, which is a little hacky. But the names of the members of the mixin will definitely conflict.
- More mechanism, larger language footprint: `default`, conflict resolution, members of the mixin could be private to mixin or private to main-type
- Would need additional mechanism if we want to support a "private" mixin.

### Data member option
In this approach, a mixin is an ordinary data member except that it is automatically parameterized by the containing type, and it has the ability to convert between a pointer to the mixin and a pointer to the containing main type. Members of the mixin are accessed from a main type value using either the name of the field or through functions of the main type that forward.
```
interface Returns(T:! Type) {
  fn Required[me: Self]() -> T;
  // Main type also has to provide a definition
  // of Overridable.
  fn Overridable[me: Self]();
}
mixin MixinName(T:! Type) for Main:! Returns(T) {
  // `Main` is the main type which contains a
  // member of type `MixinName(T) == Self`.

  // `private` means private to the mixin
  private var data: T;

  fn Provided[me: Self]() -> T {
    // `Main` is constrained to implement `Returns(T)`
    // and so has a method `Required` returning `T`.
    return (me as Main).Required();
  }
  // No direct support for overriding of methods in the mixin.
  fn Overridable[me: Self]() {
    // Members of `MixinName(T)` are available
    // through `me`.
    me.data = me.Provided();
  }
  fn CallsOverridable[me:Self]() {
    // Have to explicitly say `Main` to get its definition
    // of `Overridable`.
    (me as Main).Overridable();
  }
}
class MainType {
  // Mixins are members with names, and ordinary
  // access control modifiers.
  var m: MixinName(i32);
  // or maybe: `mix m: MixinName(i32);`
  // or maybe: `var m: mix MixinName(i32);`

  // Notice `Overridable` moved inside here so its
  // definition may be used by the mixin.
  impl as Returns(i32) {
    fn Required[me: Self]() -> T { ... }
    fn Overridable[me: Self]() -> i32 { ... }
  }

  // Need some way to add members of `m` to the
  // API of `MainType`.
  fn Provided[me: Self]() -> i32 =  m.Provided;
}
```
Advantages:
- Simpler in the sense of fewer mechanisms needed
- Straightforward initialization story
- No name conflicts
- Straightforward to have the same mixin multiple times

Disadvantages:
- Have to forward / re-export members of mixin
- For the intrusive linked list use cases, we need some way to connect the list container class with which mixin member to use. 
    - Similarly, the serialization use case would want to find the serializer mixin of all members. Expect to find the mixin by type in that case, not by name, to avoid typo problems.

**Comment by josh11b** [comment]
Copying what I said in [#typesystem](https://discord.com/channels/655572317891461132/708431657849585705/1033404388770848899):

I think we've been assuming that we want users to be able to control memory layout, and so have been listing the mixins intermixed with the variable declarations. So from a syntactic perspective we've been answering "data members." I have been arguing that our current best story for constructors is to treat them as data members as well, though that could be due to a lack of people putting forth alternative proposals. For visibility we've been leaning more toward treating them like some combination of interface implementations, base classes, and data members (as just described above); notably we do want more ability to inject names from the mixin into the mixer than described in the data member option of #1000. From a typing perspective, we've been treating mixins more like base classes, so Self in the mixin refers to the whole object with a different API.
For the question of "give each mixin a unique type" and/or "give each mixin a unique name", in discussions we've been leaning toward the principle that whether a type uses a mixin is an internal implementation detail that is not externally visible. Assuming that pans out -- that we have no problem supporting something like intrusive linked lists in this model -- there would be no need to give mixins unique types as long as they have unique names.

**Comment by chandlerc** [comment]
After discussion with the leads, no decision needed from us at this time based on the progress described in @josh11b's [comment](https://github.com/carbon-language/carbon-lang/issues/1000#issuecomment-1292353283) -- it's not clear this will even be a simple binary choice, which makes sense. When the current work to flesh out a candidate design and implementation is ready to be considered in a proposal, we can extract any new decisions needed.
