### ISSUE TITLE
How much complexity should we invest in deduced/inferred return types?

### ISSUE THREAD

**Issue by chandlerc** [carbon-language/carbon-lang#1008]
Inferred function return types look like the following:

```carbon
fn Add(x: i32, y: i32) -> auto { return x + y; }
```

Here, rather than specify the return type, the type is inferred from the return statement's expression: `x + y`.

This was added in #826 as a very minimal, simple feature. However, the restrictions placed on it may interact with other language features to be especially limiting.

Between #875 and some of the directions in #472, the inability to articulate a separate declaration and definition of such a function might make them unusable when nested in functions -- they already cannot be used with out-of-line definitions of nested functions.

C++ provides a way to allow declaring such functions -- until defined, their return type is in some ways incomplete / unknown. This introduces a certain amount of complexity but would allow out-of-line definitions of such functions, breaking some cycles, etc. This was left as an alternative not (at the time) considered in #826 when it went in.

If we don't want to add that complexity, and if we resolve #472 in a way that means inferred function return types won't work for nested functions, I think we should consider whether inferred function return types are truly carrying their weight. While they will remain a very simple feature, they'll have even more places where they interact poorly with the rest of the language (beyond virtual, interfaces, etc).

To help motivate that consideration, its also important to suggest the place where inferring the return type is especially well motivated: code that returns a type that may be especially difficult to name. For example, consider the C++ code:

```cpp
auto BuildLambda(int a, int b) {
  return [a, b](int c) { return a + b + c; };
}
```

This kind of function returning a lambda is especially hard to write without an inferred return type. It's unclear the extent to which this code will come up in Carbon, but it maybe worth thinking about these kinds of functions whet making a decision here.

I think there are basically three directions we could choose between here:

1) Make inferred function return types work as well as we can, adding some complexity to the language where needed.
2) Keep them as they are, super simple but may be very limited in how and where they can be used.
3) Remove them completely.

**Comment by josh11b** [comment]
It seems like a tentative answer was proposed but never accepted? Can we resolve this question. In summary:
- We are generally going with approach (2).
- Member functions cannot use `auto` return type.

The one thing we might want to say, beyond this, is that we might want to support `auto` with multiple return paths, using the `CommonType` mechanism created in proposal #911 .

**Comment by chandlerc** [comment]
> The one thing we might want to say, beyond this, is that we might want to support `auto` with multiple return paths, using the `CommonType` mechanism created in proposal #911 .

I don't know that we need to say definitely "yes" or "no" to that here -- I think that can wait for someone to be motivated to write a proposal?

**Comment by chandlerc** [comment]
While not thrilling, the status quo of (2) is the best thing we have for now and the leads are OK with that. We can look at proposals to use a common-type approach whenever someone writes one, and if needed revisit this with more data and a plan for how to do better than this approach.
