### ISSUE TITLE
How should interfaces for core functionality be named?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#1058]
We have various choices for how to name interfaces that correspond to core functionality, such as overloaded operators, implicit conversions, etc. Some possible considerations:

- We might want these names to be as terse as is feasible. For example, [Rust uses](https://doc.rust-lang.org/std/ops/index.html) `Mul`, `Deref`, `Index`, and [Haskell uses](https://hackage.haskell.org/package/base-4.16.0.0/docs/Prelude.html#g:4) `Eq`, `Ord`, `Num`.
- We might want some kind of systematic decoration for these names. For example, [Python uses](https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types) `__double_underscore__` names such as `__mul__`.
- We might want these names to be fully descriptive and unabbreviated, with nothing in particular setting them apart from user-defined interfaces, but still as short as possible subject to those constraints. For example, previous discussion in Carbon has used as placeholders names like `AddableWith`, and we have accepted proposals using `CommonTypeWith`, `As`, and `ImplicitAs`.
- We might want these names to be generated directly from the corresponding operators. For example, C++ uses `operator*`, `operator[]`. This would deviate from Carbon's normal naming rules, but this is perhaps a place where we could afford such deviation.

Relative to Carbon's goals, the most important aspects are likely:
- Language evolution: changes to which interfaces are core versus which are merely built on top of core interfaces should ideally avoid significant ripple effects in how code is written, suggesting that we don't use a special naming convention for these operations.
- Code that is easy to read, understand, and write, and in particular:
    - Syntax should be easily parsed and scanned by any human in any development environment, not just a machine or a human aided by semantic hints from an IDE.
    - Explicitness must be balanced against conciseness, as verbosity and ceremony add cognitive overhead for the reader, while explicitness reduces the amount of outside context the reader must have or assume.

Probably the two most plausible options are more-abbreviated Rust-like naming and more-verbose naming following our current proposals.

**Comment by jonmeow** [comment]
Does this still need a proposal given #1178 and related work?

**Comment by chandlerc** [comment]
I think this is done now.
