### ISSUE TITLE
type/value confusion in return type of functions

### ISSUE THREAD

**Issue by jsiek** [carbon-language/carbon-lang#1062]
The result of the return type expression is being set as the type of the return type expression instead of being set as the value of the return type expression. This isn't showing up as an actual bug because the type checking of return statements grabs the type of the return type expression instead of getting its value.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
