### ISSUE TITLE
find a way to permit impls of CommonTypeWith where the LHS and RHS type overlap

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#1077]
Per the [current design](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/if.md#same-type), `CommonTypeWith` has an `impl` of this form:

```
final impl [T:! Type] T as CommonTypeWith(T) where .Result = T {}
```

Given this `final impl`, it's unclear how to write a parameterized `impl` of `CommonTypeWith` for two parameterized types that overlap. For example:

```
// Error: would specialize the above `final impl`.
impl [U:! Type, T:! CommonTypeWith(U)] Vec(T) as CommonTypeWith(Vec(U)) where .Result = Vec(T.Result) {}
```

The error here is unnecessary: there's no actual coherence problem here because in the case where `T == U`, the computed `Result` is `Vec(T)`.

It's not clear how to resolve this. Some options:

* Switch from `final impl` to a [final associated constant](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0983.md#final-associated-constants-instead-of-final-impls).
* Provide some way for the author of this `impl` to say that it's prioritized below the `final impl`.
* Provide some way for the author of the `final impl` to say that it is considered more specialized than any other `impl`, rather than disallowing `impl`s that overlap with it.
* Add support for [type inequality constraints](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0818.md#type-inequality-constraints) so that the new `impl` could exclude the `T == U` case.
* Allow a `final impl` to be specialized if the specialization is identical.

**Comment by josh11b** [comment]
As far as I am aware, we would still like an answer to this question. An answer was proposed in https://github.com/carbon-language/carbon-lang/issues/1077#issuecomment-1093606977 but never accepted.

**Comment by chandlerc** [comment]
Yep, leads are happy with the resolution here: https://github.com/carbon-language/carbon-lang/issues/1077#issuecomment-1093606977
