### ISSUE TITLE
How do we match forward declarations with their definitions?

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#1132]
With the decision on #472 , Carbon has separate forward declarations from definitions and we need some way to match them up. This comes up for functions, classes, interfaces, named constraints, interface implementations, and probably others.

There are a three main components to this question:
1. What parts of a declaration are used to connect a forward declaration to its definition?
2. What constitutes a match for any given part?
3. Once we have identified that a declaration should be associated with a particular definition, what additional checking must be done to make sure they are consistent?

**Comment by zygoloid** [comment]
What agreement rule do we want for the case where the forward declaration and definition are in different scopes -- specifically, when checking whether a declaration of a member function in a class (or a defaulted function in an interface or a member of an impl) agrees with a definition written outside that class? For example:

```carbon
class A {
  fn F();
}

let T:! type = A;
// OK?
fn T.F() {}

class B(T:! type) {
  fn F();
}
constraint Type {}

// OK?
fn B(T:! Type).F() {}
```

I suggest we require the part before the `.` to agree with the class declaration, in the same way that we require the part after the `.` to agree with the function declaration, so both of the above definitions are rejected -- and in general, the first part of `fn <tokens that identify a class>.F()` is allowed if and only if `class <tokens that identify a class>;` would be allowed. That seems to be in line with what's proposed here, but @josh11b and I weren't certain the prior decision covered this.

**Comment by chandlerc** [comment]
I agree.
