### ISSUE TITLE
Mismatch in generic class argument list causes CHECK failure

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#1196]
#1195 has a test that fails with a CHECK-failure and a stack trace instead of a compiler error. The relevant lines are:
```
class Point(T:! Type) {
  // Point(T, T) does not match class declaration
  fn Origin(zero: T) -> Point(T, T) {
...
```

The mismatch between the `Point` declaration, which takes a single parameter, and the return type, which passes two arguments to `Point`, should be caught and reported instead of triggering a `CHECK` failure and stack trace:

```
CHECK failure at executable_semantics/interpreter/interpreter.cpp:216: p_tup.elements().size() == v_tup.elements().size()
...
```

This is something introduced with generic class support in #1124 .

**Comment by jonmeow** [comment]
Looks fixed, probably by #1200  and #1204.
