### ISSUE TITLE
can class parameters be deduced from a struct initializer?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#1251]
Testcase:
```
package Test1 api;
class Wrap(T:! Type) { var x: T; }
fn Get[T:! Type](w: Wrap(T)) -> T { return w.x; }
fn Main() -> i32 { return Get({.x = 1}); }
```

The question is: do we support deducing the type `T` in `Wrap(T)` from the initializer `{.x = 1}`?

This would be straightforward to implement, but it's not clear to me whether this is something we would expect deduction to be able to handle.

There's a similar but simpler case for struct field reordering:
```
package Test2 api;
fn Get[T:! Type](w: {.x: T, .y: T}) -> T { return w.x; }
fn Main() -> i32 { return Get({.y = 1, .x = 1}); }
```
In this case, I think it is relatively clear that we do want to allow this, because the "named arguments appearing in any order" use case relies on it.

Arguments for allowing the struct -> class deduction:

* It's more convenient.
* It means you can replace a struct parameter with a class without breaking callers and generally makes classes and structs behave more similarly
* C++20 permits the same kind of thing, in the form of aggregate CTAD.

Arguments against:

* It's additional complexity via an extra deduction rule.
* This would be making deduction match builtin implicit conversions better, but there might not be any way to get the same behavior for user-defined implicit conversions.

**Comment by chandlerc** [comment]
The leads are happy with the direction suggested by @zygoloid in https://github.com/carbon-language/carbon-lang/issues/1251#issuecomment-1125319492 -- marking this as closed.

Not opening a tracking issue as all of deduction hasn't gone through proposals, and this should just be reflected as those proposals take shape.
