### ISSUE TITLE
missing check that deduced argument converts to type of parameter

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#1300]
Testcase:

```
package Foo api;
fn Get[T:! ()](n: T) -> T { return n; }
fn Main() -> i32 {
  var z: i32 = 0;
  return Get(z);
}
```

This is accepted. Apparently we don't check that the value `T = i32` that we deduce is actually convertible to the type `()` declared for the binding.

**Comment by pmqtt** [comment]
I think I have fix them!
