### ISSUE TITLE
integer overflow in explorer

### ISSUE THREAD

**Issue by pk19604014** [carbon-language/carbon-lang#1308]
package P api;

fn Main() -> i32 {
  var count: i32 = 5;
  while (not (count == 0)) {
    count = count - 112722749;
  }
  return 0;
}

$ bazel run explorer:explorer /tmp/crash.carbon
...
interpreter.cpp:172:69: runtime error: signed integer overflow: -2141732226 - 112722749 cannot be represented in type 'int'

**Comment by zygoloid** [comment]
I think explorer should be catching this and reporting it as a runtime error, rather than leaving it to ubsan to diagnose.

**Comment by pk19604014** [comment]
Thanks.

Relevant Discord discussion -- https://discord.com/channels/655572317891461132/763516049710120960/982378627968675930
One of recommendations was to look into llvm's APInt -- https://llvm.org/doxygen/classllvm_1_1APInt.html

**Comment by guille2718** [comment]
The current explorer catches this as a runtime error
```
RUNTIME ERROR: /home/guille/test.carbon:6: integer overflow
```
I guess this issue can be closed now.

**Comment by geoffromer** [comment]
Yeah, looks like #2737 fixed this.
