### ISSUE TITLE
OOM in explorer type checking when a function with infinite recursion is specified in another function's return type

### ISSUE THREAD

**Issue by pk19604014** [carbon-language/carbon-lang#1321]
$ cat /tmp/crash.carbon
package P api;

fn g() -> Bool {
  return g();
}

fn f() -> g() {
}

fn Main() -> i32 {
  return 0;
}

$ time bazel run explorer:explorer /tmp/crash.carbon
...eventually OOMs
real	45m43.497s
user	33m10.615s
sys	6m2.100s

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
