### ISSUE TITLE
explorer crashes  when __await is called outside of a continuation

### ISSUE THREAD

**Issue by pk19604014** [carbon-language/carbon-lang#1393]
```
package P api;

fn Main() -> i32 {
  __await;
  return 0;
}

CHECK failure at ./explorer/interpreter/stack.h:55: !IsEmpty(): Empty stack has no Top().
```

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
