### ISSUE TITLE
Weekly sync doc is not public

### ISSUE THREAD

**Issue by laurentlb** [carbon-language/carbon-lang#1422]
From https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#collaboration-systems:
> The [weekly sync](https://docs.google.com/document/d/1pYq5MssjOi8c-wBJaHEDcsVMirFeC3iv2uFUOwsI3-M/edit), where everyone is welcome.

The Google Doc has restricted access.

**Comment by laurentlb** [comment]
Same for the following line:
> [Open discussions](https://docs.google.com/document/d/1NnFKOUNh_BCbVD29JiNqQ0JzC5VfE6YUq6CfKqFkouQ/edit), which are unstructured meeting slots used for discussing proposals, tooling, and other Carbon topics based on who attends.

**Comment by jonmeow** [comment]
Thank you for pointing this out! I've been slowly fixing doc ACLs, but I'm sure I would've missed these today.
