### ISSUE TITLE
Is this production ready? 

### ISSUE THREAD

**Issue by StandingPadAnimations** [carbon-language/carbon-lang#1433]
Just found about this language and I want to try using it for one of my projects. Is Carbon stable enough to use?

**Comment by tashima42** [comment]
It says experimental on the Readme, so probably not for a large scale project, maybe a quick personal experiment.

**Comment by zygoloid** [comment]
Thank you for your interest! Unfortuantely, our implementation is not yet complete enough for anything beyond small experiments and test cases, so I would not recommend using it for anything other than exploring the Carbon language and design at this time.
