### ISSUE TITLE
OpenMP support

### ISSUE THREAD

**Issue by foxtran** [carbon-language/carbon-lang#1447]
OpenMP is a simple way to parallelize programs on shared-memory systems. It found many applications in scientific code like GROMACS (https://github.com/gromacs/gromacs), lammps (https://github.com/lammps/lammps), QMCPACK (https://github.com/QMCPACK/qmcpack), Elemental (https://github.com/elemental/Elemental) and so on, where the performance is critical.

So, it would be excellent, when C++ → **Carbon** is, to have an OpenMP support in Carbon language.

**Comment by chandlerc** [comment]
Definitely interested in exploring what the parallel programming model is for Carbon. Would be really nice to have a very clean integration with existing OpenMP stacks as you mention.

But I suspect this is just a long way away right now. Closing this as "not planned" in the short term at least to keep our issue tracker clean.
