### ISSUE TITLE
Having support for native homebrew installation of carbon

### ISSUE THREAD

**Issue by remyleone** [carbon-language/carbon-lang#1449]
I would like to install and update carbon using my package manager which is homebrew on macos.

**Comment by geoffromer** [comment]
I'm afraid Carbon is [not yet in a usable state](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon), or even very close. That being the case, we don't think it would be useful to package it for distribution right now.
