### ISSUE TITLE
0-Element Tuples

### ISSUE THREAD

**Issue by nigeltao** [carbon-language/carbon-lang#1456]
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/tuples.md#single-value-tuples explicitly considers 1-element tuples but the doc does not consider 0-element tuples. If tuples are a product type then a 0-element tuple is the unit type.

Are they legal? What's their syntax? Are they equivalent to a 0-element struct?

See also: [Void type as unit type](https://en.wikipedia.org/wiki/Unit_type#Void_type_as_unit_type)

**Comment by geoffromer** [comment]
Yes, zero-element tuples are valid, and the syntax is `()`. The empty tuple is a different type from the empty struct, though.

**Comment by chandlerc** [comment]
> Yes, zero-element tuples are valid, and the syntax is `()`. The empty tuple is a different type from the empty struct, though.

Maybe worth a quick addition to the tuple design then, and fix this issue with that?
