### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by RoCampos** [carbon-language/carbon-lang#1475]
Hi, everyone! 

Is there an image in docker to use the language?

**Comment by jonmeow** [comment]
We've worked with mattgodbolt to make the explorer available at [carbon.compiler-explorer.com](http://carbon.compiler-explorer.com). However, Carbon is not ready for use: there is no working compiler. We consider it very experimental, so I don't think a docker would make sense. For more information, please read: https://github.com/carbon-language/carbon-lang#project-status
