### ISSUE TITLE
`new` and `delete` equivalents

### ISSUE THREAD

**Issue by nigeltao** [carbon-language/carbon-lang#1483]
I didn't see C++'s `new` or `delete` (and the Carbon equivalents) discussed in https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/README.md (or even a placeholder section under "Unfinished Tales").

Issues #257 and #1154 are related, but not exactly the same.

The status may very well be 'yeah, that's TBD (To Be Determined)'. I just wanted to check that I didn't miss anything.

**Comment by jonmeow** [comment]
I think TBD. Right now explorer has a Heap.New and Heap.Delete, but I think that shouldn't be taken as a clear design direction.
https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/data/prelude.carbon

**Comment by chandlerc** [comment]
We're definitely looking at allocators and Zig and other languages here. Since this is TBD as guessed, closing this issue for now to keep our open issues tidy.
