### ISSUE TITLE
what develop tool will be used at carbon-lang?

### ISSUE THREAD

**Issue by theseusyang** [carbon-language/carbon-lang#1489]
what develop tool will be used at carbon-lang, vs-code?

**Comment by chandlerc** [comment]
Our contribution tools are documented in our [contribution tools](/docs/project/contribution_tools.md).

Generally we try to be pretty open ended on thing like editors / IDEs though.

Does this help?

**Comment by MiroKaku** [comment]
> Our contribution tools are documented in our ~~[contribution tools](/docs/project/contribution_tools.md)~~.
> 
> Generally we try to be pretty open ended on thing like editors / IDEs though.
> 
> Does this help?

[contribution tools](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md)
