### ISSUE TITLE
DSL Support

### ISSUE THREAD

**Issue by PixelyIon** [carbon-language/carbon-lang#1498]
A major flaw with C++ that we've run into is the lack of supporting Domain-Specific Languages (DSL), it's the correct replacement for a lot of C macros. It should be noted that [Rust also implements this](https://doc.rust-lang.org/rust-by-example/macros/dsl.html#domain-specific-languages-dsls). Is there any interest in DSL support for Carbon?

(P.S. The team has done an amazing job with Carbon so far)

**Comment by chandlerc** [comment]
This is definitely an interesting area, but at the moment isn't really one of the prioritized parts of our roadmap.

Until we are beginning to more fully explore metaprogramming, I don't think there is anything immediate we can do here, so closing as not-planned (for now).

**Comment by PixelyIon** [comment]
Thanks for the response, good luck!
