### ISSUE TITLE
Unsafe support

### ISSUE THREAD

**Issue by abel1502** [carbon-language/carbon-lang#1501]
While the idea of a safety-oriented successor of C++ with maintained performace seems promising to me, I believe the original language had another very important use. That is, being capable of low-level, architecture-tailored manipulations. This includes raw pointer arithmetics, `volatile`, inline assembly, `extern "c"` and other similar features. I agree that porting some of them directly would likely compromise the safety of the language, but I still think they should be available in a more convenient manner than adding a separate C++ translation unit. Perhaps something like C#'s `unsafe` keyword could be a solution, making the programmer explicitly take responsibility for his code's safety. Another option would be allowing C++ code inserts (much like inline assembly), although that seems worse in terms of both safety and code quality.

(Sorry if this had already been brought up before. I haven't found anything similar in the issues)

**Comment by janwilmans** [comment]
Quote from Twitter: 
"Most code in a give language is written in the "default" mode, so most rust is safe, most C++ is very unsafe (who uses ".at" instead of []?). If the easiest thing to write in Carbon is unsafe code, that's what people will create."

me: "That's a good point, we should make the unsafe code ugly and verbose"

**Comment by chandlerc** [comment]
Our goals already talk about the need to have low-level access:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#performance-critical-software:~:text=Leave%20no%20room%20for%20a%20lower%20level%20language.%20Developers%20should%20not%20need%20to%20leave%20the%20rules%20and%20structure%20of%20Carbon%2C%20whether%20to%20gain%20control%20over%20performance%20problems%20or%20to%20gain%20access%20to%20hardware%20facilities.

They also already talk about making unsafe things visible:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#performance-critical-software:~:text=Make%20unsafe%20or,when%20reading%20code.

So I'm not sure there is anything more we need to do for this issue, closing as already working.

@janwilmans - A specific note, please don't use "ugly" this way here. We should talk about the functional benefit of having things by syntactically marked.
