### ISSUE TITLE
Make  carbon available on compiler explorer 

### ISSUE THREAD

**Issue by ggulgulia** [carbon-language/carbon-lang#1502]
## Description
* Compiler Explorer is an online tool used by many in C++ community developed and maintained by Matt Godbolt (and others of course
* This is the website: https://godbolt.org/
* This tool is used by many to prototype and toy around and play with C++ code and benchmark the assembly code generated by C++ code for toy applications.
* With addition of [CMake Support on compiler explorer ](https://github.com/compiler-explorer/compiler-explorer/issues?q=cmake)the users have even a bigger play ground to experiment and test the limits of Carbon compatibility with CMake

## Why carbon on compiler explorer ? 
* Since Carbon promises to work with C++, its availability on Compiler Explorer will gain the attention of a large experienced audience
* Compiler explorer gives ability to share code snippets -> this can trigger bigger discussion  within C++ and carbon community
* More feature/bug/documentation update requests
* ...

**Comment by mo-xiaoming** [comment]
It's already there, those guys are fast

[godbolt with carbon](https://carbon.compiler-explorer.com/z/96vPrhfqr)

(edited to add a code example on godbolt)

**Comment by ggulgulia** [comment]
I assumed it is not yet on compiler explorer Not sure why :thinking: . Closing this issue
