### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by ShauryaAg** [carbon-language/carbon-lang#1506]
When I run the command
```sh
bazel run //explorer -- ./explorer/testdata/print/format_only.carbon
```

I see the following error message:
```
INFO: Invocation ID: a94222fa-f225-441f-b5e5-0bf2f8269fb2
INFO: Analyzed target //explorer:explorer (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /mnt/d/Documents/Projects/carbon-lang/explorer/interpreter/BUILD:159:11: Compiling explorer/interpreter/resolve_names.cpp failed: (Exit 1): clang++ failed: error executing command /usr/lib/llvm-13/bin/clang++ -no-canonical-prefixes -fcolor-diagnostics -Werror -Wall -Wextra -Wthread-safety -Wself-assign -Wimplicit-fallthrough -Wctad-maybe-unsupported -Wno-unused-parameter -c -MD ... (remaining 86 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from explorer/interpreter/resolve_names.cpp:5:
In file included from ./explorer/interpreter/resolve_names.h:8:
./explorer/ast/ast.h:8:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
Target //explorer:explorer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.468s, Critical Path: 0.37s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Ubuntu version: 22.04
Kernel: 5.15.0-41-generic

Installed `bazelisk` and `llvm` using `linuxbrew`

**Comment by TKX42** [comment]
I get a similar error (on linux as well):

```
INFO: Invocation ID: d6e09cce-f5f3-4030-94d9-382909bd7e91
WARNING: Download from https://mirror.bazel.build/ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/jmillikin/rules_m4/releases/download/v0.1/m4-gnulib-788db09a9f88abbef73c97e8d7291c40455336d8.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/ftp.gnu.org/gnu/bison/bison-3.3.2.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/jmillikin/rules_bison/releases/download/v0.1/bison-gnulib-788db09a9f88abbef73c97e8d7291c40455336d8.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //explorer:explorer (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/tristan/.cache/bazel/_bazel_tristan/44add2c262a0c91d2e8b7606cc5bc59e/external/llvm-project/llvm/BUILD.bazel:164:11: Compiling llvm/lib/Support/CRC.cpp failed: (Exit 1): clang++ failed: error executing command /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/clang++ -no-canonical-prefixes -fcolor-diagnostics -Werror -Wall -Wextra -Wthread-safety -Wself-assign -Wimplicit-fallthrough ... (remaining 85 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/llvm-project/llvm/lib/Support/CRC.cpp:86:10: fatal error: 'zlib.h' file not found
#include <zlib.h>
         ^~~~~~~~
1 error generated.
Target //explorer:explorer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.861s, Critical Path: 3.77s
INFO: 28 processes: 13 internal, 15 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by auxaigh8AephahYoh2yahhoobohsh6ie** [comment]
Got the same error trying to build it on manjaro:
ERROR: /home/USERNAME/.cache/bazel/_bazel_USERNAME/fd6687a7a2a24454eecfdbaa7e9715a4/external/bison_v3.3.2/bin/BUILD.bazel:9:10: Linking external/bison_v3.3.2/bin/bison [for host] failed: (Exit 1): clang++ failed: error executing command /usr/bin/clang++ @bazel-out/host/bin/external/bison_v3.3.2/bin/bison-2.params

Use --sandbox_debug to see verbose messages from the sandbox
clang++: error: invalid linker name in argument '-fuse-ld=lld'
ERROR: /home/USERNAME/.cache/bazel/_bazel_USERNAME/fd6687a7a2a24454eecfdbaa7e9715a4/external/flex_v2.6.4/bin/BUILD.bazel:8:10: Linking external/flex_v2.6.4/bin/flex [for host] failed: 
(Exit 1): clang++ failed: error executing command /usr/bin/clang++ @bazel-out/host/bin/external/flex_v2.6.4/bin/flex-2.params

Use --sandbox_debug to see verbose messages from the sandbox
clang++: error: invalid linker name in argument '-fuse-ld=lld'
Target //explorer:explorer failed to build

**Comment by auxaigh8AephahYoh2yahhoobohsh6ie** [comment]
I did try it with and without in my .bashrc. The same error still remains. But Arch is Arch. Perhaps @ShauryaAg got a diffrent result on ubuntu.

**Comment by ShauryaAg** [comment]
I did not get the same error as you. However, please note that [contribution_tools.md](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md?plain=1#L142) does state that `export PATH="$(brew --prefix llvm)/bin:${PATH}"` is **only** needed in MacOS and not Linux.

However, can you try to install `lld` and see if that works?

**Comment by ghost** [comment]
> However, can you try to install `lld` and see if that works?

That did solve my problem. Indeed i was using the wrong version for lld. I will delet my previous comments to clean up the conversation.

**Comment by jonmeow** [comment]
Can you please update to head? As part of preparing the debug instructions (https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#troubleshooting-build-issues) I removed some special casing of `clang-13` that judging by paths here you're probably running into.

(sorry for the slow response)
