### ISSUE TITLE
thread safety by default

### ISSUE THREAD

**Issue by janwilmans** [carbon-language/carbon-lang#1507]
could we have Immutable objects by default?
that would also make them thread safe by default.

example: String is immutable in Java, it's inherently thread-safe.
I realize that we need performance / escape hatches here, but safe defaults would be awesome?

from the Rust docs:
```In Rust, threads are "isolated" from each other automatically, due to ownership. Writes can only happen when the thread has mutable access, either by owning the data, or by having a mutable borrow of it. Either way, the thread is guaranteed to be the only one with access at the time.```

This model sounds like a sensible default ?

**Comment by chandlerc** [comment]
I would suggest not forking off multiple issues from https://github.com/carbon-language/carbon-lang/issues/1510 like this, I think it fragments discussions and makes the issue tracker harder to manage. I've responded on the main issue, closing this one.
