### ISSUE TITLE
type safety by default

### ISSUE THREAD

**Issue by janwilmans** [carbon-language/carbon-lang#1508]
Ada had possibly the strongest type system ever, should we bring this back as a default?

```
using strong meters = double;
using strong kilometers = double;
using strong number_of_lines = int;

meters distance_to_home = 50 meters;
distance_to_home  = distance_to_home  + 10 meters;

```

* number_of_lines does like the int's do
* Meters behaves like doubles, but can't be mixed with regular double's without explicit conversion
* there would need to be a way to say: meters are addable to kilometers, and this is the ratio between them

I'm omitting a ton of complexity, but I think we should reconsider this entire topic.

**Comment by chandlerc** [comment]
I would suggest not forking off multiple issues from #1510 like this, I think it fragments discussions and makes the issue tracker harder to manage. I've responded on the main issue, closing this one.
