### ISSUE TITLE
GPU and SIMD

### ISSUE THREAD

**Issue by fhoenig** [carbon-language/carbon-lang#1509]
Just my 2 cents / rant:

I find it absurd that anyone would invent another language while pretending that a computer consists only of a CPU ALU.
GPU targets (various ILs and potentially native ISA is pretty much all over LLVM). Apple's Metal IR is also straight up LLVM IR with some attributes to mark address spaces. I don't think there is an excuse to ignore this ;-)

The other part is data-parallel expression. Much to learn from ISPC. It's also LLVM and right there. Much more accessible usage for programming CPU SIMD units than intrinsics or some SIMD vector types / matrices...

I hope you guys are thinking about that.

Kindly
F

**Comment by jonmeow** [comment]
See https://github.com/carbon-language/carbon-lang/tree/trunk/docs/project/principles/success_criteria.md?cl=head#modern-os-platforms-hardware-architectures-and-environments

**Comment by swiftcoder** [comment]
> Any chance of that success criteria doc being published outside of google corporate?

Nevermind, I found it in the repo: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/success_criteria.md

**Comment by jonmeow** [comment]
My bad, fixing link: https://github.com/carbon-language/carbon-lang/tree/trunk/docs/project/principles/success_criteria.md?cl=head#modern-os-platforms-hardware-architectures-and-environments

**Comment by fhoenig** [comment]
What does "We believe Carbon should strive to support some GPUs" mean in practice?

**Comment by jonmeow** [comment]
"We haven't fully thought this through but it's on our minds"

Pragmatically it's a priority, but it's not our top priority -- we're hoping we can get experts to contribute something better than we'd build ourselves.
