### ISSUE TITLE
Consider renaming "let"

### ISSUE THREAD

**Issue by Sploder12** [carbon-language/carbon-lang#1518]
The current design document describes `let` as "constant declarations" and further refers to it as "constant let declarations".
The naming of `let` has ambiguity and doesn't imply const-ness.
This issue is furthered by languages like JS having `let` mean something else.
`let` also doesn't give any information about the r-value nature of the binding.

I propose renaming to "const" however, I can see why this might be an issue with r-value binding.
Alternatives would include (but is not limited to), "val", "rval", "value", "rvalue".

**Comment by tomisinteazer** [comment]
I agree with this const is really explicit and is very obvious as to the purpose of the key word

**Comment by zezba9000** [comment]
This conversation is up on C# too.

**However "let" should never be a replacement for "const".**
(This is a flawed notion pulled from C/C++ & C# readonly keyword is far better equivalent)
"let" implies immutable memory on the stack, heap or global area. (Carbon is using "let" correctly here)
"const"  implies compile-time / program memory. This means compile-time string, numeric concats etc. This is very important for Arduino devices that run off flash not ram.

https://github.com/dotnet/csharplang/issues/188

**Comment by Sploder12** [comment]
You bring up a good point with the issues of "const". 
I prefer "readonly", thank you for bringing it up.

The keyword should be named in a way that the name has meaning without background knowledge, "let" lacks this.

**Comment by chandlerc** [comment]
The exact spelling of `let` hasn't gone all the way through a proposal yet, but the in-progress proposal and surrounding discussions have definitely mentioned all of these alternatives.

When we have a proposal that goes in with this, it will need to include a summary of the alternative spellings and the trade-offs between them. I think that's the point at which it will make sense to ask for a decision on the spelling here. Closing this issue for now as I don't think it makes sense to try to ask for a decision on `let` until we have a proposal that actually lays out the rationale.
