### ISSUE TITLE
Consider allowing `1e6` and similar as integer literals

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#152]
Proposal #143 suggests that we require a period in all real number literals. This means that constants such as `1e6` are invalid -- they're neither real number literals nor integer literals. The motivation for rejecting these in particular is that a survey of C++ code found that they were mostly used to express integer literals rather than real number literals (eg, `int kMaxWidgets = 1e6;`).

We should consider accepting such cases as integer literals once Carbon is more established and the divergence from C and C++ is a less significant concern.

**Comment by chandlerc** [comment]
> We should consider accepting such cases as integer literals once Carbon is more established and the divergence from C and C++ is a less significant concern.

Curious -- why wait?

What would be wrong about just allowing `1e6` as an integer literal syntax?

I was involved in cleaning up a large number of bugs in Google's codebase when we added a warning that checked for initializing an integer with this floating point literal syntax in C++, and my memory is that *all* of that code would have been correct if these had been integer literals.

**Comment by zygoloid** [comment]
> Curious -- why wait?

I was concerned that it might be too confusing to have literals in Carbon that are lexically identical to C and C++ literals but with different semantics. But I'm reconsidering this now -- given that integer literals do convert to floating-point types that they fit into, allowing `1e6` as an integer literal seems like it would not cause many problems. Cases like this would be affected:

```
var a: i32 = ...;
var b: f64 = 1e6 / a;
```

... and `b` would always hold an integer whereas the corresponding expression in C++ would produce a floating-point value for the initializer of `b`. But I'm not sure how realistic something like this is. I think we'd want Carbon code to explicitly specify a type in which to do the floating-point calculation if you want a floating-point result: `(1.0e6 as f64) / a` or `(1e6 as f64) / a`.

I'd be OK with allowing this as integer literal syntax now, and just keeping an eye on whether it leads to any confusion.

**Comment by chandlerc** [comment]
Confirmed with all the leads, and we're happy with the answer of "yes" and the details from @zygoloid's [comment](https://github.com/carbon-language/carbon-lang/issues/152#issuecomment-1504052043).
