### ISSUE TITLE
zlib1g-dev install requirement

### ISSUE THREAD

**Issue by TKX42** [carbon-language/carbon-lang#1527]
On Ubuntu, I got following error when just following the getting started instructions:

```
INFO: Invocation ID: d6e09cce-f5f3-4030-94d9-382909bd7e91
WARNING: Download from https://mirror.bazel.build/ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/jmillikin/rules_m4/releases/download/v0.1/m4-gnulib-788db09a9f88abbef73c97e8d7291c40455336d8.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/ftp.gnu.org/gnu/bison/bison-3.3.2.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/jmillikin/rules_bison/releases/download/v0.1/bison-gnulib-788db09a9f88abbef73c97e8d7291c40455336d8.tar.xz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //explorer:explorer (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/tristan/.cache/bazel/_bazel_tristan/44add2c262a0c91d2e8b7606cc5bc59e/external/llvm-project/llvm/BUILD.bazel:164:11: Compiling llvm/lib/Support/CRC.cpp failed: (Exit 1): clang++ failed: error executing command /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/clang++ -no-canonical-prefixes -fcolor-diagnostics -Werror -Wall -Wextra -Wthread-safety -Wself-assign -Wimplicit-fallthrough ... (remaining 85 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/llvm-project/llvm/lib/Support/CRC.cpp:86:10: fatal error: 'zlib.h' file not found
#include <zlib.h>
         ^~~~~~~~
1 error generated.
Target //explorer:explorer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.861s, Critical Path: 3.77s
INFO: 28 processes: 13 internal, 15 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

And fixed it with `sudo apt install zlib1g-dev`. This should be given as a requirement.

**Comment by chandlerc** [comment]
Yeah, we should document this requirement as part of our "Main tools" here I think: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#main-tools

It's a bit awkward to figure out how to phrase it, but this is an important system dependency.

Would you like to provide a patch to our documentation? Totally fine if not, just wanted to give you the option. If not, we'll find someone to fix this.

**Comment by TKX42** [comment]
I created a pull request: https://github.com/carbon-language/carbon-lang/pull/1558

**Comment by gordon815** [comment]
Hi
When following install instruction...
5. Run the Explorer
Finally, we are ready to build and run the explorer.

The following code runs Bazel build tool so that it triggers the explorer code:

$ bazel run //explorer -- ./explorer/testdata/print/format_only.carbon

I still got the error mentioned ..this was again sorted by running sudo apt install zlib1g-dev

**Comment by TKX42** [comment]
> I still got the error mentioned ..this was again sorted by running sudo apt install zlib1g-dev

I don't quite get your point. The zlib headers are not automatically installed, it was just added as a requirement under linux.

**Comment by gordon815** [comment]
No problem - thanks for explaining
