### ISSUE TITLE
consider "not rocket science" over "revert to green"

### ISSUE THREAD

**Issue by matklad** [carbon-language/carbon-lang#1552]
The contribution docs currently say

>The trunk branch should always stay "green". That means that if tests fail or if we discover bugs or errors, we revert to a "green" state by default, where the failure or bug is no longer present

https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/pull_request_workflow.md#green-tests

This wording implies that it's not exceedingly rare to actually be able to inadvertently break trunk.

I suggest adapting [not rocket science rule](https://graydon2.dreamwidth.org/1597.html), popularized by Rust. The TL;DR is that `trunk` branch is updated to a new commit only *after* that specific commit passed all of the tests there are. 

The difference between the two rules is mostly in degree and emphasis (even with nrsr, you might break trunk if you introduce a flaky test, and you'll have to revert it), but I think there are specific outcomes as well in adapting nrsr:

* It pushes hard against splitting CI into a subset of quick tests which gate PR, and a full suite which ensures correctness. Carbon project is limited in scope, it seems like it should be possible to make the entire test suite fast enough, and having a rule which *forces* you to have fast tests seems good. 
* It provides psychological safety for contributors: the current warning makes me worry that I might break something, and that I (or, worse, someone else) would have to fix it. With nrsr, I can be reasonably sure that the only failure mode is my PR not being merged. 
* It incentivises the maintainers to cast more of the checks as automated CI tests, as CI becomes a single, centralized both in space and time, defining criteria for when the code can reach & stay in trunk.  In other words, if reverting isn't a standard option, you are forced to write a test, you can't rely on "we'll discover bugs later" approach as a standard tool.

**Comment by jonmeow** [comment]
We'll generally try to do test prior to commit (e.g. https://github.com/carbon-language/carbon-lang/blob/trunk/.github/workflows/tests.yaml) but I'd expect decisions in the future to be nuanced. Also, even with tests, sometimes a broken change can get in. In that sense, we may revert.
