### ISSUE TITLE
Implement for loops

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#1592]
Explorer still doesn't implement for loops. This may not be too hard these days, although may include needing a interface for adapting iteration, similar to how we use interfaces for operators. Which may in turn deserve a focused proposal.

https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/README.md#for

**Comment by zygoloid** [comment]
Basic for loop support was added by #1753. Beyond that, there's not much more we can do in explorer for now, given that the semantics of `for` loops aren't designed yet, but #1885 is working on that.
