### ISSUE TITLE
contradiction between non goals and potential 2024-2025 goals

### ISSUE THREAD

**Issue by gertcuykens** [carbon-language/carbon-lang#1594]
The reason why Go2 failed is because Go1 was made with the opposite goals, during its trending lifetime of Go1 many great minds made interesting questions about potential improvements, yes Go1 did a amazing job in focusing the community to build great applications but it was at the cost of innovating the language to its full potential. The truth is if Google would stop investing in Go, the compiler will stop improving almost instantly because it success is based on stability and a handful of Google engineers coordinating releases. I believe the mile stone should be clear there is not going to be one version of Carbon but a multivers of Carbon versions each trying to explorer ideas. I am not sure the world is ready for a distributed language yet in 2024 but eventually we will realise that humans make to many mistakes and need to evolve daily improving ideas and for most learn how to deal with a experimental environment. From when we where little to how we learn in school, to just the fact how many people jobs rely on copy paste code because they are paid for results and not to be creative we end up with languages that take decades to improve what could have been improved in years. I believe the milestone should be made so extreme to wake us up telling us we need to step up our game if we truly want to be a next level programmer. In 2024 every body has there own flavor of Carbon and that we find a middle ground like LLVM so all our versions of Carbon can be compiled  as one. Let set each version of Carbon as a hash of the binary so it makes it very clear, the next version will NOT be

- A stable ABI for the entire language and library
- Perfect backwards or forwards compatibility

**Comment by jonmeow** [comment]
Go2 hasn't been released yet. Please don't use Carbon's forums to attack other languages.

Please review our code of conduct, and remember to always be kind and courteous on our forums. https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md

I'm deleting this post. If you want to repost without the attack on Go2, you can repost, but I don't really think your vision of many Carbon versions is feasible.
