### ISSUE TITLE
Carbon lexer for CudaText

### ISSUE THREAD

**Issue by Alexey-T** [carbon-language/carbon-lang#1602]
It is just info. I made the Carbon lexer for CudaText (free editor). It is in the Addon Manager as usual: Plugins / Addons Manager / Install.

Lexer was tested on bunch of carbon files, I guessed many keywords from context, I maybe missed some keywords.
Lexer shows some items in the code-tree: class, function, interface, impl.

where can I find full list of language keywords ? Standard types? Standard modifiers (public private inline…)?

**Comment by chandlerc** [comment]
I would suggest using the discussion feature of GitHub for things that aren't an issue.

More details of the language can be found in the design documentation, and the flex/bison implementation if interested.

Closing this issue for now.
