### ISSUE TITLE
A bold suggestion for function call syntax

### ISSUE THREAD

**Issue by pache-Ak** [carbon-language/carbon-lang#1603]
In OOP, `a.f()` is the traditional and commonly used form, however in a language with both functions and methods, coexistence of both forms can cause some trouble.

For example, `begin(a)` and `a.begin()` are also exist in C++， in majority case, they are same, but for array(not `std::array`) only `begin(a)` is OK,  as you see, here is  a problem,  `a.f()` not suitable for all situations. This syntax means a is object has member function. But `begin(a)` don't has this restriction， This can also be a member function if the compiler supports it.  

Father of C++ Bjarne Stroustrup try to unify calling syntax,  until today, it not success, maybe in c++26.  

But carbon is a new language,  has not historical baggage, we do it is easily. 

Better support for generics， we  should try only agree one syntax `f(a)` , if `f` is in class, it should mean `a.f()` (we don't need this syntax). We will not need to consider a type is object or built-in type. `f(a)` for any case is OK.

Support function and method in same time will bring chaos.  Only support one is better,  for example java only has method, these questions is not exist .   **carbon** need function and method can be replaced by function. Only need we find a function is defined in class or not. 

In fact, when we call a function, we don't need  know is a method or a function, even in generics we can't know it. If we only has one function call syntax it will clear.

I know don't support syntax `a.f()` is hard.  There are many historical and habitual factor.  But if we need a `a.f()` in some place , `f(a)` can also work is I want. I believe it will join in C++26.  

I wish we can spend some time to consider removing `a.f()` syntax. Less is better, function is enough.

**Comment by chandlerc** [comment]
An express goal of Carbon is to remain familiar and approachable to C++ developers:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#interoperability-with-and-migration-from-existing-c-code:~:text=Familiarity%20for%20experienced%20C%2B%2B%20developers%20with%20a%20gentle%20learning%20curve.

Removing method call syntax seems deeply incompatible with our goals, and so I don't think this is a realistic direction to consider at this point. If there is broad and powerful community interest in this (expressed with emoji reactions or other signals), we can reopen the issue. Closing as not-planned for now.

**Comment by pache-Ak** [comment]
> An express goal of Carbon is to remain familiar and approachable to C++ developers: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#interoperability-with-and-migration-from-existing-c-code:~:text=Familiarity%20for%20experienced%20C%2B%2B%20developers%20with%20a%20gentle%20learning%20curve.
> 
> Removing method call syntax seems deeply incompatible with our goals, and so I don't think this is a realistic direction to consider at this point. If there is broad and powerful community interest in this (expressed with emoji reactions or other signals), we can reopen the issue. Closing as not-planned for now.


year I agree remove method is incompatible,  but  the problem some case method can not work, such as generics and built-in-type,  we need a mechanism in language to  unify calling syntax, I mean `a.f()` and `f(a)` should be same, if `f` is a method.
this is a proposal in C++, but not become a standard. I mean we could keep `a.f()` to adapt C++, but `f(a)` can also work. 
like `begin(a)` in C++ . I think this mechanism join in C++ is possible, so it join in carbon is also possible.
