### ISSUE TITLE
Specification commit information and Issue&PR title

### ISSUE THREAD

**Issue by C-BJ** [carbon-language/carbon-lang#1604]
In order to make the commit information and Issue&PR title clear at a glance, it needs to be standardized
For example: 
Commit information & PR title: [README]Fix grammar errors
(PS:Do not use the past tense)
Issue title: [README]Grammar errors

**Comment by chandlerc** [comment]
While the convention of `[topic-area] message` is useful and good, it isn't evident to me that specifying and requiring this to be standardized is essential.

We do have guidelines for how to contribute:
https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#contribution-guidelines-and-standards

If you would like to suggest improvements that provide helpful and constructive suggestion for how folks should best write commit messages, I would suggest adding them there or to some of our other documents like: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/pull_request_workflow.md

While improved documentation like this is definitely exciting and welcome, not sure that an issue is useful to track this, so closing as 'not planned' for now. Thanks!
