### ISSUE TITLE
Change the file extension (.carbon)

### ISSUE THREAD

**Issue by MamadouSDiallo** [carbon-language/carbon-lang#1611]
I know it is a minor issue but can you change .carbon to something shorter like .cb or .cbn if not taken.

**Comment by Abhijeetbyte** [comment]
Indeed !

**Comment by C-BJ** [comment]
https://github.com/carbon-language/carbon-lang/issues/1574

**Comment by C-BJ** [comment]
https://github.com/carbon-language/carbon-lang/issues/1574

**Comment by robiot** [comment]
Close this as a duplicate?

**Comment by mconst** [comment]
Yes, this looks like a duplicate -- let's keep the discussion (and upvotes) in #1574.  Thanks!
