### ISSUE TITLE
matcher_test_base performing wrong replacement in a for range

### ISSUE THREAD

**Issue by urielgarciarivas** [carbon-language/carbon-lang#1621]
I discovered in #1619 PR that the class `MatcherTestBase` in the function `ExpectReplacement` is performing a wrong replacement within a for range, as follows:
When performing a replacement of
```cpp
for (int i: items) {
```
the expected result is
```cpp
for (int i in items) {
```
but the actual result has an extra space between `in` and `items`, as follows:
```cpp
for (int i in  items) {
```

**Comment by jonmeow** [comment]
FYI, asoffer is proposing a redesign of migrate_cpp in https://github.com/carbon-language/carbon-lang/issues/1534, which seems fairly likely. It may make sense to limit time spent here right now.

**Comment by urielgarciarivas** [comment]
I agree with #1534, so I will close this for now.
