### ISSUE TITLE
Carbon language 

### ISSUE THREAD

**Issue by risharthpardeshi** [carbon-language/carbon-lang#1635]

**Comment by leapofazzam123** [comment]
Carbon language

**Comment by WarEagle451** [comment]
Please don't open issues without reason

**Comment by robiot** [comment]
@mconst Close this since it's an out of context issue?

**Comment by mconst** [comment]
Yes, thanks for pointing this out.  @risharthpardeshi, please feel free to open a new issue if you have a specific problem to discuss!
