### ISSUE TITLE
README C++

### ISSUE THREAD

**Issue by Mylloon** [carbon-language/carbon-lang#1636]
This is highly anecdotal, but to compile the code in C++ in the REAMDE, isn't better to do
```cpp
std::vector<Circle> circles = {{Circle(1.0), Circle(2.0)}};
```
instead of
```cpp
std::vector<Circle> circles = {{1.0, 2.0}};
```
and say that we have to use at least c++20?

I may have missed something, sorry if I did

**Comment by robiot** [comment]
The projects source code itself is written in c++17, so thats probably why the examples also targets that c++ std.

**Comment by pacion** [comment]
Yeah, there is another topic about this #1587

**Comment by jonmeow** [comment]
There's a desire to _support_ C++20. However, there's a big interest in supporting developers who aren't using the latest version of C++, because many aren't. Even with #1587, we wouldn't _require_ C++20.
