### ISSUE TITLE
triple-quoted strings issue

### ISSUE THREAD

**Issue by Alexey-T** [carbon-language/carbon-lang#1644]
file docs/design/lexical_conventions/string_literals.md
ends with such example

```
// This is a single-line raw string literal, equivalent to "\"".
var String: ambig3 = #"""#;
```

CudaText lexer cannot highlight this and i think it is right here. It finds literal from `#"""` until end-of-file, because `#"""` is valid beginning of triple quoted string!

**Comment by geoffromer** [comment]
See earlier in that document:

> A *block string literal* starts with `"""`, followed by an optional file type indicator, followed by a newline...

and later:

> A *file type indicator* is any sequence of non-whitespace characters other than `"` or `#`.

So I think the `"""` in this example can't be the start of a block string literal, because it's followed by something that's not a file type indicator or a newline.

**Comment by jonmeow** [comment]
Note, #1360 is proposing to change this.
