### ISSUE TITLE
Create new branch for pulling.

### ISSUE THREAD

**Issue by pacion** [carbon-language/carbon-lang#1645]
More and more people contribute to this project, have you considered creating new branch and make significant updates into the language instead of obtaining one which is "trunk"?

**Comment by jonmeow** [comment]
Can you offer what you see as the advantages to splitting a branch out and having development go to it?

To try to explain the approach we're using, we'd do most development on trunk and do release branches as needed. But that's more of a "once we're ready to do releases" thing. Some notes on this are here:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/pull_request_workflow.md#trunk-based-development
