### ISSUE TITLE
Typing error in quicksort snippet

### ISSUE THREAD

**Issue by vpelosio** [carbon-language/carbon-lang#1647]
The screenshot from the README.md points to https://github.com/carbon-language/carbon-lang/raw/trunk/docs/images/quicksort_snippet.svg which ends with:

QuickSort(s[:p-1])); <- here we have a double ')' which is wrong
QuickSort(s[p+1:])); <- the same here

**Comment by pacion** [comment]
I'll fix that

**Comment by jonmeow** [comment]
Ref: #1652

**Comment by AFZL210** [comment]
Hi im absolute beginner I would love to fix that

**Comment by geoffromer** [comment]
Looks like this is fixed now. Please reopen if I've misunderstood.
