### ISSUE TITLE
Need a official website for the carbon language...

### ISSUE THREAD

**Issue by ItsRoy69** [carbon-language/carbon-lang#1649]

**Comment by pacion** [comment]
Yeah +1.
Admins what do you think about creating new repository which is also open source? (need to publish docs somewhere)

**Comment by jonmeow** [comment]
> Admins what do you think about creating new repository which is also open source? (need to publish docs somewhere)

The intent is to keep as much as we can in `carbon-lang`

**Comment by jonmeow** [comment]
Duplicate of #1492

**Comment by robiot** [comment]
> Duplicate of #1492 

Maybe close this to keep the open issues clear from duplicates?

**Comment by jonmeow** [comment]
@robiot Missed the button, thanks for pointing that out. :)
