### ISSUE TITLE
Short circuit semantic in bool expression

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#1651]
### Discussed in https://github.com/carbon-language/carbon-lang/discussions/1625

<div type='discussions-op-text'>

<sup>Originally posted by **pmqtt** July 23, 2022</sup>
Hello folk,
I don't know that short circuit is the reight word for this kind of expression in a if statement:

```
fn test() -> Bool {
  Print("HALLO WELT");
  return true;
}

fn Main() -> i32 {
   if( (0==1) and ( test() ) {
      // do anything
   }
} 
```

I think the reight semantic is that "HALLO World" will never printed! But In the current implementation  the test function  is always called. 

</div>

**Comment by Pixep** [comment]
@jonmeow Happy to help. Do you know approximately where the parsing and evalution is done for `if` conditions?
Otherwise I will just dig around.

**Comment by ghost** [comment]
@Pixep 
https://github.com/carbon-language/carbon-lang/blob/eded7ee2706f582793258133d386e9cba9f54d44/toolchain/parser/parser_impl.cpp#L1070
If not found yet, this is where parsing if statements takes place.

**Comment by jonmeow** [comment]
The explorer logic is all under /explorer (distinct from /toolchain).

To walk through how I'm looking --

1. Start at parser.ypp, find the relevant grammar: https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/syntax/parser.ypp#L536, `OperatorExpression` and `Operator::And`

2. Look at interpreter.cpp, find the calling code: https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/interpreter/interpreter.cpp#L195, this is relevant because to use `.value()` they've already been calculated.

3. Still digging into interpreter.cpp, find how arguments are evaluated: https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/interpreter/interpreter.cpp#L1085, `pos()` is being used as a cursor.

I'm looking at this code and, unlike other operators like `+` or `==`, logical operators (`and`, `or`, `not`) aren't extensible ([reference](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/logical_operators.md#overloading)).

One approach here would be to change EvalPrim to use CARBON_FATAL if called with Operator::And/Or, and do short-circuiting logic in OperatorExpression. Saying that makes me kind of wonder if we should create a type distinction, e.g. ExtensibleOperatorExpression versus BuiltinOperatorExpression, but unless @geoffromer or @zygoloid want to express a thought here, the smaller fix seems like a good start.

**Comment by Pixep** [comment]
Awesome, thanks for the detailed background info, super helpful. I will start taking a look at that.

**Comment by Pixep** [comment]
Just to set expectations, I am working on it, and commited to get this done, but I expect it to take me a week+, between finding the availability to work on it, getting used to the environment, and everything. As well as unit tests, doc & friends as needed. Let me know if this kind of turn-around is OK for you :).
