### ISSUE TITLE
need better docs

### ISSUE THREAD

**Issue by duccdev-archive** [carbon-language/carbon-lang#1653]
we need better docs for understanding carbon better, such as docs on pointers, memory management, and other stuff

**Comment by jonmeow** [comment]
To be clear, we'll eventually write tutorials, etc. However, Carbon is not ready for use, and until it's more ready we're doing what we can to not encourage use of Carbon for applications:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon
