### ISSUE TITLE
Exclude svg from pre-commit end-of-file newline

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#1655]
As noted on https://github.com/carbon-language/carbon-lang/pull/1652 pre-commit enforces end-of-file newlines on svg, but probably nobody really reads the image files. It's probably better to just stop, particularly given drawing downloads are generated with a mismatch versus what the pre-commit wants.

**Comment by pacion** [comment]
PR sent :))

**Comment by jonmeow** [comment]
Fixed by #1688
