### ISSUE TITLE
Can't build: The include path is not normalized

### ISSUE THREAD

**Issue by uninhm** [carbon-language/carbon-lang#1673]
I get this error when running
`$ bazel run //explorer -- ./explorer/testdata/print/format_only.carbon`

`ERROR: /home/unai/.cache/bazel/_bazel_unai/c979266a4479bde9c9b8c348f74cbcfb/external/bazel_cc_toolchain/BUILD:20:19: in cc_toolchain_suite rule @bazel_cc_toolchain//:bazel_cc_toolchain: The include path '/usr/lib/llvm/14/bin/../../../../lib/clang/14.0.4/share' is not normalized.`

In fact, when I run
`clang -no-canonical-prefixes -v -fsyntax-only -x c++ /dev/null -stdlib=libc++`
I get these paths:
`/usr/lib/llvm/14/bin/../../../../lib/clang/14.0.4/include`
`/usr/include`

But `repository_ctx.path()` is normalizing it [here](https://github.com/carbon-language/carbon-lang/blob/trunk/bazel/cc_toolchains/clang_configuration.bzl#L101)...

**Comment by robiot** [comment]
Could you try changing the include path `/usr/lib/llvm/14/bin/../../../../lib/clang/14.0.4/share` to `/usr/lib/clang/14.0.4/share`?

**Comment by uninhm** [comment]
@robiot how?

Edit: I mean, how do I do so?
Edit 2: I have already tried setting `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` environment variables

**Comment by geoffromer** [comment]
Have you tried [using homebrew](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#clang-and-llvm) to install llvm?

**Comment by jonmeow** [comment]
Closing due to lack of updates. Note, things have been adjusted for a bit, and we no longer recommend homebrew on linux:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md
