### ISSUE TITLE
Can't run explorer: explorer(26008,0x10a261600) malloc: nano zone abandoned due to inability to preallocate reserved vm space.

### ISSUE THREAD

**Issue by gotnull** [carbon-language/carbon-lang#1676]
Everything up until running the explorer fails:

`bazel run //explorer -- ./explorer/testdata/print/format_only.carbon`

`clang --version`:
Homebrew clang version 14.0.6
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

`sw_vers`:
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

`uname -a`:
Darwin AU-C02DRAHFMD6M 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

<img width="978" alt="Screen Shot 2022-07-25 at 1 58 35 pm" src="https://user-images.githubusercontent.com/578908/180696208-99088db1-2c75-4558-b264-3dad55f6356b.png">

**Comment by gotnull** [comment]
UNAME:

Darwin AU-C02DRAHFMD6M 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

**Comment by chandlerc** [comment]
This is a known issue, but good to have a bug to track it.

The explorer still runs (you can see it print "Hello world!" after the error message) but there is some error setting up ASan on macO when run this way. If you use the optimized build `-c opt` flag to Bazel) it'll go away. We should also figure out why ASan is hitting this issue and fix it.

**Comment by jonmeow** [comment]
Duplicate of #1404

**Comment by micttyl** [comment]
Hello, @gotnull It should be resolved since #2177
Come and try
