### ISSUE TITLE
Please change the name to cshanty

### ISSUE THREAD

**Issue by jloveric** [carbon-language/carbon-lang#1677]
As the title states, the language should be called cshanty.

**Comment by anton-roos** [comment]
Please refrain from opening issues that does not align to our Code of Conduct. Please read more about it here: https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md @jonmeow can we please close this as it is not a real issue.

**Comment by chandlerc** [comment]
While I'm personally a big fan of sea shanties, sea shanty humor, and the recent C-shanty humor, this is quite off topic and probably not worth using the issue tracker for.

I don't think this is an interesting CoC violation for what its worth, but it is off topic and we should try to stay on topic here.

Anyways, closing.
