### ISSUE TITLE
It's nice to try Carbon, but I wonder whether it's a system programming language or not

### ISSUE THREAD

**Issue by CoderTyn** [carbon-language/carbon-lang#1684]
As titled.
It would be nice to receive your reply.

**Comment by netesy** [comment]
This question can be answered easily by reading the Readme. It is posed as a replacement for legacy c++ code which means it is a system programming language.

**Comment by TheSoumilArora** [comment]
This language aims to be a replacement for the C++ language.
Hence It will be a system programming language shortly.

**Comment by jonmeow** [comment]
I'm closing this issue: please use Discord or GitHub Discussions for questions like this.

Thanks for the answers above, I think they address the question well.
