### ISSUE TITLE
Syntax has much room for improvement

### ISSUE THREAD

**Issue by Jakobovski** [carbon-language/carbon-lang#1686]
First of all awesome project! Great work, a much needed language.

I think the syntax has much room for improvement. It's readability is mediocre when it should be great. As a simple example `i32` imo should be `int32`, it's just way more readable.  A beautiful, readable, and more standard syntax makes a language far more pleasant to use, encourages adoptions, and will result in less buggy code

If you think I am wrong and the syntax is good, I suggest you do a poll on twitter and see what people think. 

If it's not too late to improve the syntax I would be happy to help out and come up with a good a design.

**Comment by robiot** [comment]
You can do polls on Github discussions, Twitter isn't needed.

**Comment by emillaine** [comment]
Created a poll for the `i32` vs `int32` issue: https://github.com/carbon-language/carbon-lang/discussions/1696

**Comment by zygoloid** [comment]
Thanks for your interest! If you have new information and can make a compelling case for how some syntactic changes would objectively and substantially make the Carbon language meet its goals better, please file a specific issue describing those changes, or add a reaction to an existing issue if it has already been filed. However, please be aware that [many syntactic choices are subjective and have already been debated at length](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#why-arent-people-willing-to-discuss-certain-topics-like-the-file-extension-or-syntax-for-specific-constructs), and minor syntactic improvements aren't the highest priority at the moment.

This specific issue as it stands is too non-specific to be useful, and a separate issue for the `i32` versus `int32` suggestion has already been opened, so I'm closing this.
