### ISSUE TITLE
Fixed Spellings and Grammar in Docs

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [carbon-language/carbon-lang#1695]
#1693 

Please review this pull request, I have made to improve the docs

**Comment by MrKrishnaAgarwal** [comment]
#1693

**Comment by robiot** [comment]
Thanks for the pull request. You don't have to create a issue to refer to an already created pull request. Instead have some patience and wait for someone in the organization to review and maybe merge. 

@mconst Close this (You have officially became the `#1` issue closer :rofl: )

**Comment by MrKrishnaAgarwal** [comment]
Thanks a lot
Sorry for the inconvenience caused
