### ISSUE TITLE
Is Quicksort in readme serious?

### ISSUE THREAD

**Issue by abcxcba** [carbon-language/carbon-lang#1726]
```
package Sorting api;

fn Partition[T:! Comparable & Movable](s: Slice(T))
     -> i64 {
  var i: i64 = -1;

  for (e: T in s) {         //  in use
    if (e <= s.Last()) {
      ++i;
      Swap(&s[i], &e);  // modification
    }
  }
  return i;
}

fn QuickSort[T:! Comparable & Movable](s: Slice(T)) {
  if (s.Size() <= 1) {
    return;
  }
  let p: i64 = Partition(s);
  QuickSort(s[:p - 1]);
  QuickSort(s[p + 1:]);
}
```
The 's' being iterated over inside the for loop can be modified inside the loop?
Is the patition function implemented in the correct logic?
Can Quicksort sort correctly?

Sorry to ask such a question, I just started learning programming a month ago and can't read such code.

**Comment by jonmeow** [comment]
Please don't use issues for questions like this; assume that examples are intended to work.

If you have a specific concern about the example, that is what issues are for. if you're simply unfamiliar with QuickSort, it's a standard algorithm and you'll find many references for it online.

**Comment by abcxcba** [comment]
> Please don't use issues for questions like this; assume that examples are intended to work.
> 
> If you have a specific concern about the example, that is what issues are for. if you're simply unfamiliar with QuickSort, it's a standard algorithm and you'll find many references for it online.

Please take a closer look at the Partition function, is it right? I think it's wrong.
I don't think you're even reading what I'm talking about, are you?

**Comment by abcxcba** [comment]
> Please don't use issues for questions like this; assume that examples are intended to work.
> 
> If you have a specific concern about the example, that is what issues are for. if you're simply unfamiliar with QuickSort, it's a standard algorithm and you'll find many references for it online.

Look here: [https://en.wikipedia.org/wiki/Quicksort](url)

The Lomuto partition scheme should be what the sample code in the readme is trying to accomplish.
But take a closer look at the implementation of the code.
The patition function in the readme code has a number of errors that make it even less capable of partitioning the data properly.

Error 1:
for ( e in s), when using such an iterative loop, the iterated s is not supposed to be modified in this for, otherwise the code will be confusing.

Error 2:
And e will iterate over every value of s, including s.last(), so you can't use a judgment statement like if (s <= s.last()).

Error 3:
Missing step.

The correct implementation in wiki page is:
```
// Sorts a (portion of an) array, divides it into partitions, then sorts those
algorithm quicksort(A, lo, hi) is 
  // Ensure indices are in correct order
  if lo >= hi || lo < 0 then 
    return
    
  // Partition array and get the pivot index
  p := partition(A, lo, hi) 
      
  // Sort the two partitions
  quicksort(A, lo, p - 1) // Left side of pivot
  quicksort(A, p + 1, hi) // Right side of pivot

// Divides array into two partitions
algorithm partition(A, lo, hi) is 
  pivot := A[hi] // Choose the last element as the pivot

  // Temporary pivot index
  i := lo - 1

  for j := lo to hi - 1 do 
    // If the current element is less than or equal to the pivot
    if A[j] <= pivot then 
      // Move the temporary pivot index forward
      i := i + 1
      // Swap the current element with the element at the temporary pivot index
      swap A[i] with A[j]

  // Move the pivot element to the correct pivot position (between the smaller and larger elements)
  i := i + 1
  swap A[i] with A[hi]
  return i // the pivot index

```

**Comment by abcxcba** [comment]
> Please don't use issues for questions like this; assume that examples are intended to work.
> 
> If you have a specific concern about the example, that is what issues are for. if you're simply unfamiliar with QuickSort, it's a standard algorithm and you'll find many references for it online.

I hope you can prove me wrong that such code does what it wants to do inside carbon.
Or show the benefit of having an obviously wrong code in the most obvious place in the language introduction.

**Comment by abcxcba** [comment]
I have never seen such a glaring error in the introduction of any other language.
What a horrible mistake this is.
Especially for a language that wants to replace C++.
