### ISSUE TITLE
Adding to Debian repository

### ISSUE THREAD

**Issue by patranger** [carbon-language/carbon-lang#1732]
It would make programming in Carbon a lot easier as if the language will be added to the Debian 11 and 12 repository.

**Comment by WarEagle451** [comment]
Isn't Debian a Linux OS? Carbon should be able to compile and run on all platforms but IMO is shouldn't be the languages job to implement it's self into other projects and code bases. I've never used Debian so I may be misunderstanding what you're saying.

**Comment by int3l** [comment]
Meanwhile if you want to "install" Carbon-language on Linux / Ubuntu 22.04 LTS.

Container:

```bash
apt-get install -y build-essential clang git libc++-dev lld wget zlib1g-dev
wget https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -O /usr/local/bin/bazel
chmod +x /usr/local/bin/bazel
git clone https://github.com/carbon-language/carbon-lang
cd carbon-lang
bazel run //explorer -- ./explorer/testdata/print/format_only.carbon
```

VM:

```bash
sudo apt install -y build-essential clang git libc++-dev lld wget zlib1g-dev
sudo wget https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -O /usr/local/bin/bazel
sudo chmod +x /usr/local/bin/bazel
git clone https://github.com/carbon-language/carbon-lang
cd carbon-lang
bazel run //explorer -- ./explorer/testdata/print/format_only.carbon
```

PS: 📟 ping @ThePrimeagen 😝

**Comment by josh11b** [comment]
It is way too early for Carbon to have a package in various linux distributions.

**Comment by patranger** [comment]
@josh11b Maybe but Carbon is being made by Google in a such way, so I don't know if it's too early. Nim language and Haxe, which has no connection with such a large corporation as Google, is available in the repository of most operating systems, so as for the language behind one of the largest corporations in the world, I would say that it should already be available in the Debian and Arch Linux repositories. It would be acceptable if there was a dedicated repository to add in Debian sources.

**Comment by geoffromer** [comment]
Carbon is not "the language behind one of the largest corporations in the world". Carbon is an experiment, and even if the experiment is successful, it is likely [years away](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon) from being ready for anyone to use (even Google). Packaging Carbon for users, when Carbon is not actually usable, would be doing those users a disservice.
