### ISSUE TITLE
Is the carbon standard library the C++ standard library, or something else?

### ISSUE THREAD

**Issue by rconde01** [carbon-language/carbon-lang#1743]
Do we reuse that C++ knowledge or will it be something designed from scratch?

**Comment by pacion** [comment]
I recommend you to read the docs, there are all the informations connected to this reference.

**Comment by rconde01** [comment]
Could you add a link? I skimmed the docs but nothing obvious jumped out at me other than Carbon would create it's own containers.

**Comment by jonmeow** [comment]
Please use GitHub Discussions or Discord to ask questions language questions; issues should only be used when there's a bug, feature, or some other thing actionable with a PR.

Building a standard library is at the top of the language tools and ecosystem goal: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#language-tools-and-ecosystem
