### ISSUE TITLE
Failure in pointer derefernce

### ISSUE THREAD

**Issue by pmqtt** [carbon-language/carbon-lang#1783]
This code should not work, because  *x is a address and not a value!
```
fn test(var i: i32*)-> Bool{
    if(*i == 10){
        return true;
    }else{
        return false;
    }
}

fn Main() -> i32 {
  var b: Bool* = heap.New(true);
  var i: i32* = heap.New(10);
  var x: i32** = &i;
  if (test(i) ){
    return 1;
  }
  return 0;
}
```
I am reight ?

**Comment by pacion** [comment]
What do you mean by talking should not work?

**Comment by pmqtt** [comment]
Hi,
the method test expected a i32*, but get a i32**... From my point of view is this wrong...

**Comment by sobieh** [comment]
You are still passing **i** to test() but i assume you meant to test(**x**).
In current form it looks absolutely valid for me.

**Comment by pmqtt** [comment]
I'm so sorry... It is to late in  germany... ! Sorry !!!!
