### ISSUE TITLE
Docs refer to `Optional` both as a choice type and a class type

### ISSUE THREAD

**Issue by h3har** [carbon-language/carbon-lang#1788]
The design documentation refers to `Optional` in different places as a choice type and a class type, which appears contradictory.

The [specialization](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/generics/details.md#specialization) section of the generics doc implies that `Optional` is a class type and demonstrates how specialization can enable developers to implement optimizations for how `Optional` is stored for their own types.

The [error handling](https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#error-handling) section of the design README implies that `Optional` is a choice type (which would have the benefit of cooperating easily with pattern matching).

If `Optional` was to be a class, I assume there are plans to enable classes to behave like choice types and participate in pattern matching. In this case, it would perhaps be preferable that whether the type was actually a choice type or class type would be an implementation detail that an API designer could change without breaking other code.

**Comment by h3har** [comment]
See #1796 instead, where I changed this into a quasi-proposal.

**Comment by h3har** [comment]
Perhaps this "Close as not planned" method of closure was more appropriate...

...Github's not letting me do it.

**Comment by hddharvey** [comment]
Closing as not planned (replaced with a proper proposal)
