### ISSUE TITLE
Implement `Print`

### ISSUE THREAD

**Issue by CodeKitty-max** [carbon-language/carbon-lang#1801]
Return is performing the same function as ```Print``` for other data types. Print on the other hand only accepts string data type rather than all data types. For instance, attempting to Print the result of the main function of "/explorer/testdata/array/nested.carbon" returns:

a type error in Print argument 0
expected: String
actual: i32

```return``` on the other hand functions the same way print does.
Wouldn't it be practical if ```Print``` supported all data types?

**Comment by jonmeow** [comment]
The current `Print` is just a stub while other languages features are built. I'll leave this open for tracking, but I don't think the explorer is ready yet to do it.

**Comment by Zhanytrix** [comment]
Hello, you can print i32 values in Print("") using {0}, value.
That is an example: 
```
fn Main() -> i32 {
    var num1: i32 = 0;
    var num2: i32 = 0;
    Print("The sum is: {0}", num1+num2);
    return 0;
}
```

I hope this will help you.

**Comment by CodeKitty-max** [comment]
Understood, will give you feedback on what I see

**Comment by CodeKitty-max** [comment]
It has worked. Is there support for f32?

**Comment by Zhanytrix** [comment]
Currently, it does not seem possible to declare f32 variables or even use them.

**Comment by CodeKitty-max** [comment]
Yes. That's my experience so far with f32 as I am trying to build something in Carbon. I will keep exploring.

**Comment by jonmeow** [comment]
Note, this is blocked on #2110

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
