### ISSUE TITLE
Target JavaScript Developers ONLY

### ISSUE THREAD

**Issue by samsafay** [carbon-language/carbon-lang#1812]
I think you should only target `JavaScript` developers.
Why would an expert in a fast language like C++, Rust or GO want to jump on something new?

On the other hand many JavaScript developers are backend and Full Stack mobile developers (Node and React-native).
We want a C++ performance for JavaScript but it doesn't exist (look at the hype around [BUN](https://bun.sh/) which is trying to be that)

There are more JavaScript developers out there than any other language. So you will have a bigger community, hence more impactful.

I as a JavaScripter am willing to learn something that resembles JavaScript. It should include all its features like `Closures`, `Async Generators`, `Async/Await Promises`, `Callback Pattern`, `First-class Functions`, `Functional Nature (map, reduce, filter, some etc)`, `Aarrow Functions`, `OOP Support`, `Pass by Reference`, `Destructuring Assignment`, `Spread Operator`, `const let` etc.

For types please be inspired by RUST not Typescript. I prefer the return type from a function to have `->` instead of `:` like:
```
const square = (input: number ) -> number => x * x
```
instead of this 
```
const square = (input: number ) : number => x * x
```

**Comment by Skeltpr** [comment]
As someone who’s wanted to use Rust for ages, but cannot because of reliance on existing C++ libraries, this language’s design being based on Rust’s is a dream and I wouldn’t have it any other way.

With that said, if you want a JS-like system level language, have you considered Haxe? It’s syntax is super similar to JS/TS, and it compiles to native C and C++. Feel it would fit your use-case much more.

**Comment by samsafay** [comment]
Thanks for the feedback. I Have heard of HAXE but not sure how large its community is. 

I am actually not trying to change the design philosophy of Carbon, its probably too late! But rather hoping this message will find its way into other decision makers that there is huge demand for a fast JS-like system language that has been neglected by the FANG.

My dream is a native AOT for JS so I can use npm packages but I thought that's off-topic to mention on another language's GitHub issue.

**Comment by badolsmito** [comment]
Carbon isn't like Rust. It's not there to prevent memory leaks. Javascript developers would definitely have lots of memory leaks in their programs because they don't know how to properly write performant applications.

**Comment by geoffromer** [comment]
What you're asking for here would be a fundamentally different project, with different [goals](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#interoperability-with-and-migration-from-existing-c-code), a different design, a different audience, and different people working on it. Consequently, it's off-topic here.
