### ISSUE TITLE
Rework of `.devcontainer`

### ISSUE THREAD

**Issue by beryll1um** [carbon-language/carbon-lang#1816]
Rework of `.devcontainer` to use `homebrew/brew` docker image.

Purpose of this change is excluding centos7.9.2009 from current configuration. It's installing homebrew and it's dependencies by itself. Furthermore, it's building curl by itself, so it takes a lot of time. 

It's not so important, but most part of community using Ubuntu for now (It's my conclusion based on my observation in Discord community chats). `homebrew/brew` image based on ubuntu22.04 for now, so it's will be cool and so convenient.

**Comment by geoffromer** [comment]
Did you mean for this to be a pull request?

**Comment by beryll1um** [comment]
> Did you mean for this to be a pull request?

Hello. No. I planned to discuss the past solution here, and created a pull request to provide a comparison solution. There seems to be a discussion going on there already, so let's leave that for history.

pull: #1817

**Comment by jonmeow** [comment]
I think #1817 fixes this, so closing.
