### ISSUE TITLE
Pull Request and Issue Template 

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [carbon-language/carbon-lang#1832]
One suggestion from me is that, the maintainers of this repository can add around 4-5 Issue Templates and The most important I think is Pull Request Template, so that the person making the pull request remembers to provide a description and prerequisites. and follow the tasks, like this:

- [x]  Provided Description
- [x]   Provided Title

**Comment by MrKrishnaAgarwal** [comment]
> One suggestion from me is that, the maintainers of this repository can add around 4-5 Issue Templates and The most important I think is Pull Request Template, so that the person making the pull request remembers to provide a description and prerequisites. and follow the tasks, like this:
> 
> * [ ]   Provided Description
> * [x]   Provided Title

**Comment by MrKrishnaAgarwal** [comment]
Should I create a pull request adding Pull Request and Issue Template?

**Comment by geoffromer** [comment]
What problem(s) are you trying to solve?
