### ISSUE TITLE
Failed to compile and run explorer

### ISSUE THREAD

**Issue by redjoker011** [carbon-language/carbon-lang#1840]
Hello I'm following the Getting Started section and installed preq-requisite packages but encountered an error when running `bazel run //explorer -- ./explorer/testdata/print/format_only.carbon`

<img width="1427" alt="Screen Shot 2022-07-30 at 11 38 34 PM" src="https://user-images.githubusercontent.com/22144212/181924499-968dbf7e-55d6-4fea-8261-063208c49d6d.png">

I'm using macOS M1 Chip if that matters

**Comment by jonmeow** [comment]
This looks like issues with the clang/llvm install, please see build troubleshooting:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#troubleshooting-build-issues
