### ISSUE TITLE
new_proposal.py: could not request reviewer: 'carbon-language/carbon-leads'

### ISSUE THREAD

**Issue by foxtran** [carbon-language/carbon-lang#1841]
I tried to create a new proposal and I got the following error:
```
 RUNNING: /usr/bin/gh pr create --draft --label proposal --project Proposals --reviewer carbon-language/carbon-leads --repo carbon-language/carbon-lang --title 'Multidimensional array' --body 'TODO: add summary and links here'
Warning: 1 uncommitted change
could not request reviewer: 'carbon-language/carbon-leads' not found
ERROR: Command failed: /usr/bin/gh pr create --draft --label proposal --project Proposals --reviewer carbon-language/carbon-leads --repo carbon-language/carbon-lang --title 'Multidimensional array' --body 'TODO: add summary and links here'
```

After removing `--reviewer carbon-language/carbon-leads`, PR was successfully created.

My version of `gh` is:
```
$ gh --version
gh version 2.14.2 (2022-07-15)
https://github.com/cli/cli/releases/tag/v2.14.2
```

**Comment by geoffromer** [comment]
I believe you can work around this issue by [obtaining contributor access](https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#collaboration-systems), and if you're trying to contribute to the project, you should probably do that anyway.

If nothing else, we should probably provide a more helpful error message.
