### ISSUE TITLE
Running without LLVM in PATH caches the wrong `llvm_bindir` on macOS

### ISSUE THREAD

**Issue by clavin** [carbon-language/carbon-lang#1842]
The current official build instructions indicate you need to add homebrew-installed LLVM to your `PATH` env var. If, for any reason, you forget to do this on your first run, then `bazel/cc_toolchains/clang_configuration.bzl` will determine the detected variable `llvm_bindir` to be `/usr/bin`, leaving a contributor with a confusing error message similar to this:

```
ERROR: /private/var/tmp/_bazel_xyz/3270e4af245a133976d398d0b16f8498/external/com_google_absl/absl/debugging/BUILD.bazel:171:11: Linking external/com_google_absl/absl/debugging/libdebugging_internal.a failed: (Exit 1): llvm-ar failed: error executing command /usr/bin/llvm-ar @bazel-out/darwin_arm64-fastbuild/bin/external/com_google_absl/absl/debugging/libdebugging_internal.a-2.params

Use --sandbox_debug to see verbose messages from the sandbox
src/main/tools/process-wrapper-legacy.cc:80: "execvp(/usr/bin/llvm-ar, ...)": No such file or directory
```

Even if the LLVM installation is later added to your `PATH`, you will still continue to receive this error message as trying to rebuild will still try to use the erroneous, cached `llvm_bindir` variable previously determined.

A simple workaround in the troubleshooting docs (that I missed):

1. Make sure you have added LLVM to your path, per the getting started instructions, then
2. Run `bazel clean` to get back to a clean slate.

Trying to build your chosen target should now work without running in to that error due to the `llvm_bindir` no longer being cached and pointing to the wrong directory.

It was [mentioned in Discord](https://discord.com/channels/655572317891461132/824137170032787467/1002740695787913294) that an issue should be filed to track this build error.

A possible solution might be better guards on the path filled in for the `LLVM_BINDIR` substitution in the `clang_configuration.bzl` Starlark script, checking that other LLVM tools are present in that path and emitting a helpful build error message if they aren't. ~~Another option is just to add this info to the troubleshooting docs.~~

**Comment by jonmeow** [comment]
Assigning this to @chandlerc because I'm not sure what he had in mind. We already document the need to `bazel clean` in build troubleshooting:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#troubleshooting-build-issues

**Comment by clavin** [comment]
Based on the way his message is written, he might have thought that it was something different/more serious than this common build configuration issue. I'm embarrassed I too missed the fix in the troubleshooting guide.

Would a small check for the presence `llvm-ar` in the detected `llvm_bindir` as a safety guard for contributors be helpful? It's not exhaustive but it certainly would help. Happy to contribute it in attempt to reduce the volume of duplicate issues created for this common troubleshooting error y'all triage through 🙂

**Comment by jonmeow** [comment]
chandlerc wrote most of this (the bzl files); it's possible he wasn't reading closely, but he may have also had something specific in mind.

> Would a small check for the presence `llvm-ar` in the detected `llvm_bindir` as a safety guard for contributors be helpful?

Sure! I think it's definitely an issue that the config isn't validating it found all the tools it expects. I'm kind of concerned about it breaking some people who've found non-standard solutions, but I think it's probably a good starting point.

**Comment by 3405691582** [comment]
As it stands, there are three (related) problems:
* if the host platform provides `llvm-ar` in a location that is not beside `clang` (but still in `PATH`), we'll fail unnecessarily despite lying about `PATH` in the error message;
* removing the `fail` (conditionalizing it with a `repository_ctx.which` or what have you) makes this go away of course, but we still assume that `LLVM_BINDIR` has both `clang` and `llvm-ar` adjacent to each other in `bazel/cc_toolchains/clang_cc_toolchain_config.bzl`;
* the build seems to work okay anyway (maybe that's just because I have `--override_repository=com_google_absl=/...` right now?) 

The right thing to do is clearly if I just send a pr to have a `CLANG_BINDIR` and an `LLVM_BINDIR` or similar, but I'm most confused by the third part. Is there a particular target that will definitively invoke `ar` to test this on, because `//explorer` doesn't seem to be doing it?
