### ISSUE TITLE
VSCode extension?

### ISSUE THREAD

**Issue by wildaces215** [carbon-language/carbon-lang#1860]
Hi there I'm seeing carbon for the first time and looks really good! Is there a vscode extension so that it can aid in making programs?

**Comment by elvodqa** [comment]
`Carbon Language is currently an experimental project. There is no working compiler or toolchain. `
It will probably be in the future when the first version of Carbon is released but meanwhile, you can make your own syntax highlighting.

**Comment by jonmeow** [comment]
Just noting, there are others working on contributing an extension.

**Comment by wildaces215** [comment]
Ok I'll close the issue thanks for letting me know!
