### ISSUE TITLE
Action Ubuntu Test is broken 

### ISSUE THREAD

**Issue by pmqtt** [carbon-language/carbon-lang#1865]
Hi everyone,
Currently, the initializing of the workflow action 
test / test (ubuntu-latest, opt) (pull_request_target) failed!
![image](https://user-images.githubusercontent.com/51272730/182146978-fad20013-00f4-4ad2-982f-f0bd22c60f06.png)

Best regrads!

**Comment by pmqtt** [comment]
I checked if a code change I made caused the test to fail. I just ruled that out, I tried to build a PULL request without any changes. This doesn't work either

**Comment by jonmeow** [comment]
This looks like a (temporary?) issue with homebrew: https://github.com/Homebrew/homebrew-core/commit/463e65eb7c30a7607c6f895108ee5da71dbe60e7

Need to think about options here, it's not clear what's intended and we probably shouldn't build llvm from scratch.

**Comment by jonmeow** [comment]
Actual commit that probably caused this: https://github.com/Homebrew/homebrew-core/commit/e90cd9845777a0d420ef350c191a6b41a2a9a922

To check state at head: https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb

**Comment by chandlerc** [comment]
Lots of discussion in Homebrew/homebrew-core#100411 -- they've worked around this for us, so things should be back to normal. We also have some more options we've prototyped now to handle when their big GCC-12 breakage happens for real. Closing this now that things seem back to green for the moment.
