### ISSUE TITLE
Explorer: missing support for class `base`, `abstract`, and `extends`

### ISSUE THREAD

**Issue by Pixep** [carbon-language/carbon-lang#1881]
The explorer generates a non-specific syntax error when trying to use class prefix or extends.

**Comment by Tom-debug110** [comment]
haha，I agree you.

**Comment by Pixep** [comment]
@jonmeow if we focus this issue on "Inheritance" (outside of virtual methods, etc., as in the wiki), I think we can consider this one "done" to the degree we might want to support it in explorer.

**Comment by Pixep** [comment]
Closing this one, based on the current Explorer implementation level 🥳
