### ISSUE TITLE
Add note for meeting process to CONTRIBUTING

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#1900]
A few things CONTRIBUTING.md could help with:

- Process, particularly "raise hands" with a link to the appropriate help page
- How to get an invite to meetings (need to ask explicitly, we won't add without explicit request -- seeing the calendar is enough to join).

**Comment by sirlordt** [comment]
Where is the calendar to meeting?

**Comment by ryoari** [comment]
has this been resolved? if not what needs to be done?

**Comment by jonmeow** [comment]
Marking closed -- I imagine the doc will keep evolving, but the process is covered elsewhere at this point.
