### ISSUE TITLE
Support for full static executables like go lang

### ISSUE THREAD

**Issue by sirlordt** [carbon-language/carbon-lang#1906]
Create very portables executable can run with no dependencies from libc or libstdcxx is great for cloud native apps.

You can compile in Ubuntu 22.04 and run in any distro for example Alpine or Ubuntu 12.04 with no issues with the libc version.

Of course when the project only use full carbon libraries. Or when this are possible with no dynamic linking of external .so/.dll

**Comment by geoffromer** [comment]
I expect Carbon will support this, but probably not for a while -- we don't even have a compiler yet.

I'm closing this as "not planned" to keep our issues list clean, but really it's "not planned _yet_".

**Comment by sirlordt** [comment]
Ok thanks for the feedback!!!!
