### ISSUE TITLE
Move Carbon Vim Plugin into Separate Repository

### ISSUE THREAD

**Issue by davidzchen** [carbon-language/carbon-lang#1921]
I think the [Carbon Vim plugin](https://github.com/carbon-language/carbon-lang/tree/trunk/utils/vim) should be moved into a standalone Git repository.

This will make it a lot easier for developers who use Vim package managers, such as Vundle, Pathogen, or even Vim's new built-in package manager as of Vim 8.

**Comment by davidzchen** [comment]
+cc @x2w-sloth @jonmeow WDYT?

**Comment by jonmeow** [comment]
This has already been discussed, and the intent is to generally manage edits within Carbon's main repository, mirroring subdirectories over to other repositories. https://github.com/carbon-language/carbon-lang/pull/1863 has a draft implementation of this. Does that seem reasonable to you?

**Comment by x2w-soda** [comment]
I understand that a standalone repository is easier for package managers to download or update the plugin, perhaps mirroring is indeed a good way to keep actual files in the base repo and have a mirrored standalone repo for vim package managers.

**Comment by chandlerc** [comment]
This should be fixed now that #1863 is merged. See: https://github.com/carbon-language/vim-carbon-lang

Happy to have PRs to the `utils/vim` directory to add/fix anything needed to make this work well.
