### ISSUE TITLE
No pointer incrementation, so how do you propose to write proper containers?

### ISSUE THREAD

**Issue by mattreecebentley** [carbon-language/carbon-lang#1941]
Most containers rely on pointer incrementation to some extent, more notably vector, and indexes are always slower (I have not seen a single case in the last 10 years that has changed this perspective, and have done numerous tests myself). 
How do you propose to implement containers without supporting pointer incrementation?

Side-note, not clear on the advantage of not being able to null pointers. Some magic value is always necessary when it comes to writing containers.

**Comment by jonmeow** [comment]
We expect most pointers _shouldn't_ be incremented; typically it's just a single object allocated, not an array. Thus the plan is that normal pointers won't be incrementable in order to avoid bugs such as:

```cpp
void Accumulate(int* sum, int val) {
    sum += val;
}
```

A type which is dedicated towards pointers that _need_ to be incrementable for C++ interop purposes is likely. Note that Carbon containers may not need this to be implemented; nothing's wrong with tracking offsets another way so long as the resulting performance is equivalent.

**Comment by mattreecebentley** [comment]
On 7/08/2022 1:35 pm, Jon Ross-Perkins wrote:
> We expect most pointers /shouldn't/ be incremented; typically it's just 
> a single object allocated, not an array. Thus the plan is that normal 
> pointers won't be incrementable in order to avoid bugs such as:
> 
> void  Accumulate(int* sum,int  val) {
>      sum += val;
> }
> 
> A type which is dedicated towards pointers that /need/ to be 
> incrementable for C++ interop purposes is likely. Note that Carbon 
> containers may not need this to be implemented; nothing's wrong with 
> tracking offsets another way so long as the resulting performance is 
> equivalent.

Tracking via indexes is *never* equivalent in terms of performance.
Please re-open, unless you actually genuinely intend to doom this 
language to less-than-optimal performance.

**Comment by mattreecebentley** [comment]
Please take a look at how many more instructions are needed for index addressing vs pointer addressing, even in this most-simple of examples - yes, debug mode, but debug mode performance is very important for a lot of fields:
https://godbolt.org/z/Mobj7sxEb

**Comment by cdmaczane** [comment]
A related concern of mine is how we are expected to write memory allocators without pointer arithmetic? Are we supposed to drop down to C/C++? Pointers need to be aligned and differences calculated without storing extra metadata. I feel like it also makes many algorithms more natural. Maybe this could all be achieved with byte arrays, offset indices and casting? 🤔

**Comment by geoffromer** [comment]
@mattreecebentley I've edited your comment above to remove a personal attack. Please take a moment to familiarize yourself with our [code of conduct](https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md).

I'd also suggest moving this topic to a [discussion](https://github.com/carbon-language/carbon-lang/discussions) if you want to continue it. We're trying to reserve our issues list for things that can be resolved in the near term with a pull request.

**Comment by jonmeow** [comment]
> Please take a look at how many more instructions are needed for index addressing vs pointer addressing, even in this most-simple of examples - yes, debug mode, but debug mode performance is very important for a lot of fields:

Certainly there are trade-offs for debug performance, and our [safety strategy](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/safety_strategy.md) lays out thoughts there. There may also be options to reduce overhead.

Mainly though, I think it's a bit too early to commit to any given approach: we're still at a level of language design that's sketching out the core language, and data structures will come some time after that. For all the vagueness to that answer, the question of pointer arithmetic support can be answered independent of library choices: I do expect a semantic equivalent for pointer arithmetic will be supported.

> A related concern of mine is how we are expected to write memory allocators without pointer arithmetic? Are we supposed to drop down to C/C++? Pointers need to be aligned and differences calculated without storing extra metadata. I feel like it also makes many algorithms more natural. Maybe this could all be achieved with byte arrays, offset indices and casting? 🤔

The main point is that many pointer uses in C++ don't need arithmetic, so using a different type for when arithmetic _is_ required can create a useful boundary to prevent programmer errors. We think providing separate types is a reasonable balance for reducing bugs while still providing flexibility.

Also see zygoloid's comment: https://github.com/carbon-language/carbon-lang/discussions/1954#discussioncomment-3353776

**Comment by mattreecebentley** [comment]
What on earth are you talking about?

**Comment by mattreecebentley** [comment]
> @mattreecebentley I've edited your comment above to remove a personal attack. Please take a moment to familiarize yourself with our [code of conduct](https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md).
> 
> I'd also suggest moving this topic to a [discussion](https://github.com/carbon-language/carbon-lang/discussions) if you want to continue it. We're trying to reserve our issues list for things that can be resolved in the near term with a pull request.

If you perceived it as a personal attack, I would disagree.

**Comment by mattreecebentley** [comment]
> > Please take a look at how many more instructions are needed for index addressing vs pointer addressing, even in this most-simple of examples - yes, debug mode, but debug mode performance is very important for a lot of fields:
> 
> Certainly there are trade-offs for debug performance, and our [safety strategy](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/safety_strategy.md) lays out thoughts there. There may also be options to reduce overhead.

But this isn't a debug-performance-only problem.
In the example I gave you, when you switch GCC to -O2 the compiler is able to turn the index-based incrementation into a pointer-based one, simply *because* the example is so simple.
In anything approximating a real program, wherever the iteration is not strictly linear (and even sometimes where it is), the compiler will probably not be able to optimize this into pointer incrementation. 

As a more real-world example, with plf::hive/colony, I've over the years experimented several times with turning the pointer-based iterators into index-based ones. This reduces cache use, as it reduces the iterator size from 192bits to 80bits. In reality though, the constant need to do array + offset calculations always led to ~5% performance reductions across all benchmarks, including straight iteration.

Simply put, unless you support pointer incrementation, you are not going to get good performance.



> Mainly though, I think it's a bit too early to commit to any given approach: we're still at a level of language design that's sketching out the core language, and data structures will come some time after that. For all the vagueness to that answer, the

Well, that's exactly why I'm bringing this up now - I see you folks making what I consider to be a critical decision error, and that's likely to calcify. 
I get the impression that the exact target audience for this language is being figured out on the fly, which is not the best starting point. Clearly it's not for game dev, as they need fast debug builds, and anything else is no-go. In it's current state it is unlikely to suit most of SG14, as latency and performance are most important, and lack of low-level access like pointer incrementation is a no-go for the most part.

**Comment by chandlerc** [comment]
Just to try to clarify a bit, I don't think anyone is imagining that there would be *no* way to create an incrementable pointer. I think there will definitely be ways to do that.

The current design is based on the idea that the *default* pointer shouldn't be incrementable because most pointers are to single objects.

I would imagine we will have some specialized type(s) that specifically model the cases where an incrementable pointer is what you want and important for performance.

I think it is also good to nudge people towards considering indices. While there are cases that really require incrementing pointers to achieve peak performance, there are also many cases where an index would be as fast or faster, and provide significantly more flexibility for checking for bugs in debug builds with bounds checks, etc.

The goal is to have *both* facilities, and help folks use the right one for the task at hand.

> it's not for game dev, as they need fast debug builds, and anything else is no-go. In it's current state it is unlikely to suit most of SG14, as latency and performance are most important, and lack of low-level access like pointer incrementation is a no-go for the most part.

FWIW, we have folks working on Carbon that are very interested in exploring it for game development, low-latency and performance use cases, and low-level/hardware-focused use cases.

We have a goals document that pretty clearly lays out our priorities here, and performance is the top priority. Hopefully the above explains the strategy in more detail.

**Comment by chandlerc** [comment]
(I've separately hidden a comment that is off-topic. Please don't mix a debate about moderation into the technical discussion. I also checked with other moderators and other members of the conduct team and this was a correct moderation decision.)
