### ISSUE TITLE
Order of variable declaration is wrong

### ISSUE THREAD

**Issue by mattreecebentley** [carbon-language/carbon-lang#1942]
The syntax is objectively unintuitive - by saying that, I immediately create a distinction between 
(a) subjective unintuitiveness (based on culturally-specific differences or personal familiarity) and 
(b) objective unintuitiveness (based on cross-cultural and largely biology-driven preferences).

All natural languages start with generics and move to specifics, and so do programming languages. 
We have a heading with the general topic, then a paragraph with the specifics. 
We have a function name and the arguments, then we say what we do with those arguments.

We say:
"There was a being, a human named John, who was holding an apple."
We don't say:
"There was a being, whose name was John, a human, who was holding an apple."
because it moves from more specific (John) to less specific (human). 

Likewise we don't tend to say:
"An apple was being held by John, who was a human, and a being."

Then why do Carbon variable declarations look like this:?
var area: f32 = 1;

var is the least specific aspect (because there are many, many vars), the type of var (f32) is the second least specific (because there may be many f32's), the name is more specific (because there is only one of this name) and the value is the most specific (because it is a value ascribed to the specific name - or, technically, it's another statement concatenated).
So it should look like:
var f32 area = 1;

Except that 'var' is completely superfluous. 

In the following sentence:
"There was a being, a human named John, who was holding an apple."
"being" is implied by "human". We know that humans are beings, and therefore in most cases we would say:
"There was a human named John, who was holding an apple."
That is more natural.
Similarly, saying:
f32 area = 1;
is perfectly natural, as 'var' is implied by f32, and a function cannot begin with f32, and functions are prefixed by 'fn' anyway. Thus we come back to C++ syntax. There may be a desire to move away from that, based on simply wanting something different, but I don't see the case for it here.

I don't care necessarily if other languages follow this syntax ordering, that's no argument for it being good objectively.

**Comment by MuhammadMehediHasan** [comment]
I think they are going to implement dynamic data types. This is why they are declaring variables like that. It will be easier to opt out `f32` from `var area: f32 = 1` rather then from `var f32 area = 1` or `f32 area =1`.
```ts
// dynamic
var area = 1;
// declarative
var area: f32 = 1;
```
In your case
```ts
// dynamic
var area = 1;
// declarative
var f32 area = 1; // 1
f32 area = 1; // 2
```

I think the current variable declaration is okay if they want to implement dynamic data types. If they are not implementing dynamic data types, then the way c or c++ is used to declare variables is better.

**Comment by chandlerc** [comment]
> The syntax is objectively unintuitive - by saying that, I immediately create a distinction between (a) subjective unintuitiveness (based on culturally-specific differences or personal familiarity) and (b) objective unintuitiveness (based on cross-cultural and largely biology-driven preferences).
> 
> All natural languages start with generics and move to specifics, and so do programming languages.

As you mention below, many programming languages use the order "name" followed by "type"... But I'll get to that below.

I don't think this is true of "all natural languages", and I'm not a linguist or even particularly multilingual.

Just looking at https://en.wikipedia.org/wiki/Word_order I see a really amazing diversity of word orders across all kinds of words. Also lots of languages where you can *change* the word order. Written word order also seems especially unlikely to be universal across languages given that *words* are not universal across written languages...


But I think all of this is also not very relevant, even if there exist truly universal properties of natural languages (something I'm quite skeptical about after some quick discussions with anthropologists). We're not building a natural language, but an extremely structured and pragmatic artificial language. And it needs to work well for parsers and compilers as well as human developers. For example:

> Except that 'var' is completely superfluous.

It isn't superfluous, it is important for parsers. The lack of this is a major component that leads to C++'s https://en.wikipedia.org/wiki/Most_vexing_parse

> I don't care necessarily if other languages follow this syntax ordering, that's no argument for it being good objectively.

Other languages following this structure is at least an argument for there being a *risk* of confusing people who are familiar with those languages. How large of a risk? How many people fall into that category? We don't have good data, but the leads specifically considered this risk too high and decided to match the structure of other languages. It is a judgement call, but that's how we make decisions in the absence of a rigorous and comprehensive UX study of the specific issue for our specific target audience.

Until there is some new information or new widespread interest in revisiting this, I think we should close this as not-planned.

**Comment by zygoloid** [comment]
I went looking for how the C++ variable declaration syntax is described to beginners. The first example I found was in https://www.w3schools.com/cpp/cpp_variables.asp:

> Create a variable called `myNum` of type `int` and assign it the value 15:
>
> ```
> int myNum = 15;
> ```

Note that the English description is in the Carbon order, not the C++ order. That's certainly not evidence that the Carbon order is best, but it does suggest to me that there isn't an inviolable natural language rule that would put the static type before the name.

I agree with @chandlerc that we don't have enough new evidence from this issue to reconsider this decision.

**Comment by mattreecebentley** [comment]
On 7/08/2022 6:40 pm, Chandler Carruth wrote:
> I don't think this is true of "all natural languages", and I'm not a 
> linguist or even particularly multilingual.

By referencing wiki and wording ordering you've deliberately ignored the 
central point, which is that all languages, including programming 
languages, go from the generic to the specific by default and not the 
reverse. This is a necessarily property of Communication, not just 
languages. Consider why we put topic headings before a bullet point list, rather than after.
You are doing so to enforce your subjective preference, but it is not 
objectively relevant.


>     Except that 'var' is completely superfluous.
> 
> It isn't superfluous, it is important for parsers. The lack of this is a 

What I was saying in context is that it's superfluous from a semantic 
point of view. If it's necessarily for the parser in this case, that is 
fine.


> major component that leads to C++'s 
> https://en.wikipedia.org/wiki/Most_vexing_parse 
> <https://en.wikipedia.org/wiki/Most_vexing_parse>
> 
>     I don't care necessarily if other languages follow this syntax
>     ordering, that's no argument for it being good objectively.
> 
> Other languages following this structure is at least an argument for 
> there being a /risk/ of confusing people who are familiar with those 
> languages. How large of a risk? How many people fall into that category? 

That falls into the 'subjectively intuitive' category as noted.
Even if that were a concern, you can *obviously* counter with the same 
argument for the people who're familiar with the other styles. It's not 
worth discussing.


> We don't have good data, but the leads specifically considered this risk 
> too high and decided to match the structure of other languages. It is a 
> judgement call, but that's how we make decisions in the absence of a 
> rigorous and comprehensive UX study of the specific issue for our 
> specific target audience.
> 
> Until there is some new information or new widespread interest in 
> revisiting this, I think we should close this as not-planned.

Until you represent some objective point of view that addresses my 
specific points rather than just, basically, talking /around/ them, I 
don't think you should. I think you should actually contemplate this on 
an objective level, rather than going to great pains to paint it as 
subjective.

**Comment by mattreecebentley** [comment]
On 7/08/2022 6:08 pm, Mehedi Hasan wrote:
> I think they are going to implement dynamic data types. This is why they 
> are declaring variables like that. It will be easier to opt out |f32| 
> from |var area: f32 = 1| rather then from |var f32 area = 1| or |f32 
> area =1|.

If that's the case, that's fine, although I deeply hope they do not 
implement an 'auto' equivalent, as that is a horror of coding practice 
in my experience, and makes unfamiliar codebases essentially unreadable.

**Comment by mattreecebentley** [comment]
> I went looking for how the C++ variable declaration syntax is described to beginners. The first example I found was in https://www.w3schools.com/cpp/cpp_variables.asp:
> 
> > Create a variable called `myNum` of type `int` and assign it the value 15:
> > ```
> > int myNum = 15;
> > ```
> 
> Note that the English description is in the Carbon order, not the C++ order. That's certainly not evidence that the Carbon order is best, but it does suggest to me that there isn't an inviolable natural language rule that would put the static type before the name.

I agree that it's flexible based on context (humour writers often change the order specifically because upsetting the default order sounds funny, proving the rule), but in general it does tend to run from the generic to the specific.
The better question is, what is the valid objective reason for changing it from the C++ default to another one, given that C++ is the language it is meant to be interoperable with?
There's been one such suggestion above.

**Comment by chandlerc** [comment]
Repeatedly claiming a position that others disagree with is "obvious" and insisting that other views are not valid doesn't help understand why there is a disagreement, doesn't follow our code-of-conduct, and isn't how we discuss things in the Carbon community.

And even more so, please do not claim that people "deliberately ignored the central point" of your post. Accusations like this don't help make the discussion productive and are very much against our code-of-conduct.

There have been several warnings about conduct and communication here and elsewhere. If you can't communicate in a friendly and welcoming way, Carbon isn't the right place. This discussion is not productive so I'm closing and locking it.
