### ISSUE TITLE
Simple support for multiple return values from functions

### ISSUE THREAD

**Issue by mattreecebentley** [carbon-language/carbon-lang#1943]
I couldn't see support for multiple return values from a function in the documentation, so I will suggest this. If someone has a better idea or a reason why this is worse than declaring and returning a class or something, please inform me - there may be something I'm missing here.
Something as simple as:
`fn Sign(i: i32, j: i32) -> i32, i32
`
, where the return statement also supports comma-separated returns:
`return 4, 5;`

and the function call takes the form of:
`foo, bar = Sign(4, 5);
`
might suffice.

**Comment by jonmeow** [comment]
This is handled through returning a tuple, and tuple destructuring. 

Tuples: https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#tuples
Destructuring: https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#destructuring-patterns
