### ISSUE TITLE
May I recommend to use less disk space?

### ISSUE THREAD

**Issue by christianhujer** [carbon-language/carbon-lang#1944]
I installed Homebrew _only_ for Carbon (Bazel), and I've never used Bazel for anything.

And here's my disk usage:
```
christian.hujer@Nelkinda-Blade-Stealth-2:~/git/carbon-language/carbon-lang$ du -csh /home/linuxbrew/ ~/.cache/bazel
2.9G    /home/linuxbrew/
2.0G    /home/christian.hujer/.cache/bazel
4.8G    total
```
Almost 5 GB just for trying to play around with a programming language that wants to compete with C++? 5 GB is a bit much, don't you agree? May I suggest that Carbon uses less disk space? And yes, it's mostly not Carbon but Bazel and Brew, but using them is a choice.

**Comment by chandlerc** [comment]
FWIW, a lot of this is LLVM, not Bazel...

We're installing the LLVM and Clang toolchain to have a consistent host toolchain. And Bazel is building the LLVM and Clang libraries to use in our implementation. I don't think we have any really great alternatives here. But we do actually keep track of this, and will try to minimize the overhead where we can.

But none of this will really impact the experience of eventual Carbon users. These are only relevant for folks helping design and develop Carbon. In a few years, when we're looking at making this more accessible for users we'll of course want to provide as minimal packages as we can.

Last but not least, I'd ask to avoid talking about a "diet" or making other analogies to people's weight. Instead, just focus on "use less diskspace" or "reduce dependencies."

For now, as this really is just an implementation detail that no one is actively working on, closing as "not-planned".

Keep in mind, you can always try out Carbon without installing anything using https://carbon.compiler-explorer.com/

**Comment by christianhujer** [comment]
Point taken about "diet", changed the text.
