### ISSUE TITLE
CoC lacks honesty principles

### ISSUE THREAD

**Issue by mattreecebentley** [carbon-language/carbon-lang#1985]
The ISO CoC, for all it's faults, has good guidelines around honesty and not deliberately deceiving others.
These are practical and Do work. I have experience of this.
They are also necessary. Things tend to go downhill very rapidly where there are not consequences for dishonesty.
I am, frankly, surprised to not see a dishonesty clause in the CoC. This is likely to lead to a lot of avoidable passive-aggressive behaviour, later on.

Note that where dishonesty is apparent, it is not enough to merely say you think someone is being dishonest. You have to be able to prove that they are deliberately being dishonest, via previous communiques or otherwise, rather than simply mistaken.

**Comment by chandlerc** [comment]
I believe our CoC covers the parts of this it can under the section "When we disagree, we try to understand why".

Getting into dishonesty, especially deliberate dishonesty or deception, would push us towards personalizing the discussion if not leading to out-right accusations and other escalatory steps. That isn't the right approach. Instead, while the discussion remains friendly and welcoming, we'll try to keep understanding different viewpoints and perspectives. Once that's done, or if the discussion stops being friendly and productive, we'll ask it to stop and stick to that.

If folks can't discuss and even disagree in a friendly way, then Carbon isn't the community for them.
