### ISSUE TITLE
Reflect "Operator tokens #601" in the design docs

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#1992]
Proposal #601 was accepted but the design docs in https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design/lexical_conventions have not been updated to reflect its acceptance.

**Comment by josh11b** [comment]
https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design/lexical_conventions still says "TODO: operators"

**Comment by aswin2108** [comment]
Hey @Hech will you be continuing this or can I take over???

 @josh11b If I can should I continue the work on the pr which is already made or just make a new one!?

**Comment by josh11b** [comment]
Either is fine, but do please incorporate the feedback that was made on that PR, particularly the shift from "operator tokens" to "symbolic tokens".
