### ISSUE TITLE
Reflect "Comments #198" in the design docs

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#1994]
Proposal #198 was accepted but https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design/lexical_conventions/README.md still says "TODO: ... comments", and that should be linked from https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/README.md#code-and-comments . Since the design decision in #198 is somewhat surprising, it would be good to explain it and possibly the alternatives considered somewhere in the lexical_conventions directory.

**Comment by avinal** [comment]
Hello @josh11b, I would like to work on this issue.

**Comment by josh11b** [comment]
> Hello @josh11b, I would like to work on this issue.

Sounds good! You'll want to make sure you sign up for contributor access, see https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#collaboration-systems .

**Comment by avinal** [comment]
I have requested contributor access. In the meantime, I am going through the discussions.

**Comment by jonmeow** [comment]
FYI: creating PRs doesn't require contributor access (see the last paragraph of [getting access](https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#getting-access) for an explanation of what access is appropriate when)

**Comment by avinal** [comment]
Will add by this weekend.

**Comment by ghost** [comment]
Is there any additional help needed on this issue? I can dedicate time next week to help. I can check in on this issue in Discord Monday morning.

**Comment by josh11b** [comment]
> Is there any additional help needed on this issue? I can dedicate time next week to help. I can check in on this issue in Discord Monday morning.

@eeshvardasikcm , it looks like @avinal created #2064 but did not finish it. I am not aware of anyone else working on this.

**Comment by avinal** [comment]
Hey @josh11b @eeshvardasikcm, apologies for not being able to complete this till now, last few months were very busy. I don't have access to a system till 20th Dec, as soon I get back, I will push my changes. Also no additional help is required AFIR, if something comes up I will ping you. Thanks for your understanding.

**Comment by ghost** [comment]
> ...I will push my changes. Also no additional help is required...

Okay. There's a different issue that I can do. Thanks for the update. josh11b is monitoring this issue.

**Comment by aswin2108** [comment]
@avinal @josh11b Can I try it...?

**Comment by amyra98** [comment]
Can you please explain in detail what do I have to do? @josh11b and then assign me this issue

**Comment by aswin2108** [comment]
@amyra98 Actually I am working on this and will create a pr shortly!

**Comment by KAWALMEET-SINGH** [comment]
I want to work on this Issue  please assign me.

**Comment by jonmeow** [comment]
@KAWALMEET-SINGH We typically won't assign issues. I've added [some documentation for why](https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#implement-carbons-design). Please feel to work on it if you have time [a "good first issue" can help familiarize with the project], but please note aswin2108 recently sent out #2641.

**Comment by aswin2108** [comment]
Yeah, actually I was waiting for the review to happen! I was said that it was in the queue.
