### ISSUE TITLE
Make proposal for optional argument names

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#1996]
Unused argument names (e.g., `fn Foo(unused arg: i32)`) were the topic of leads question #476. The question was resolved, and the comment https://github.com/carbon-language/carbon-lang/issues/476#issuecomment-863011977 has details.

Because the question was asked independent of a proposal, a standard proposal is still needed for evolution review, essentially translating the issue into a proposed solution with rationale, alternatives considered, etc. This issue is to track the proposal need.

**Comment by matthew-russo** [comment]
I'd like to pick this up.

**Comment by rajeck1234** [comment]
can i fix this issue

**Comment by nikhil061102** [comment]
If no one is working on this issue, can it be assigned to me. I am new to the world of open source contribution and is very excited to start. This will also be a good start for me for GSoC 2023
Thank You

**Comment by jonmeow** [comment]
This was fixed by #2022, I think we just missed closing it. (Thanks Matthew!)

**Comment by nikhil061102** [comment]
Hello
It would nice if you could suggest some beginner level or easy issues which
I can look into. Thank you :)

**Comment by jonmeow** [comment]
@nikhil061102 We appreciate your interest, but do not make off-topic comments on issues; use discussion forums for generic help requests.
