### ISSUE TITLE
Make proposal for numeric type literal syntax

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#1998]
Fixed-size integer type names (e.g., `int` vs `i32` vs `int32`) were the topic of leads question #543. The question was resolved, and https://github.com/carbon-language/carbon-lang/issues/543#issuecomment-887106270 has details. I believe the answer covers `iN`, `uN`, and `fN`, even though the question started with `iN`.

Because the question was asked independent of a proposal, a standard proposal is still needed for evolution review, essentially translating the issue into a proposed solution with rationale, alternatives considered, etc. This issue is to track the proposal need.

Note, https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/lexical_conventions/numeric_literals.md#references should track what's been designed in this space.

Also note, I think the question of the underlying type (e.g. `Int(32)`) also is in need of a proposal; I'm not sure we have anything tracking that.

**Comment by chandlerc** [comment]
Let's focus this issue on officially covering `iN`, `uN`, and `fN` type literal syntax as aliases for `Carbon.Int(N)`, `Carbon.UInt(N)`, and `Carbon.Float(N)` (respectively). Further details of those `Carbon.*` types should be separate, and I think shouldn't even block getting the shorthand naming syntax in place.
