### ISSUE TITLE
Leverage Circle’s compiler work on generics 

### ISSUE THREAD

**Issue by dvader** [carbon-language/carbon-lang#2009]
Sean Baxter is doing some wicked, wicked work on generics and meta programming with his Circle C++ compiler and it works and compiles C++, it just adds a lot of nice features.  I would highly recommend Carbon takes a page from what he’s doing there. An example is his cppcon presentation https://youtu.be/15j4bkipuAg. 
1. Templates and packs
○ Templates, completed
○ Member traits
○ Circle Imperative Arguments (CIA)
○ Pack metafunctions
2. The Standard Library
○ std::tuple
○ std::variant 
○ std::mdspan

**Comment by jonmeow** [comment]
I'm converting this to a discussion. We use issues for things that can be addressed by a PR, and this feels more like general commentary to me.
