### ISSUE TITLE
Bug: stuck on image selection while dev container creation in VS Code

### ISSUE THREAD

**Issue by avinal** [carbon-language/carbon-lang#2043]
## The Problem

I am trying to use the devcontainer configuration to create a container using VS Code. But the step is stuck on image selection and since this is executed in a non-interactive shell, the container won't be created. See the screenshot.
![image](https://user-images.githubusercontent.com/74113200/184855138-4704f2b0-fd14-465e-b8fc-d16199f98952.png)

## System
- OS: Fedora 36
- VS Code: 1.70.1
- Podman: 4.1.1

## The fix

Modifying [this](https://github.com/carbon-language/carbon-lang/blob/trunk/.devcontainer/Dockerfile#L6) line to explicitly mention `docker.io` as required by #1816 solves this issue.
```dockerfile
FROM docker.io/homebrew/brew:${TAG}
```

## References
- #1816 
- #1817

**Comment by avinal** [comment]
If this seems good I would like to open a PR for the fix.

**Comment by geoffromer** [comment]
@cyw3 or @beryll1um might be able to weigh in on this.

**Comment by beryll1um** [comment]
@geoffromer I think fix is OK. Really, if some specified docker images sources contains same named containers under same named authors this bug will caused.
*VSCode devcontainer extension really have a non-interactive shell
We can specify to pull homebrew container from the specific source and it will solve the problem.
