### ISSUE TITLE
Getting an error while using For loop as specified in documentation 

### ISSUE THREAD

**Issue by Subhangini** [carbon-language/carbon-lang#2053]
**My code**
![image](https://user-images.githubusercontent.com/68437435/185012015-bebad6f0-264f-474e-afb4-bdcaeb281249.png)
**Error**
![image](https://user-images.githubusercontent.com/68437435/185012276-3e415304-0b9e-4b39-a2c3-202a0dc25403.png)

Getting the error in for loop.

**Comment by L4stR1t3s** [comment]
I think that var is not necessary in a for loop currently.
`for (name: String in names)`

The Carbon language is under construction though, so this may change.

**Comment by Subhangini** [comment]
> for (name: String in names)

That's too not working

    
![image](https://user-images.githubusercontent.com/68437435/185022718-66b6b746-4e6d-44b1-93ed-e7b77f85799a.png)

**Comment by L4stR1t3s** [comment]
`Print(name);` according to [example](https://github.com/carbon-language/carbon-lang/blob/trunk/README.md#carbon-and-c) in [README.md](https://github.com/carbon-language/carbon-lang/blob/trunk/README.md).

**Comment by Tomttth** [comment]
wouldn't it be good if we can reduce the redundancy for the for loop:
for (name: String in names)

as name is  again mentioning the type. Wouldn't it be nice if name can infer the type from array or the iterable.
so the above syntax can be shortened:
for (name in names)

**Comment by jonmeow** [comment]
Closing. Thank you @L4stR1t3s for answering this. I'll also note https://carbon.compiler-explorer.com/z/e1vfbzbxn for examples.

@Tomttth When people are asking how to get something to work, I think it's unhelpful to suggest changes to language syntax. Feel free to follow up on your post #2033, but this issue wasn't the right place for that.

**Comment by Tomttth** [comment]
Thanks for clarifying👍
