### ISSUE TITLE
Features : Python binding

### ISSUE THREAD

**Issue by arita37** [carbon-language/carbon-lang#2055]
Is it possible to have Minimal example to bind carbon functions/methods
to python (ie using PyBindGen) ?

**Comment by Tomttth** [comment]
I wonder if carbon is going to support foreign functions like java and other languages:
https://en.wikipedia.org/wiki/Foreign_function_interface

**Comment by jonmeow** [comment]
You can read our language roadmap here: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/roadmap.md

When it comes to cross-language interoperability, C++ is our top priority. I'm sure Python support would eventually become a priority, but it's likely to be [years out](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon). We aren't tracking things which are that far off on the horizon.
