### ISSUE TITLE
Proposal: Algebraic data types

### ISSUE THREAD

**Issue by hydroper** [carbon-language/carbon-lang#2082]
I've been thinking of algebraic data types like the following:

```
algebraic enum Result {
  Winner{player:Player};
  Draw;
}
// this isn't type inference; Winner and Draw are available out of Result
let r:Result = Draw;
```

Which translates to:

```
abstract class Result {
}
class Winner extends Result {
  let player:Player;
}
class Draw extends Result;
```

Since it translates to subtypes, it could easily be reused by C++. I'm not sure this is idiomatic, just an idea. I couldn't find a similiar issue here.

**Comment by jonmeow** [comment]
This is equivalent to [choice types](https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#choice-types). Your examplr would be:

```
choice Result {
  Winner(player:Player),
  Draw,
}
```

Closing since I assume you overlooked `choice`, but feel free to follow up if I've misunderstood.

**Comment by hydroper** [comment]
@jonmeow Thanks, didn't see it was named like this.
