### ISSUE TITLE
Proposal: Include directive

### ISSUE THREAD

**Issue by hydroper** [carbon-language/carbon-lang#2083]
A directive for merging statements from another file. It could be valid in any context, even in, say, class blocks.

**c.carbon**

```
class C {
  include './c-further.carbon';
}
let c:C = {.x = 10};
```

**c-further.carbon**

```
let x:i64 = 0; // defines instance field 'x'
```

## Motivation

- This is useful for partially-implemented classes (instead of .NET-like `partial` classes you include files).
- This allows to mix Carbon with other languages, like XML documents, making script a part of another script. Say:

**my-control.xml**

```xml
<control>
  <script>
    fn Create() -> Me {
      return {.base = Control.Create()};
    }
  </script>
</control>
```

**Comment by matthew-russo** [comment]
I think this generally falls in to the metaprogramming category which hasn't been fully worked through.
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/metaprogramming.md

#89 laid out an initial draft with some ideas around the direction carbon may take but it was leaning away from arbitrary code generation with macros which I think your `include` directive is a specific example of. Not sure how set in stone "no macros" is or if there have been more recent discussions on the preferred approach for metaprogramming.

**Comment by hydroper** [comment]
> I think this generally falls in to the metaprogramming category which hasn't been fully worked through. https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/metaprogramming.md
> 
> #89 laid out an initial draft with some ideas around the direction carbon may take but it was leaning away from arbitrary code generation with macros which I think your `include` directive is a specific example of. Not sure how set in stone "no macros" is or if there have been more recent discussions on the preferred approach for metaprogramming.

My proposal diverges from C++'s `#include`. I don't think it has much to do with metaprogramming. In my language's parser this statement serves to contribute a statement sequence from another file to another statement sequence. When the verifier (aka. type checker or symbol solver) takes the statement sequence it should pass the same context to the included sequence.

For example, my TypeScript AST looks like this:

```typescript
export class IncludeStatement extends Statement {
    childScript: Script | null = null;
    childStatements: Statement[] = [];

    constructor(public src: string) {
        super();
    }
}
```

`IncludeStatement` is visited in all verifier phases. (I had done a verifier before.) Each child statement takes the same context.

**Comment by chandlerc** [comment]
> > I think this generally falls in to the metaprogramming category which hasn't been fully worked through. [https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/metaprogramming.md](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/metaprogramming.md?rgh-link-date=2022-08-21T18%3A49%3A46Z)
> > #89 laid out an initial draft with some ideas around the direction carbon may take but it was leaning away from arbitrary code generation with macros which I think your `include` directive is a specific example of. Not sure how set in stone "no macros" is or if there have been more recent discussions on the preferred approach for metaprogramming.
> 
> My proposal diverges from C++'s `#include`. I don't think it has much to do with metaprogramming. In my language's parser this statement serves to contribute a statement sequence from another file to another statement sequence. When the verifier (aka. type checker or symbol solver) takes the statement sequence it should pass the same context to the included sequence.
> 
> For example, my TypeScript AST looks like this:
> 
> ```ts
> export class IncludeStatement extends Statement {
>     childScript: Script | null = null;
>     childStatements: Statement[] = [];
> 
>     constructor(public src: string) {
>         super();
>     }
> }
> ```
> 
> `IncludeStatement` is visited in all verifier phases. (I had done a verifier before.) Each child statement takes the same context.

I think I understand what you're proposing, but I agree that this gets into metaprogramming and compile-time assembly of code from external files, just in this case other Carbon files.

While we can revisit that when we get to metaprogramming, I don't think we're going to dig back into that in the short term (it's not really part of our current roadmap / priorities) and I don't think reading other Carbon files is going to be where we start either. So probably right to leave this closed.
