### ISSUE TITLE
choice: don't require empty `()`

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2097]
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/README.md#choice-types has example code:

```
choice IntResult {
  Success(value: i32),
  Failure(error: String),
  Cancelled
}

...

  case .Cancelled => {
    Terminate();
  }
```

Right now, it would be `Cancelled()` with parentheses: https://carbon.compiler-explorer.com/z/3dnK4xP38

Probably the right choice here is to not require parentheses in the explorer, although that'll probably require some extra handling of choices so that the parentheses are only conditionally required.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
