### ISSUE TITLE
mandatory parentheses in choice type values and matching

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#2111]
The explorer implementation of choice types supports:

```carbon
choice X {
  A(i32),
  B(),
  C
}
```

Given that declaration, I would expect to be able to create corresponding values using `X.A(5)`, `X.B()`, and `X.C`, and pattern-match them using `X.A(n: i32)`, `X.B()`, and `X.C`. But in fact, in order to create and pattern-match `C` values, one uses `X.C()` instead.

This seems inconsistent to me. I would suggest that either we make the parentheses mandatory in `choice` declarations, or that we expect parentheses when creating and using choice values only if there were parentheses in the choice type declaration. I think having the simpler `X.C` syntax available is beneficial (eg, `.None` seems cleaner than `.None()` for an `Optional` type), so I'd suggest changing the interpretation of `X.C` so that it's a value of type `X` rather than a function that returns a value of type `X`.

**Comment by jonmeow** [comment]
Note also #2097

**Comment by zygoloid** [comment]
I don't think we need both issues, closing as a duplicate of #2097.
