### ISSUE TITLE
Explorer does not support current block string literal syntax

### ISSUE THREAD

**Issue by etalian** [carbon-language/carbon-lang#2121]
Block string literal syntax was recently changed (#1360), however Explorer does not accept the new syntax:
```
package ExplorerTest api;

fn Main() -> i32 {
  var block: String = '''
    This is a block string literal
    ''';
  return 0;
}
```
produces:
`COMPILATION ERROR: invalid character '\x27' in source file.`

**Comment by priyans-google** [comment]
I'll take a stab at this. I'm starting with `explorer/syntax/lexer.lpp`, splitting the `#*(\"\"\"|\")` case into two: one to handle single-line strings, and one to handle multi-line strings.

Note that when we support char literals, we'll have to further refactor this.

**Comment by priyans-google** [comment]
This should be resolved now.

**Comment by jonmeow** [comment]
Agreed, thanks!
