### ISSUE TITLE
Brew build error

### ISSUE THREAD

**Issue by 4lfg24** [carbon-language/carbon-lang#2136]
After running "bazel run //explorer -- ./explorer/testdata/print/format_only.carbon" in the terminal, I get this error, "fail("`llvm-ar` not found in PATH or adjacent to clang")" could someone please tell me how to fix it? Thank you in advance!

**Comment by yaa-ali** [comment]
Hi,
Install llvm [even in GNU/Linux] with brew and set the path  

``` 
brew install llvm
export PATH="$(brew --prefix llvm)/bin:${PATH}" 
```
**Install brew**
brew documentation[`brew.sh`](https://docs.brew.sh/Homebrew-on-Linux)

**_Troubleshooting build issues_**

> Many build issues result from the particular options clang and llvm have been built with, particularly when it comes to system-installed versions. This is why we recommend using [Homebrew's LLVM](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#clang-and-llvm).

**Comment by chandlerc** [comment]
I think the previous post already answered this, closing.
