### ISSUE TITLE
Need design updates for #2015 numeric type literal syntax

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#2159]
We need updates to docs/design corresponding to proposal #2015.

**Comment by Aniumbott** [comment]
I'm new here I would be glad to work on it but will need a little guidance if someone can join along or can have a mentor if possible. 🥺

**Comment by zygoloid** [comment]
Hi @Aniumbott, welcome to the Carbon project! I'm happy to provide some guidance here.

What we'd be looking for here is a pull request updating the `.md` files in `docs/design`:
- Read through all the current parts of the design that discuss integer and floating-point type literals, and change them as needed to ensure that they match #2015.
- Make sure that all design details mentioned in #2015 are reflected somewhere suitable in `docs/design`.
- Add references back to the proposal from the design, both in the "References" section and in the "Alternatives considered" section in each file. See [the design style guide](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/design_style_guide.md) for details.

Let me know if you have questions -- feel free to message me on discord.

**Comment by paulfryzel** [comment]
@Aniumbott As the author of #2015, also feel free to ping me on Discord (paulfryzel) for any additional context or clarification you may need. Best of luck starting out on it!

**Comment by cguiubg** [comment]
Hello I'm new to carbon and would love to contribute. It looks like some updates corresponding to #2015 are reflected in the docs from #1975. Is there any more work to be done on this issue I can help with?

**Comment by PramodhTVK** [comment]
Hello,I am very new to this language allthough I know a good amount of C++.I would love to contribute.Could you guys pls help me out?

**Comment by geoffromer** [comment]
@PramodhTVK It sounds like you're asking for help with contributing to Carbon in general, rather than this issue in particular? If so, please take a look at [CONTRIBUTING.md](https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md).

**Comment by avicorp** [comment]
> @Aniumbott As the author of #2015, also feel free to ping me on Discord (paulfryzel) for any additional context or clarification you may need. Best of luck starting out on it!

Hi, I started looking at the task and followed @zygoloid guidelines. I sow that #2015 mentioned at the reference section in two places and that the concept of iN, uN and fN introduced in the design.md. 

I edit the numeric_literal.md and add referanse where #2015 was mentioned. 

Can you assign me to the task and I will commit  the change.
