### ISSUE TITLE
Why is discord used for discussions?

### ISSUE THREAD

**Issue by rscircus** [carbon-language/carbon-lang#2165]
Seeing the reasoning behind discussing things away from GitHub, why Discord?

- it's a memory hog
- extracts personal data
- they seem to be bad at engineering on multiple levels:

![image](https://user-images.githubusercontent.com/1167114/189473836-6c2fa82a-ed13-4198-a3f4-67818e28783e.png)

Above happened during a business trip inside of Europe and I can not log in anymore as the verification by handing out my mobile number to them did not work. Neither did the 'identify the adult cat' captcha, nor seemed the automagically appearing 'verify by email' which seems to misunderstand what its own intention at all was.
I.e., I can't work on my issues in my spare time (!), while traveling at all and wonder if my account will be blocked when stopping to travel and stay at a place.

Quite a demotivating piece of software.

**Comment by chandlerc** [comment]
GitHub doesn't provide a real-time chat system. There are several of these, but while Discord does have problems, all the others we looked at had their own problems as well. On the balance, we had the most experience with and confidence in Discord. It isn't perfect, but it's the best we have.

That said, definitely reach out to Discord for assistance, and we can also look at whether there is anything we can do on our end.

**Comment by rscircus** [comment]
Thanks for the clarification @chandlerc - I'll leave this open during the weekend to leave some space for some opinions and close it then on Monday.

It annoyed me quite a bit today, as it is difficult to find time and I now have it due to a business trip and wanted to add the #pattern-matching discussion on Discord as mentioned by @josh11b in https://github.com/carbon-language/carbon-lang/issues/1758 and https://github.com/carbon-language/carbon-lang/pull/1388... and didn't expect such a blocker...

**Comment by Pandaa-P** [comment]
>extracts personal data

It's a big problem of discord, like to even chat in carbon server I need to complete a few more steps before I can start talking in this server. what these steps? `Verify your phone number.`. yep, outright data harvesting.

**Comment by ghost** [comment]
Discord is not secure. If you can't access your personal information on a trip to Europe, maybe the next question to bring up is about safety.

**Comment by rscircus** [comment]
Closing as @chandlerc mentioned a (undocumented?) discussion/selection (by the leads?) and they seemingly went for the lesser of all evils.

**Comment by jonmeow** [comment]
In the interest of openness, we turned on phone number verification because of unverified concerns about alt account creation being used for trolling on Discord, particularly in the wake of going public when mods were feeling overloaded. Phone number verification was a requirement we enabled in order to hinder alt account creation.

By comparison, on GitHub, there is no doubt we had an alt account attack. However, GitHub lacks similar controls. Instead, we escalated to GitHub support for assistance, which took a few hours to respond. Overall, GitHub was a greater burden on moderators.

It's disappointing to me that Discord implements their verification poorly. However, Discord excels at providing tools to help moderate and encourage positive and constructive communities, particularly with the ecosystem of bots surrounding it.

We're going to try turning Discord's phone number verification off; we've been waiting for the post-announcement attention to die down, and I'm back from a trip this week (timing related to this thread is coincidental). Even as we do that, community safety and the ability to respond to trolling will remain important, and we're going to keep looking into tools we will use the tools available to us in order to respond. Again, unlike GitHub, Discord provides more options here that we can take advantage of.

**Comment by rscircus** [comment]
Got back to Germany and it starts again... confirmed meanwhile 4 times to a machine (hcaptcha) that I ain't a machine. Jumped through a bunch of email activation hoops and now a new challenge came up:

![image](https://user-images.githubusercontent.com/1167114/191104636-a908d79f-5e51-4901-89f7-aeed5134e2e8.png)

@chandlerc @jonmeow - it can be that you (as Alphabet employees) get quick replies, however, the not so famously employed of us seem not to...

So, maybe you can send me a screenshot of the discussion @josh11b mentioned in https://github.com/carbon-language/carbon-lang/pull/1388#issue-1305059495 ? I'd really like to get https://github.com/carbon-language/carbon-lang/pull/1871 out of its draft state and also close https://github.com/carbon-language/carbon-lang/pull/1388 ...

**Comment by rscircus** [comment]
[proof](https://twitter.com/RsCircus/status/1568968609661358084) for asking Discord for help ... 

... on the positive side: at least I get some more sleep instead of some lovely nightly hours of thinking about formal languages. :sleeping: ... on the negative side, this is really demotivating. I mean honestly, instead of you guys I am not paid for this here. Further, I am not willing to spend my nights with debugging proprietary software. This above is already way too much off-topic....

**Comment by rscircus** [comment]
After a few last attempts with a browser Discord hasn't seen yet (Vivaldi):

![image](https://user-images.githubusercontent.com/1167114/191107512-43022d84-c6ae-499a-a864-c616854d0386.png)

This is soooo weird...

Env:

![image](https://user-images.githubusercontent.com/1167114/191107780-769958b1-8994-4cd2-b5ae-eb61881dd93e.png)

DevTools:

![image](https://user-images.githubusercontent.com/1167114/191108073-a3b3c831-c094-45cb-8e0c-aa8022ec78d5.png)

Sure. Some if it is uBlock... but come on... just as a comparison of another chat tool (Telegram) on the same machine and browser:

![image](https://user-images.githubusercontent.com/1167114/191108371-14c85ee3-12aa-40db-add3-686d049d7c25.png)

Pretty clean, ain't it?

**Comment by geoffromer** [comment]
I understand your frustration, but this has gotten off-topic.

I'm afraid we don't have any special relationship with Discord that we can leverage here; we're just using their service. If you're locked out of your account, you might need to contact Discord support directly, for example [here](https://support.discord.com/hc/en-us/requests/new). Alternatively, you might have more luck contacting them through Twitter if your tweet describes the specific problem you're experiencing.

In the meantime, it makes sense to look for workarounds like asking @josh11b to give you more information about the discussion he cited in his comment, but that belongs in a reply to his comment, not here.

The question that this issue originally asked has been answered, so I'm closing it.

Please note that personal attacks like "they seem to be bad at engineering" are not permitted by our [code of conduct](https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md).

**Comment by rscircus** [comment]
@geoffromer - hm, thanks for the feedback that some understand 'they seem to be bad at engineering' as a personal attack. To me it is more on the level of expressing an opinion about a product than that.

**Comment by ghost** [comment]
> @geoffromer - hm, thanks for the feedback that some understand 'they seem to be bad at engineering' as a personal attack. To me it is more on the level of expressing an opinion about a product than that.

Because we are on the topic of international travel, I want to share that there is a terms of service from a mobile app I downloaded from a China company; and in this terms of service, they highly recommend to be careful about commenting negatively concerning both their company and other people within the app.

The relevance is that there may be an increase sense of safety when we are using international apps, and we use more sensitivity in addressing topics with a more positive light.

This is a code of conduct skill that I also am learning how to improve in myself.

**Comment by rscircus** [comment]
In light of the current Twitter breach and Discord collecting phone numbers aggressively, can we talk about this again?

See: https://news.ycombinator.com/item?id=34126428

**Comment by rscircus** [comment]
In light of the current Twitter breach and Discord collecting phone numbers aggressively, can we talk about this again, @geoffromer, @chandlerc, @jonmeow, & @josh11b ?

See: https://news.ycombinator.com/item?id=34126428

**Comment by chandlerc** [comment]
> In light of the current Twitter breach and Discord collecting phone numbers aggressively, can we talk about this again, @geoffromer, @chandlerc, @jonmeow, & @josh11b ?
> 
> See: [news.ycombinator.com/item?id=34126428](https://news.ycombinator.com/item?id=34126428)

We turned off requiring phone number verification for our server because of the limitations this causes.

**Comment by rscircus** [comment]
Why does it want a phone number then¿

see https://github.com/carbon-language/carbon-lang/issues/2165#issuecomment-1251483594

**Comment by geoffromer** [comment]
> Why does it want a phone number then¿
> 
> see https://github.com/carbon-language/carbon-lang/issues/2165#issuecomment-1251483594

That comment is from three months ago. Are you still having this problem now?

**Comment by rscircus** [comment]
@geoffromer - thanks for letting me know. This policy change passed me and solved all the issues above. Just created a new user on your server and am taking up my work on #1758 again.
