### ISSUE TITLE
one-tuples and one-tuple syntax

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#2191]
We have a longstanding [open question](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/tuples.md#single-value-tuples) on tuple syntax: can you write a one-tuple, and if so, how? (See also #2038 for some recent discussion).

Possibilities:

0) Carbon has no 1-tuples (like Haskell, Swift, Scala). `(a)` is the same as `a` and in simple cases can be used as if it were a 1-tuple.
1) Allow specifically `(` _expression_ `,` `)` for this. Do not allow a trailing comma in any other cases (previously discussed but seems unprecedented in other languages).
2) Allow a trailing comma in tuple syntax for non-empty tuples, that is mandatory when constructing a 1-tuple but otherwise optional; don't allow trailing commas in other parenthesized lists like function calls (like Chapel).
3) Allow a trailing comma in all non-empty parenthesized comma-separated lists; it is mandatory when the parentheses could otherwise be interpreted as grouping parens (like Python, Rust, Julia).
4) Some blurring of the line between values and 1-tuples, so we have both but they're usually interchangeable.
5) Change tuple syntax entirely to avoid the problem, such as using `(@, first_elem, second_elem)` (suggested by @tkoeppe on #2038).

**Comment by zygoloid** [comment]
I think that we need 1-tuples for generic code, if nothing else. The case of exactly one result should be expected to be common, and treating it as some kind of special case seems especially problematic. Note that `GetFirstElement(MakeTuple(a, b...))` would misbehave under option 0, particularly if `b` is empty and `a` is itself a tuple. I think option 0 is a bad fit given our goals for generic programming.

Of the remaining options, 4 and 5 seem too inventive, and 4 seems likely to lead to confusion. Option 3 is the most consistent choice, has plenty of precedent, and doesn't seem to solicit complaints -- in fact, while researching this I found a lot of user sentiment for Swift to switch from option 0 to option 3.

So I propose we select option 3, at least for now. This seems like a relatively easy syntactic decision to revisit later, unless the decision is to switch to option 0, but as noted I think that's a poor fit for Carbon and will remain so.

**Comment by josh11b** [comment]
I'd just like to express that allowing a trailing comma has been used to make it easier to edit lists and to make diffs smaller in source control when making changes. See, for example, https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas

**Comment by zygoloid** [comment]
Leads decision: we select option 3. Non-empty parenthesized comma-separated lists can have a trailing comma, which is mandatory when the parentheses would otherwise be interpreted as grouping parens and is otherwise optional.
