### ISSUE TITLE
Style code change

### ISSUE THREAD

**Issue by holu31** [carbon-language/carbon-lang#2218]
I propose to replace PascalCase with snake_case

**Comment by jonmeow** [comment]
Casing was most recently considered in more length on #1435. It may be helpful to start at the end (e.g., [zygoloid's response](https://github.com/carbon-language/carbon-lang/issues/1435#issuecomment-1201751831)) if you're trying to understand the rationale. Note that this might be reconsidered in the future, but at present the leads are making a decision based on the information that's available.

Given this issue isn't offering new information, I'm closing it.
