### ISSUE TITLE
Possible code typo in Carbon FAQ

### ISSUE THREAD

**Issue by KZiemian** [carbon-language/carbon-lang#2228]
In FAQ [Why do variable declarations have to start with var or let?](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#why-do-variable-declarations-have-to-start-with-var-or-let) we have code
```
var ((x: i32, _: i32), y: auto) = ((1, 2), (3, 4));
```
All fine here. But in the line below we read "This code is valid, and initializes `x` to `1` and `z` to `(3, 4)`.". In my humble opinion it should say that `y` is initialized to `(3,4)`.

I made this issue not PR, since someone more knowledable should judge is this really typo, or some magic. And you shouldn't waste PR for such trivial thing.

**Comment by jonmeow** [comment]
Thanks, #2230 

FWIW feel free to use PRs for things like this, they're low cost.
