### ISSUE TITLE
Arrays with single object entry result in error

### ISSUE THREAD

**Issue by felix-seifert** [carbon-language/carbon-lang#2317]
### Description of the bug:

An array which includes a single object can somehow not be created. If I try to create the same array with two or more objects, everything seems to work fine.

### What did you do, or what's a simple way to reproduce the bug?

```
package ExplorerTest api;

class Car {
  var type: String;
  var maxSpeed: i32;
}

fn Main() -> i32 {

  var car1: Car = {.type = "Ford", .maxSpeed = Car.GetIntRandomRange(180, 200)};
  var carArray: [Car; 1] = (car1);

  return 0;
}
```

### What did you expect to happen?

```
result: 0
```

### What actually happened?

```
COMPILATION ERROR: ../carbon-hack/main.carbon:11: type error in name binding: 'class Car' is not implicitly convertible to '[class Car; 1]'
```

**Comment by jonmeow** [comment]
Single-value tuples need to be distinguished using a suffix comma, similar to Python. (this is the plan [noted here](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/tuples.md#single-value-tuples))
https://carbon.compiler-explorer.com/z/zdaGcsEEq
