### ISSUE TITLE
MultiLine Strings doesnt work , Throwing Syntax Errors

### ISSUE THREAD

**Issue by akashakash24** [carbon-language/carbon-lang#2338]
### Description of the bug:

I'm Trying to create a multi line string. The compiler throws errors while creating a multi lined string

### What did you do, or what's a simple way to reproduce the bug?

https://carbon.godbolt.org/z/G5rsharva

package ExplorerTest api;

fn Main() -> i32 {
  var singleLine: String = "Hello world!";
  var multiLine: String = """ hello line 1
            hello line 2
            hello line 3
        """; 
  return 0;
}

<Compilation failed>

# For more information see the output window

SYNTAX ERROR: <source>:5: Invalid block string: Invalid characters in file type indicator:  hello line 1
Compiler returned: 1

### What did you expect to happen?

Multi Line Strings

### What actually happened?

Compiler error

### Any other information, logs, or outputs that you want to share?

![image](https://user-images.githubusercontent.com/31944412/197470559-b3dddabd-c5e4-4844-ac7d-e011c3856dcc.png)

**Comment by jonmeow** [comment]
The first line is a file type indicator, similar to markdown. It's failing because of the whitespace. If you remove the whitespace (e.g., `"""helloline1`) it'll work.

Glancing at the design, the error is correct:

> A file type indicator is any sequence of non-whitespace characters other than ' or #. The file type indicator has no semantic meaning to the Carbon compiler, but some file type indicators are understood by the language tooling (for example, syntax highlighter, code formatter) as indicating the structure of the string literal's content.

https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/lexical_conventions/string_literals.md#simple-and-block-string-literals
