### ISSUE TITLE
Herb Sutter

### ISSUE THREAD

**Issue by magom001** [carbon-language/carbon-lang#2419]
### Summary of issue:

https://www.youtube.com/watch?v=ELeZAKCN4tY

**Comment by geoffromer** [comment]
The Carbon issue tracker is for tracking specific, actionable issues with the design and implementation of Carbon. We have a [Discord server](https://github.com/carbon-language/carbon-lang/discussions) and a [GitHub Discussions](https://github.com/carbon-language/carbon-lang/discussions) forum for more open-ended discussions (although they should still be focused on the design and implementation of Carbon).
