### ISSUE TITLE
Explorer: Support `abstract` virtual methods

### ISSUE THREAD

**Issue by Pixep** [carbon-language/carbon-lang#2512]
### Background

The Carbon explorer currently supports `virtual` and `impl` prefixed virtual method, but not `abstract` methods (i.e. pure virtual methods in C++).

### Goal

Support `abstract` method, as described in the [class design doc](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/classes.md#virtual-override-keywords). This includes:
* Checking that the method has no implementation (`CallableDeclaration::body()`)
* Checking that child classes do implement the method

### Starting point

A recommended approach would be to modify the switch/case logic for virtual methods declaration in `explorer/interpreter/type_checker.cpp` (in the `TypeChecker::DeclareClassDeclaration` function, `VirtualOverride::Abstract` case) to remove the current error logged when `abstract` is used, and check if the method has no body first.

This can be tested by creating a running a new lit test under `explorer/testdata/class`, and run using `bazel run //explorer/testdata:class/<my_abstract_method_test.carbon>.run`.

Example of tests:

Error case 1
```
base class A {
  // Error, abstract method cannot have a body (note the curly braces)
  abstract fn Foo[self: Self]() {}
}
```

Valid case
```
abstract class A {
  // OK, no implementation
  abstract fn Foo[self: Self]();
}

class B extends A {
  // OK, implemented in child class
  fn Foo[self: Self]() {}
}
```

### Resources

* https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md
* https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md
* `#contributing-help` channel on the Discord

**Comment by aphsai** [comment]
hi, could I take a crack at this?

**Comment by Pixep** [comment]
> hi, could I take a crack at this?

Welcome @aphsai ! We have another person on the [Discord](https://discord.gg/ZjVdShJDAs) who started working on it yesterday (I will ask them to add a little note here to be assigned).
Feel free to join us there, and I will start thinking of another other `good first issue` as well.

**Comment by aphsai** [comment]
Thanks for the quick reply, happy to help if they need it.

**Comment by n3r0bi0m4n** [comment]
@Pixep here I am

**Comment by CODER2810** [comment]
HELLO I CAN RESOLVE THIS ISSUE KINDLY LET ME WORK IN THIS PROJECT

**Comment by ashutosh887** [comment]
HI @Pixep  I would like to wrap this issue
Please assign it to me

**Comment by Pixep** [comment]
Thanks for the enthusiasm, let's first see if @n3r0bi0m4n can finish it :)
@n3r0bi0m4n is it something you are still working on?

**Comment by CODER2810** [comment]
no i am not working on anything for now ....

**Comment by ashutosh887** [comment]
I'm next in the queue @Pixep @CODER2810 😄

**Comment by CODER2810** [comment]
ok bro all d best

**Comment by Pixep** [comment]
Hid a few comments, to make sure we stay on topic. We may open the issue to be re-assigned in the future, but for now someone already is.

**Comment by shreya024** [comment]
> Hid a few comments, to make sure we stay on topic. We may open the issue to be re-assigned in the future, but for now someone already is.

Hi @Pixep I would like to work on this issue if it is open

**Comment by Pixep** [comment]
Hey everyone, `good first issue`s don't need to be assigned anymore (see https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#implement-carbons-design for some explanation), feel free to work on it if you wish!

**Comment by AbdullahGhulamNabi** [comment]
I'm eager to contribute to the effort to resolve the pure virtual function error problem as a student and to do so in order to improve the community while learning essential software development skills. Can I have a chance to work upon?

**Comment by himanshusingh0905** [comment]
@Pixep There is no method that can tell if a method has a body or not.

**Comment by Pixep** [comment]
> @Pixep There is no method that can tell if a method has a body or not.

During type checking, you can use `fun->body().has_value()`. You can see it in the reference work that was done on the same issue for an example here: https://github.com/carbon-language/carbon-lang/pull/2528.

@shreya024 , @AbdullahGhulamNabi , @himanshusingh0905 the issue is open for anyone to work on it, without being assigned :)

**Comment by Jayantbhoj** [comment]
is it still open can i contribute?

**Comment by AbdullahGhulamNabi** [comment]
Thanks for mentioning me. I am glad you responded.
Can you elaborate the the problem and how can I contribute to it as I only
have prior knowledge of C++ and never contributed to open source before.
So, it would be really helpful of you could a glimpse of how can I can deep
dive into it. Waiting for your reply.

**Comment by Ceri555** [comment]
hey im new to open source was trying to resolve this issue can you help me on how to check that child classes do implement the method

**Comment by rishitha1238** [comment]
Hi Pixep, I would like to work on this if it's open
