### ISSUE TITLE
Explorer: Support `virtual destructor`s

### ISSUE THREAD

**Issue by Pixep** [carbon-language/carbon-lang#2521]
Support virtual destructors for Explorer, as described in https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/classes.md#destructors.

### Scope

This involves:
* Updating the allocation and deallocation logic to proper creation/destruction of classes created with `New`
    * Currently `var pa: A* = heap.New(A.Create())` creates a destroys a temporary `A`, assigns its address to `pa`, and destroys it immediately. We either need to extend its lifetime or alternatively copy `A` before it is destroyed.
    * See example below
* Modifying the grammar to support `virtual destructor`
* Preventing `Delete` on classes without virtual destructors, when appropriate
* Destroy the entire class hierarchy when calling `Delete` with a base class pointer

### Allocation issue

```carbon
package ExplorerTest api;

class A {
  fn Create() -> A {
    Print("CONSTRUCTOR A");
    return {};
  }
  destructor[self: Self] {
    Print("DESTRUCTOR A");
  }
}

fn Main() -> i32 {
  Print("Before New A");
  var pa: A* = heap.New(A.Create());
  Print("Before Delete A");
  heap.Delete(pa);
  return 0;
}
```

This example prints:

> Before New A
> CONSTRUCTOR A
> DESTRUCTOR A
> Before Delete A

The only reason why the program doesn't crash, is before `Delete` invokes `::Dealloc` which doesn't check if the value is alive, only if the allocation is, and proceeds to set the allocation to `Dead` without calling the destructor.

**Comment by rajeck1234** [comment]
@Pixep can i try this one

**Comment by Pixep** [comment]
> @Pixep can i try this one

You can give it a shot if you want, but I don't think this is an easy starting point, as this is a long-term issue requiring a few changes (including #2545), and I have a WIP branch there: https://github.com/Pixep/carbon-lang/pull/4.

That gave me the opportunity to brush up that work a bit.
