### ISSUE TITLE
Move `CallableDeclaration::name()` to `FunctionDeclaration`

### ISSUE THREAD

**Issue by Pixep** [carbon-language/carbon-lang#2531]
This issue is based on a TODO from the `CallableDeclaration` class declaration.
It would be preferred to move the `name()` method and attribute to `FunctionDeclaration` instead of the current class it lives in.

### Goal

* Move `name()` and attribute from `CallableDeclaration` to `FunctionDeclaration`
* Update codebase to ensure identical behavior and all tests pass.

Excerpt:
https://github.com/carbon-language/carbon-lang/blob/4daaa4866f8f12ab00e7ba053182761b1e762cfd/explorer/ast/declaration.h#L151-L152

**Note**: The `DestructorDeclaration` class is currently setting this field to `"destructor"`, and the code currently calling `name()` will need to behave the same.

### Resources

* https://github.com/carbon-language/carbon-lang#getting-started
    * And the `#contributing-help` Discord channel

**Comment by max-muoto** [comment]
Would be happy to take this one!

**Comment by Pixep** [comment]
> Would be happy to take this one!

You got it, thank you for the help!
