### ISSUE TITLE
Discord link 

### ISSUE THREAD

**Issue by nitin-787** [carbon-language/carbon-lang#2564]
### Description of the bug:

discord link is not working : https://discord.com/invite/ZjVdShJDAs

### Link to documentation:

https://github.com/carbon-language/carbon-lang#readme

### What should it say instead?

It should accept invite.

**Comment by chandlerc** [comment]
The link seems to still work, but it *is* an invite. You have to choose to accept it to join the server.

There isn't, to my knowledge, a different kind of Discord link that we can post at this time.

So I think this is working to the best extent it can. If you or others who are more familiar with Discord have a suggestion for something more effective than an invite link though, let us know and re-open the issue.

**Comment by stharlinjoel27-tech** [comment]
https://discord.gg/J2M2ECcanN

**Comment by danakj** [comment]
This link goes to a different Discord server.
