### ISSUE TITLE
Explorer: error on bit-shift overflow

### ISSUE THREAD

**Issue by Pixep** [carbon-language/carbon-lang#2595]
### Background

From the design documentation for [bitwise operations](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/bitwise.md#integer-types)

> The second operand of a bit-shift is required to be between zero (inclusive) and the bit-width of the first operand (exclusive); it is a programming error if the second operand is not within that range.

### Goal

Check the value of the second operand at runtime, for both left and right bit-shift operators, to match the design specification.

### Suggested approach

Bit-shift operators are implemented in the snippet below.

https://github.com/carbon-language/carbon-lang/blob/b2c60b4f53fa7a3a296ce91efeb6cbe4d3d84b70/explorer/interpreter/interpreter.cpp#L1590-L1603

This could be achieved by
 
* Checking the value of the second operand at that location
* Returning a `ProgramError` if the check fails
* Adding new `fail_` lit tests to cover the different use cases in `https://github.com/carbon-language/carbon-lang/tree/trunk/explorer/testdata/operators`

### Resources

* [bitwise operations](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/bitwise.md#integer-types) design documentation
* https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md
* https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md
* `#contributing-help` channel on the Discord

**Comment by AmrDeveloper** [comment]
I will be happy to work on this

**Comment by Pixep** [comment]
Welcome @AmrDeveloper , sure thing! Feel free to reach out on Discord if you have questions, and thank you.

**Comment by jonmeow** [comment]
Fixed by #2600

**Comment by jonmeow** [comment]
Thank you for the contribution!
