### ISSUE TITLE
Remove the need for semicolons

### ISSUE THREAD

**Issue by ermin247** [carbon-language/carbon-lang#2655]
### Summary of issue:

Make semicolons optional bc modern devs dont really like them and its a hassle to deal with when you have a large codebase and you spend hours trying to fix a bug thats caused by one missing semicolon
Its draining

**Comment by aviRon012** [comment]
This would be unfamiliar to C++ developers,
this might go against carbons goals of having a simple grammar that is easy to parse and tool.

one place where I think semicolons are unnecessary, is after class declarations, I always forget to put semicolons there, and it seems unintuitive to put semicolons after a curly brace. 

[this video](https://www.youtube.com/watch?v=c_cdmmTmS1U) is an interesting comparison of the usage of semicolons between different languages.

**Comment by AmayX** [comment]
To be honest, a C++ dev might prefer the semicolon as a line-ender than some other delimiter like a whitespace

**Comment by jonmeow** [comment]
While we understand semicolons aren't everyone's favorite feature, the leads have already discussed this and decided towards semicolons. Please see: https://github.com/carbon-language/carbon-lang/issues/1924

Technical notes:
- https://github.com/carbon-language/carbon-lang/issues/1924#issuecomment-1207586109 is the actual lead decision.
- https://github.com/carbon-language/carbon-lang/issues/1924#issuecomment-1206591526 quotes the rationale on-thread.

Carbon's evolution policy is to reevaluate old decisions when there's new evidence available which might change that decision. I don't think we have new evidence to evaluate, so I'm closing this issue as a duplicate.
