### ISSUE TITLE
Fuzzer issue around `interface Invalid {}`

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2729]
### Description of the bug:

The indicated code almost works but hits UndefinedBehaviorSanitizer, maybe because of `interface Invalid {}`

### What did you do, or what's a simple way to reproduce the bug?

```
package EmptyIdentifier impl;

interface Invalid {
}

fn Main() -> i32 {
  return 0;
}
```

### What did you expect to happen?

Nothing there looks bad to me, actually. An empty interface is fine.

### What actually happened?

```
optional:321:22: runtime error: load of value 2, which is not a valid value for type 'bool'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior optional:321:22 in
```

### Any other information, logs, or outputs that you want to share?

Case 274900545 for those with access to the current fuzzer reporting.

**Comment by jonmeow** [comment]
Use `bazel run -c dbg //explorer` to get a better stack trace for tracking this down. Marking as a good first issue.

**Comment by catranoverme** [comment]
it doesnt prompt any error on my end tho?
