### ISSUE TITLE
Fuzzer issue around divide-by-zero

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2731]
### Description of the bug:

Divide-by-zero causes undefined behavior.

### What did you do, or what's a simple way to reproduce the bug?

```
package EmptyIdentifier impl;

fn Main() -> i32 {
  return 1 / 0;
}
```

### What did you expect to happen?

Should probably fail with a runtime error, preventing the divide-by-zero from actually running.

### What actually happened?

interpreter.cpp:222:69: runtime error: division by zero
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior interpreter.cpp:222:69 in

### Any other information, logs, or outputs that you want to share?

Case 269347757 for those with access to the current fuzzer reporting.

**Comment by jonmeow** [comment]
Note the `%` implementation probably shares this issue.

**Comment by AmrDeveloper** [comment]
I will be happy to work on this

**Comment by AmrDeveloper** [comment]
We can close this issue now :D
