### ISSUE TITLE
Fuzzer issue around Print arguments

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2734]
### Description of the bug:

Print uses llvm::formatv, which can crash on invalid inputs.

Note, one way of fixing this might be to write custom input string validation that limits content, producing a compilation error instead of a crash.

### What did you do, or what's a simple way to reproduce the bug?

```
package EmptyIdentifier impl;

fn Main() -> i32 {
  Print("{1 1}");
  return 0;
}
```

### What did you expect to happen?

Should error on the format string

### What actually happened?

Crashes

### Any other information, logs, or outputs that you want to share?

Case 269349669 for those with access to the current fuzzer reporting.

**Comment by Rishabh9955** [comment]
Hello sir,
Myself Rishabh Kumar Singh from Tamil Nadu, India. Currently in Third year of my IT degree at Excel Engineering College.
I have experience in Dsa basic and C++ Basic to Advance .
I have also done coding on Leetcode and Coding ninjas.
I would like to do this Project and work under guidance of great mentor.
It would be great opportunity for me to learn from expert developers and dive deep in open source to explore great organizations like Drupal.org.

Currently I am exploring and working on issue to learn more about codebase Fuzzer issue around infinite recursion.
Please reach out to me -
email - rs6322398@gmail.com
LinkedIn-
Github

Thank you 😊
