### ISSUE TITLE
Tuple with `auto` doesn't validate length

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2777]
### Description of the bug:

Looks like when `auto` is in a type tuple, the tuple size isn't correctly validated by type checking. Note that if `auto` is replaced by `i32` in the below code, it gets a reasonable error instead of crashing.

### What did you do, or what's a simple way to reproduce the bug?

```
package ExplorerTest api;

fn Main() -> i32
{
  var a: (auto,) = (1, 2);
  return 0;
}
```

### What did you expect to happen?

Should be a compile error

### What actually happened?

```
CHECK failure at explorer/interpreter/interpreter.cpp:331: p_tup.elements().size() == v_tup.elements().size()
```

### Any other information, logs, or outputs that you want to share?

This was found by running the fuzzer by hand.

**Comment by jonmeow** [comment]
Just to note, `var a: (auto,) = 1;` should also be tested as part of fixing. It crashes on a different path, but it's likely a fix will handle both cases.

**Comment by maan2003** [comment]
I am investigating this now.

Update: both CARBON_CHECKs need to be converted to an error message.
