### ISSUE TITLE
Prevent generic bindings in types

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2783]
### Description of the bug:

According to explorer:
1) `var x: (T: type);` -- "the type of a binding pattern cannot contain bindings"
2) `var x: (T:! type);` -- valid
3) `var x: (T:! type) = 0;` -- "type error in initializer of variable: 'i32' is not implicitly convertible to 'T'"

Per [#syntax discussion](https://discord.com/channels/655572317891461132/709488742942900284/1098318068725334066) we'll disallow (2), with the rule that types cannot contain binding patterns. Note that making this an error will also change (3).

### What did you do, or what's a simple way to reproduce the bug?

```
fn Main() {
  var x: (T:! type);
  return 0;
}
```

There's probably also a related scenario for:

```
fn Foo(x: (T:! type)) {}
```

### What did you expect to happen?

Should be a compile error

### What actually happened?

Code compiles

### Any other information, logs, or outputs that you want to share?

Should probably wait on #2782 and adjust the logic there (I'm thinking bool require_binding to an enum Bindings // Required, Disallowed, Mixable), also replacing the VisitPatterns call that does the current "the type of a binding pattern cannot contain bindings"

**Comment by geoffromer** [comment]
As noted in the linked #syntax discussion, I think it might make more sense to solve this by treating the right-hand side of a binding as an expression rather than a pattern.
