### ISSUE TITLE
Reimplement AutoPattern as an expression

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2788]
Per discussion around #2783 and [on #syntax](https://discord.com/channels/655572317891461132/709488742942900284/1098318068725334066), there's a long-term desire to migrate AutoPattern away from being a pattern, and instead have it be an expression.

This had come up because the rhs of a binding is typically a type (`x: type`), which is the main use-case for `auto` in a pattern, because `type` there is current a pattern.

Steps probably include:

- Moving `auto` parsing from pattern to expression syntax.
- Migrating `auto` type deduction.
- Detecting `auto` outside of binding patterns and erroring (currently rejected by bison syntax).
- Switching the type of a binding to an expression.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
