### ISSUE TITLE
Alias resolved_declaration error

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2794]
### Description of the bug:

Looks like the set_resolved_declaration code from #2720 has a crash. I was looking at this for #2792, seeing if there were edge cases to handle.

FYI @Maan2003 

### What did you do, or what's a simple way to reproduce the bug?

```
package ExplorerTest api;

class A {
  class B {}
  alias C = B;
}

fn Main() -> i32 {
  return 0;
}
```

### What did you expect to happen?

Error or nothing (i.e., successful compile).

### What actually happened?

```
CHECK failure at ./explorer/ast/declaration.h:1022: !resolved_declaration_.has_value()
```

**Comment by maan2003** [comment]
I am investigating this. guess: this happens due to multiple phases of name resolution.
