### ISSUE TITLE
Support aliasing an interface method as a class member

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2798]
### Description of the bug:

This is the feature version of #2583 (now that the crash is fixed), to support aliasing an interface method as a class member.

### What did you do, or what's a simple way to reproduce the bug?

```
package sample api;

interface Printable {
  fn PrintIt[self: Self]();
}

impl String as Printable {
  fn PrintIt[self: String]() {
    Print(self);
  }
}

class Vector(T:! type) {
  var x: T;

  alias PrintIt = Printable.PrintIt;
}

// Conditionally implement the API for certain `T`s.
impl forall [U:! Printable] Vector(U) as Printable {
  fn PrintIt[self: Self]() {
    Print("{{");
    self.x.PrintIt();
    Print("}");
  }
}

fn Main() -> i32 {
  var v: Vector(String) = {.x = "test"};
  v.(Printable.PrintIt)();
  v.PrintIt();
  return 42;
}
```

### What did you expect to happen?

That the alias makes using the member name equivalent to using a *qualified* member name in a call. Basically, lines 30 and 31 should be equivalent:

```
  v.(Printable.PrintIt)();
  v.PrintIt();
```

### What actually happened?

Currently unsupported.

**Comment by redbopo** [comment]
I think this is a small fix, the former will cause runtime format error.

>     Print("{");
->
>     Print("{{");

**Comment by jonmeow** [comment]
@redbopo Thanks, fixed the example. That's the result of a separate bugfix I recently put in. :)

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
