### ISSUE TITLE
gen_rtti.py not found but mentioned in "explorer/ast/ast_node.h"

### ISSUE THREAD

**Issue by sembooooo** [carbon-language/carbon-lang#2808]
### Description of the bug:

Hi community,
Good morning!
I was going through `ast_node.h`  and found out that the `gen_rtti.py` mentioned in the comments is not present.
When i googled for it, i found a previous PR which has `gen_rtti.py`  under `explorer/fuzzing/` but when i looked into the latest carbon_lang repo `explorer/fuzzing` i found a `.py` file with the name `regen_corpus.py`. 
So is this a comment section some how missed when the file was renamed ? 
or did not i looked properly for the file ?
I have also looked for other files that contains this name and it looks like `ast_node.h` is the only file with this name

### Link to documentation:

file in which i observed the above mentioned part.
https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/ast/ast_node.h

**Comment by sembooooo** [comment]
Found the issue https://github.com/carbon-language/carbon-lang/pull/2703/files where the file is deleted.

**Comment by jonmeow** [comment]
Thanks, https://github.com/carbon-language/carbon-lang/pull/2810 fixes this.
