### ISSUE TITLE
Fix uninitialized array access/initialization

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#2812]
### Description of the bug:

Trying to assign an uninitialized array value crashes.

Reported by Dr. J [on Discord](https://discord.com/channels/655572317891461132/1051906612375326862/1103442098818121808).

### What did you do, or what's a simple way to reproduce the bug?

```
package sample api;

fn Main() -> i32 {
    var my_array : [i32; 1];
    my_array[0] = 100;
    Print("{0}", my_array[0]);
    return 0;
}
```

### What did you expect to happen?

Prints 100

### What actually happened?

```
FATAL failure at explorer/ast/value.cpp:334: field access not allowed for value Uninit<Placeholder<my_array>>
```

It looks like the `my_array[0] = ...` is treated as uninitialized access. Instead, the array should be treated as "initialized" with uninitialized entries, since it has a designated size.

Either way, it shouldn't crash.

**Comment by profjpbaugh** [comment]
Dr. J = me.  Thanks for filing this, and for the information!  :)
