### ISSUE TITLE
The block string literal design would benefit from more dedicated examples around newlines

### ISSUE THREAD

**Issue by chandlerc** [carbon-language/carbon-lang#2887]
### Description of the bug:

Currently, we have a reasonably generic strategy for handling newlines in block string literals:
- The literal only starts on the line after the opening triple-quote (so there is no leading newline)
- Any newline in the literal's source can be skipped from its content by ending the line with a `\`.
- By default, the last line has a trailing newline, and all block literals have trailing newlines
- But this can be suppressed using the general newline suppression:
  ```carbon
  var s: String = '''
      one newline here:
      but none here:\
      ''';
  ```

However, the inclusion of the trailing newline by default and using the general escape technique to remove it has surprised at least one group when reading the design, so we should add some dedicated examples that showcase these different aspects.

### Link to documentation:

https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/lexical_conventions/string_literals.md

**Comment by jonmeow** [comment]
What are you looking for that's different from the following examples?

```
// This string contains no newline characters.
var String: type_mismatch = '''
  Shall I compare thee to a summer's day? Thou art \
  more lovely and more temperate.\
  ''';

var String: trailing_whitespace = '''
  This line ends in a space followed by a newline. \n\
      This line starts with four spaces.
  ''';
```

[edit: also]

```
var String: w = '''
  This is a string literal. Its first character is 'T' and its last character is
  a newline character. It contains another newline between 'is' and 'a'.
  ''';
```

**Comment by chandlerc** [comment]
> What are you looking for that's different from the following examples?

Ones that more explicitly focus on trailing newlines. The first one wasn't enough for several folks reading the design to recognize the goal of the pattern.
