### ISSUE TITLE
Exponential run time with deeply nested tuple type

### ISSUE THREAD

**Issue by geoffromer** [carbon-language/carbon-lang#2951]
### Description of the bug:

Given the following input:

```
package EmptyIdentifier impl;

var EmptyIdentifier: ((((((((((((((((type, ), ), ), ), ), ), ), ), ), ), ), ), ), ), ), ) = (EmptyIdentifier, );
fn Main() -> i32 { return 0; }
```

the Explorer takes 80 seconds (and several gigabytes of memory) to run on my machine, which seems excessive. That's with 16 pairs of parentheses in the type of `EmptyIdentifier`. Removing parentheses reveals a very clear exponential relationship: 15 parentheses takes 40 seconds, 14 parentheses takes 20 seconds, etc.

Curiously, with more than 16 parentheses the running time seems to be roughly constant at 100-105 seconds. The observable behavior changes as well: with 16 parentheses the output is:

```
RUNTIME ERROR: test16.carbon:4: could not find `EmptyIdentifier: ((((((((((((((((type))))))))))))))))`
```

But with 17 parentheses the output is:

```
COMPILATION ERROR: test17.carbon:4: type error in implicit conversion: '(((((((((((((((((type,),),),),),),),),),),),),),),),),)' is not implicitly convertible to '((((((((((((((((type,),),),),),),),),),),),),),),),)'
```

However, that may be a separate issue.

**Comment by jonmeow** [comment]
FWIW it might be related to MaxExponentialDepth (8, so 16 is 2x) in pattern analysis.

**Comment by geoffromer** [comment]
Note: the above timing data is in the default build mode; with `-c opt` the run times are roughly 20x better, but exhibit the same patterns.

> FWIW it might be related to MaxExponentialDepth (8, so 16 is 2x) in pattern analysis.

That would explain a lot, but when I change that constant to 7, the transition in behavior still happens between 16 and 17.

**Comment by jonmeow** [comment]
The transition in behavior happens due to MaxTodoSize: the overflow error is converted to an implicit conversion failure because https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/interpreter/type_checker.cpp#L1064 doesn't propagate the original error message (which, may be the right choice -- we don't have error codes, and the overflow cause is a little opaque)

**Comment by geoffromer** [comment]
Status update: I've narrowed this down to an issue with template instantiation: a template related to the tuple type is getting instantiated twice, and each instantiation transitively requires instantiating the same template for the tuple's elements. This means that the number of instantiations grows exponentially as we add layers of nesting to the tuple.

I'm planning to fix this by adding a memo table of template instantiations, so that each instantiation happens at most once. It might be possible to avoid instantiating the template twice by construction, but I'm not currently planning to pursue that, because I don't know how much more time that would take, and it would lead to a much narrower and less robust fix. I'm going to be on vacation until July 17th, but I'll pick this up on my return unless someone else gets to it first.
