### ISSUE TITLE
Fuzzer found issue: crash on namespace in a base type specifier

### ISSUE THREAD

**Issue by chandlerc** [carbon-language/carbon-lang#2980]
### Description of the bug:

Currently, the explorer crashes when a namespace is in the base type of a class.

### What did you do, or what's a simple way to reproduce the bug?

The test case is something like:

```carbon
// Generated by proto_to_carbon.
package EmptyIdentifier impl;

class EmptyIdentifier{
namespace EmptyIdentifier;
  extend base: EmptyIdentifier;

}
fn Main() -> i32 { return 0; }
```

This crashes the explorer.

### What did you expect to happen?

Not crash (and produce an error -- namespaces should not be allowed in this context).

### What actually happened?

Crashed.

### Any other information, logs, or outputs that you want to share?

The explorer crashes in the type_checker.cpp file, inside the `TypeCheckExpImpl` function, and in the `ExpressionKind::IdentifierExpression` case (line 3582 at the time of filing).

There, we try to evaluate `ident.value_node().static_type()` and crash as the `ident` refers to a namespace which has no static type (I think).

That's as far as I made it debugging, leaving this as a good first issue on the explorer if anyone is interested.

**Comment by noelg-cj** [comment]
Hey, thanks for the info! I am new to contributions but I would be happy to give it a shot!
