### ISSUE TITLE
How special is `self`? Is it a keyword?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#2984]
### Summary of issue:

A `self` binding behaves like a normal name binding, except that it can only appear in the implicit parameter list of a function (and indeed is the only non-generic binding that can appear in that list, at least currently). But how special is the name `self`, and is it reserved in other contexts?

### In favor of `self` being a regular identifier

We could say that the only special thing about `self` is that it's permitted as a name of a non-generic implicit parameter, and that it's otherwise usable as a normal identifier.

It may be useful to introduce the name `self` in a constructor-like factory function. This:

```carbon
class MyClass {
  fn Make(a: i32, b: i32) -> MyClass {
    returned var self: Self = {.a = b, .b = a};
    self.SwapAAndB();
    return var;
  }

  fn SwapAAndB[addr self: Self*]();

  private var a: i32;
  private var b: i32;
}
```

seems like it could be a nice idiomatic alternative to this C++ code:

```c++
class MyClass {
public:
  MyClass(int a, int b) : a(b), b(a) {
    SwapAAndB();
  }

  void SwapAAndB();

private:
  int a;
  int b;
};
```

Using `self` as an identifier may also be convenient in callback functions:

```carbon
class MyClass {
  fn Callback(self: Self) { ... }
  fn DoThing[self: Self]() {
    TakeCallback(MyClass.Callback, self);
  }
}
```

Also, the identifier `self` is not especially rare in C++ code, so for interoperability purposes it may be useful if `x.self` were valid.

### In favor of `self` being a keyword

The Carbon language rules would be simpler if all identifiers with special meaning are keywords. This would also match C++ better. Also, while we have a syntactic analogue between the `self: Self` syntax and the `name: Type` syntaxes, they are permitted in distinct, non-overlapping contexts, so treating them as different at the grammar level may be reasonable.

Taking `self` as a keyword may also make it easier to add new uses for this keyword. For example, if we want to allow `[self]` as a shorthand for `[self: Self]`, and `[addr self]` as a shorthand for `[addr self: Self*]`, and `self` is a regular identifier, we'd need to figure out what happens for cases like `[not_self]` -- is that accepted by the parser but rejected later because the identifier isn't `self`? Does that conflict with other uses of identifiers in an implicit parameter list?

`Self` (with capital `S`) is more special than `self`: it is implicitly introduced in various places, and `.Self` has special meaning in a constraint, both of which suggest that allowing explicit declarations of the name `Self` may be confusing, and using the keyword treatment may be preferable. It seems likely to minimize confusion to treat `self` and `Self` the same way, which suggests treating them both as keywords.

### Any other information that you want to share?

In explorer, `Self` is a keyword but `self` is not, with a semantic check that a non-generic binding appearing in an implicit parameter list is named "self". They both result in normal `IdentifierExpression`s as if they were not keywords, and regular name lookup is used for both, except for the special case of `.Self` which has a custom parse rule.

In the toolchain, both `self` and `Self` are keywords, but there's no semantic handling or name lookup implemented for either yet.

**Comment by jonmeow** [comment]
FYI I'd brought this up in relation to #2983 adding `self` to the keyword list.

**Comment by GauravN123** [comment]
class MyClass {
  fn Callback(self: Self) { ... }
  fn DoThing[self: Self]() {
    TakeCallback(MyClass.Callback, self);
  }
} 
In this Class , what is the functionality of Self. Please anyone explain . I think self is keyword

**Comment by jonmeow** [comment]
@GauravN123 Use either the [discussion boards](https://github.com/carbon-language/carbon-lang/discussions) or [Discord forums](https://discord.com/invite/ZjVdShJDAs) to ask for information about Carbon. Issues should remain focused on the topic.

**Comment by chandlerc** [comment]
Beyond the ones mentioned in the summary, for me a further argument for `self` being a keyword, at least initially, is that it provides more options for us to explore abbreviated method syntaxes. Rust, for example uses `self` as a keyword to provide an abbreviated method syntax.

Given these factors, and that it is relatively easy to relax this in the future, I lean towards making `self` a keyword at this point.

**Comment by chandlerc** [comment]
There's consensus in the leads, so this is decided based on my [comment](https://github.com/carbon-language/carbon-lang/issues/2984#issuecomment-1666648329) and the rationale in the summary.
