### ISSUE TITLE
Substitutions which can be mirrored are non-deterministic

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#3051]
### Description of the bug:

Digging into trace output, I noticed some substitutions were non-deterministic. For example (from separate runs):

```
substitution of {Self:! As -> .Self, T:! type -> T, impl binding Self:! As as interface As(T = T) where Self impls interface As(T = T) -> ()}
substitution of {T:! type -> T, Self:! As -> .Self, impl binding Self:! As as interface As(T = T) where Self impls interface As(T = T) -> ()}
```

### What did you do, or what's a simple way to reproduce the bug?

Run with --trace_context=prelude and look at output. Since the prelude is always loaded, it doesn't matter which file.

### What did you expect to happen?

There should be a deterministic substitution. Might need to ask @zygoloid which is preferred. :)

### What actually happened?

Note that `Self` and `T` are swapped between the two runs.

**Comment by zygoloid** [comment]
Bindings have an index based on their position in lexical scope that we can sort by here.

**Comment by chandlerc** [comment]
Would this make sense to flag as a good first issue?

**Comment by Rakshit358** [comment]
@jonmeow I am a complete beginner can I work on this issue?

**Comment by jonmeow** [comment]
Sure, you're welcome to take a look! We use "good first issue" for things which should help build familiarity.

**Comment by seekaddo** [comment]
Hey @jonmeow what is left here to be done? I tried analyzing the issue but it seems to be fixed by the changes from this #3039.

The trace output looks consistent to me.
here is an example:
```` console

->+ substitution of [`U:! type` -> `U`, `Self:! AddAssignWith` -> `.Self`, `impl binding Self:! AddAssignWith as interface AddAssignWith(U = U) where Self impls interface AddAssignWith(U = U)` -> `()`]

->+ substitution of [`U:! type` -> `U`, `Self:! AddAssignWith` -> `.Self`, `impl binding Self:! AddAssignWith as interface AddAssignWith(U = U) where Self impls interface AddAssignWith(U = U)` -> `()`]

->+ substitution of [`U:! type` -> `U`, `Self:! AddAssignWith` -> `.Self`, `impl binding Self:! AddAssignWith as interface AddAssignWith(U = U) where Self impls interface AddAssignWith(U = U)` -> `(witness 0 of witness for .Self:! type)`]

<<- substitution: interface AddAssignWith(U = U) where Self impls interface AddAssignWith(U = U) => interface AddAssignWith(U = U) where .Self impls interface AddAssignWith(U = U)

->+ substitution of [`.Self:! type` -> `T`, `impl binding .Self:! type as interface AddAssignWith(U = U) where .Self impls interface AddAssignWith(U = U)` -> `()`]

->+ substitution of [`.Self:! type` -> `T`, `impl binding .Self:! type as interface AddAssignWith(U = U) where .Self impls interface AddAssignWith(U = U)` -> `()`]

->+ substitution of [`.Self:! type` -> `T`, `impl binding .Self:! type as interface AddAssignWith(U = U) where .Self impls interface AddAssignWith(U = U)` -> `(witness 0 of witness for Self:! AddAssignWith(U))`]

````

**Comment by prabhatexit0** [comment]
I think this issue was fixed by #3039 @zygoloid

**Comment by seekaddo** [comment]
Thanks for the update. I will look for something different to begin with.

**Comment by geoffromer** [comment]
I'm tentatively closing this; please reopen if it's still an issue.
