### ISSUE TITLE
Restructuring & namespacing plan for the toolchain

### ISSUE THREAD

**Issue by chandlerc** [carbon-language/carbon-lang#3070]
I wanted to capture a discussion that several of us had around a restructuring of the toolchain to give ourselves a bit of a better directory layout and nomenclature.

Overall, the plan is to move towards a structure of major components where there is a reasonable namespace we can use to have a regular name component of code within that component. That is, rather than `SemanticsNode`, we'll have something structurally more like `Semantics::Node`.

As part of that, we noted a couple of things:
- There are really two layers inside of the `semantics` directory currently: the semantics-IR, and the code to check a parse tree and build that IR from it.
- The names we're using aren't awesome, and that showed up when trying to give command line flags that reflect the various stages.

One of the challenges we have is that the command line wants verb-shaped names as they're about the _action_ of that phase. But forming nouns out of the verbs for the phases doesn't follow a consistent structure. For example, "parser" is great, but "lowerer" is really awkward. So our thought was to switch to naming things after the verb everywhere.

The outcome of this (if I remember correctly -- please correct if I've misremembered) was to move to the following rough name / structure.

- `lex` directory, and if needed a `Carbon::Lex` namespace
- `parse` directory, and if needed a `Carbon::Parse` namespace
- `check` directory for the semantic & type checking logic that diagnoses invalid Carbon code and produces a valid semantics IR, and `Carbon::Check` namespace
- `lower` directory and `Carbon::Lower` namespace
- `codegen` directory and `Carbon::Codegen` namespace, treating "codegen" as a word

We talked about what to name the component that provides the semanitics IR definition and APIs, but didn't come up with anything that I think folks were delighted by. Some of the candidates:
- `SIR` -- not great if pronounced "sir".
- `SemIR` -- maybe pronounced "simmer"?
- `SemaIR` -- the abbreviation "sema" in Clang hasn't been enjoyable, especially for non-native speakers
- `CarbonIR` -- unclear if this is an IR written *in* Carbon or *for* Carbon. Also, we might end up with more IRs if we want to do high level optimizations.

We didn't really talk about how we want to handle the components that aren't named after a phase of compilation. Personally, I think these are maybe fine to have subdirectories but no namespace as they will tend to be widely used. And I'm also OK with the current names we have there. But flagging it in case others disagree.

We're not planning to rush out and change everything here. This issue is to try to capture the plan for whenever seems like an opportune moment to minimize the churn for folks with pending PRs, and to  make sure everyone is happy with the outcome. It should also allow us to start opportunistically using this nomenclature where needed, for example in the command line.

**Comment by jonmeow** [comment]
One thing to be sure of -- I think the conclusion was to split semantics into `check`/`Check` for logic, and `semantics`/`Semantics` for the IR. However, we'll try adjusting the code for namespaces first, before moving files, to see if it's a reasonable patch. The specific desire driving that was that both type checking and lowering would refer to the IR with similar names (which would be the case because they'd both use `Semantics::` namespace references).

My plan is to probably work on bits of the rename this week, just letting some open work wind down first.

**Comment by chandlerc** [comment]
BTW, I ran `SemIR` pronounced "simmer" by a few folks who've worked on a bunch of compiler projects, and they seemed to think it was a fine name approach.

> One thing to be sure of -- I think the conclusion was to split semantics into check/Check for logic, and semantics/Semantics for the IR.

Agreed about the split as a conclusion.

If we're going with `SemIR`, should that be the namespace?

**Comment by jonmeow** [comment]
> If we're going with `SemIR`, should that be the namespace?

I'd be fine with that -- does `sem_ir`/`SemIR` sound reasonable? (i.e., directory name to match)

**Comment by jonmeow** [comment]
Just noting for future reference, the use of `Carbon::Testing` was discussed [on Discord](https://discord.com/channels/655572317891461132/655578254970716160/1141153794097422457) as a consequence of https://github.com/carbon-language/carbon-lang/pull/3170/files#r1310772837

**Comment by jonmeow** [comment]
Further note for future reference, #3244 seems to be the outcome of a later decision _not_ to use `Carbon::Testing` for tests.
