### ISSUE TITLE
Can't find bazel package on ubuntu 22.04

### ISSUE THREAD

**Issue by vpelosio** [carbon-language/carbon-lang#3071]
### Description of the bug:

In the documentation is said:

These commands should help set up a development environment on your machine.

### Debian or Ubuntu

```
# Update apt.
sudo apt update

# Install tools.
sudo apt install \
  bazel \
  clang \
  gh \
  libc++-dev \
  lld \
  python3 \
  zlib1g-dev

# Install pre-commit.
pip3 install pre-commit

# Set up git.
# If you don't already have a fork:
gh repo fork --clone carbon-language/carbon-lang
cd carbon-lang
pre-commit install

# Run tests.
bazel test //...:all
```
but actually bazel cannot be installed out of the box in ubuntu 22.04.

```
user@pc:~$ sudo apt install bazel
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bazel
```

Furthermore python3-pip should be added to the list of packages to install because is needed for the command
`pip3 install pre-commit`

### Link to documentation:

https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md

### What should it say instead?

Improve the documentation to list the exact commands to follow to install bazel

**Comment by geoffromer** [comment]
It looks like [this step](https://bazel.build/install/ubuntu#add-dis-uri) is what's missing.

**Comment by felixf4xu** [comment]
bazel has pre-built binary for download at its release page, for example: https://github.com/bazelbuild/bazel/releases/download/7.0.2/bazel-7.0.2-linux-x86_64

**Comment by felixf4xu** [comment]
bazel has pre-built binary for download at its release page, for example: https://github.com/bazelbuild/bazel/releases/download/7.0.2/bazel-7.0.2-linux-x86_64
