### ISSUE TITLE
Remove clangd BUILD patch

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#3136]
#3112 patched the LLVM build to expose files from clangd, [here](https://github.com/carbon-language/carbon-lang/blob/trunk/bazel/patches/llvm/0004_Add_library_for_clangd.patch). If possible, this should be upstreamed: we should be trying to stay as close to LLVM upstream as we can, avoiding patches which we would need to maintain.

If it can't be upstreamed because upstream doesn't want these files used as a library, the dependency should be re-evaluated. In general we don't want to add dependencies on internal libraries, because of a lack of long-term stability guarantees.

FYI @josh11b @Maan2003

**Comment by jonmeow** [comment]
@josh11b Is this something that you can investigate? (I'm concerned about what happens if there's an API change, or the patch breaks)

**Comment by josh11b** [comment]
Got https://github.com/llvm/llvm-project/pull/81556 accepted upstream. Next time we sync llvm, we can hopefully remove (most of?) the patch (though the library did get renamed in the process).

**Comment by jonmeow** [comment]
Would you like to take care of syncing?

**Comment by archanakush900** [comment]
next time we sync llvm ,
