### ISSUE TITLE
bazel rules_bison is pretty old

### ISSUE THREAD

**Issue by dabrahams** [carbon-language/carbon-lang#314]
**Note: this is not really a problem.**  If you have the time to explain why my attempt to point at bison-3.7.5 didn't work, that would be great.  Otherwise feel free to close.

The executable semantics code is full of pointers and low-level haxx in part because nobody knew about
https://www.gnu.org/software/bison/manual/html_node/C_002b_002b-Bison-Interface.html or https://www.gnu.org/software/bison/manual/html_node/C_002b_002b-Variants.html

~But using those requires a much newer version of Bison than v3.3.x that is supported by the existing rules_bison~**Actually v3.3.2 has the necessary features.  I was seeing errors for other reasons**
I attempted to make my own update that included the new version but bazel merrily kept using the earlier version.

See https://github.com/chandlerc/rules_bison/compare/master...dabrahams:bison-3.7.5
and https://github.com/dabrahams/carbon-lang/compare/existential-handroll...dabrahams:modern-bison?expand=1

Perhaps @chandlerc can help
/cc @jsiek

**Comment by jonmeow** [comment]
We're not making substantial explorer changes anymore, so the version of bison doesn't affect as much. The long-term plan is to eliminate explorer code in favor of just having the toolchain with similar support, so I'm closing this.
