### ISSUE TITLE
Exponential blow-up in `impl` matching

### ISSUE THREAD

**Issue by geoffromer** [carbon-language/carbon-lang#3247]
### Description of the bug:

Impl matching can take exponential time in some cases.

### What did you do, or what's a simple way to reproduce the bug?

```
package Something api;

interface I {}

impl () as I {}
impl ((),) as I {}
impl forall [T:! type where .Self impls I and (.Self,) impls I] ((T,),) as I {}

fn F[T:! I](x: T) {}

fn Main() -> i32 {
    F((((((((((((((((((((((((((((((((),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),));
	return 0;
}
```

### What did you expect to happen?

I expected the program to run in reasonable time and return 0.

### What actually happened?

The program does not stop in a reasonable amount of time. Reducing the amount of nesting in the argument of `F` makes it faster.

### Any other information, logs, or outputs that you want to share?

Trace output indicates that the slowdown is because the number of `impl` matching operations grows exponentially.

**Comment by chandlerc** [comment]
Closing this as we aren't prioritizing further work on the explorer right now: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
