### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by sibi-venti** [carbon-language/carbon-lang#3308]
### Description of the bug:

In file included from external/com_google_absl/absl/time/internal/cctz/src/civil_time_detail.cc:15:
external/com_google_absl/absl/time/internal/cctz/include/cctz/civil_time_detail.h:18:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~

### What did you do, or what's a simple way to reproduce the bug?

bazel build //...

**Comment by sibi-venti** [comment]
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#debian-or-ubuntu
followed this and bazel clean and bazel build //... it worked

**Comment by ddkwork** [comment]
> https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#debian-or-ubuntu
> followed this and bazel clean and bazel build //... it worked

How to build on Windows 11?

**Comment by geoffromer** [comment]
We don't yet have a well-lit path for building on Windows, because we don't have many active contributors who use Windows. Some folks have reported success building Carbon using WSL, but I don't know any of the details.
