### ISSUE TITLE
Allow `[]` as a part of control flows

### ISSUE THREAD

**Issue by msadeqhe** [carbon-language/carbon-lang#3503]
### Summary of issue:

Considering we want to initialize variables in control flows, we have to put everything inside a block statement:

```cpp
{
    var i: i32 = 0;
    while (i < 10) {
        // :statements...
        ++i;
    }
}
```

A simpler and easier solution can be used to declare variables right within the headline of control flows, in C++ we have a way for it:

```cpp
// C++
for (int i = 0; i < 0; i++) {
    // :statements...
}
```

Carbon can use a similar syntax:

```cpp
// Carbon
while (var i: i32 = 0; i < 0) {
    // :statements...
    ++i;
}
```

But there is another way that is considerable.

### Details:

Everything inside `[...]` already means their values are deduced from arguments in function declarations.

```cpp
// Carbon
fn Buy[T:! type](something: T) {
    // :statements...
}
```

This approach can be expanded to control flows too:

```cpp
// Carbon
[var i: i32 = 0] while (i < 10) {
    // :statements...
    ++i;
}

// Carbon
// Or alternatively this one:
while [var i: i32 = 0](i < 10) {
    // :statements...
    ++i;
}
```

Furtunately, parameters and variable declarations in Carbon share the same syntax. So `[...]` can be reintroduced in Carbon with a generalized rule. `[...]` may means a list of variable declarations or deduced parameter declarations. This feature exists in Cpp2 (Cppfront):

```cpp
// Cpp2
(inout i: i32 = 0) while i < 10 next i++ {
    // :statements...
}
```

In Cpp2 (Cppfront) its name is parameterized block statement. `(...)` is a list of parameters that their life-time is limited to the body of `while` control flow.

### Any other information that you want to share?

Carbon already has `[...]` syntax in function declarations. `[...]` is already like a way to declare local variables within function signature. The same behavior can be expanded to control flows. Thanks.

**Comment by chandlerc** [comment]
This isn't really a sufficiently narrow or specific question for us to make a decision on. How best to initialize variables around control flow should be discussed with the community (for example in the ⁠syntax channel of Discord), and eventually a draft proposal built up to incorporate feedback and lay out a clear direction, motivation, and set of alternatives. If there are specific questions there that need to be decided, those should be filed as leads issues with a reference to the overarching proposal for context and the specific question ("should we use syntax ... or ... in the XYZ part of proposal N") that needs a decision.

Closing the issue for now.
