### ISSUE TITLE
Declaring lambdas with `fn` keyword

### ISSUE THREAD

**Issue by msadeqhe** [carbon-language/carbon-lang#3529]
### Summary of issue:

Traditionally lambdas (aka closures, functors and function objects) and functions (either global or member) are different. But modern programming languages, make them the same (especially in functional programming languages).

### Details:

Here is a summary of how programming languages are designed in regards to naming lambdas and functions:

Language  |What's the name of lambda?
----------|----------------
Rust      |Closure, Unnamed closure object
Swift     |Unnamed closure (function is named closure)
C++       |Lambda, Unnamed closure object
Java      |Lambda, Anonymous function (it's type is function interface)
Python    |Lambda, Unnamed function object (any function is object)
C#        |Lambda, Anonymous function
Cpp2      |Lambda, Local function, Unnamed function
D         |Function literal
Go        |Function literal, Anonymous function
Kotlin    |Function literal, Function instance
JavaScript|Arrow function, Function expression
PHP       |Arrow function, Anonymous function

So practically all of them (except C++ and Rust) use a similar term to refer to both lambda and function. Though C++ has `std::function<..>` type to hold either function or lambda. Therefore we can assume almost all modern programming languages use a similar term to refer to both lambda and function.

### Examples

Additionally Go, D, JavaScript, PHP, C#, Cpp2, R and ... use a similar syntax to declare both lambda and function.

#### Go

```go
y := func(x int) int { return x + 1 }

```

#### D

```d
auto y = function int(int x) { return x + 1; };
auto z = (x) => x + 1;
```

#### JavaScript

```js
let y = function(x) { return x + 1; };
let z = (x) => x + 1;
```

#### PHP

```php
$y = function($x) { return $x + 1; };
$z = fn($x) => $x + 1;
```

#### C#

```cs
// `delegate` keyword declares a function reference.

// It's a function reference.
delegate int TypeDelegate(int x);

// It holds a function.
int FunctionName(int x) { return x + 1; }
TypeDelegate y0 = FunctionName;

// They hold lambdas.
TypeDelegate y1 = delegate(int x) { return x + 1; };
System.Func<int, int> y2 = delegate(int x) { return x + 1; };

// Short lambda syntax, is similar to an unnamed function declaration:
//  `int <unnamed>(int x) ...`
var z = int(int x) => x + 1;
```

#### Cpp2 (cppfront)

```cpp
// Function declaration
f: (x: int) -> int = { return x + 1; }
// Terser function declaration
f: (x) x + 1;

// Lambda syntax
y: = :(x: int) -> int = { return x + 1; };
// Terser lambda syntax
z: = :(x) x + 1;
```

#### R

```cpp
y <- function(x) { x + 1 }
z <- \(x) x + 1
```

Carbon can reuse `fn` keyword to have the same (or similar) declaration for both lambdas and functions.

### Any other information that you want to share?

Carbon already uses `let` and `var` instead of explicitly mixing `const`, `&` and `&&` for function parameters. Therefore it has higher-level view than C++ on function parameters. In the same way, Carbon can have higher-level view than C++ on lambdas and functions. Thanks.

**Comment by geoffromer** [comment]
"Similar" is pretty vague, so I'm having a little trouble figuring out what specific decision this issue is asking the leads to make. Is it asking whether lambdas should use `fn` as an introducer? If so, that should probably go in the summary, and maybe the issue title (note that you can edit both of them).

**Comment by chandlerc** [comment]
We're definitely interested in exploring what syntax works best for lambdas, but we think that's best done in community discussions and eventually a proposal.

Once there is a proposal, if there are competing syntaxes or a lack of consensus on a specific introducer, that's the time and place to open a leads issue to make a decision. We would need to have the proposal though to surface the tradeoffs of the options and be able to provide a resolution.

Closing this issue, and we suggest opening a fresh one if needed once there is a proposal to serve as the context.
