### ISSUE TITLE
Logo is really bad

### ISSUE THREAD

**Issue by ghost** [carbon-language/carbon-lang#3538]
This is not a bug, more of a suggestion. I think it would be a good idea to change the logo.

![image](https://github.com/carbon-language/carbon-lang/assets/60055347/4926d345-0a83-4d79-bdd5-cf66c16fecff)

The logo looks really bad. I asked a bunch of people what they think about it, and the general 
consensus is that its too simple. If you place the logo over a solid black background, you can't even make out the circle. You can see this problem if you browse GitHub in dark-mode.  Reminds me of this XKCD: https://xkcd.com/993/. I know this is not a priority issue, but maybe would be worth making a better design?

**Comment by hulxv** [comment]
Is it something important for programming languages? who cares about it now? I think carbon is an under-development till now and there are things more important than logo.

**Comment by geoffromer** [comment]
Please see [this FAQ entry](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#why-isnt-there-a-carbon-language-logo):

> Establishing a Carbon Language logo isn't a priority right now. Remember that this project is an _experiment_, and so we think it's best to concentrate efforts on ensuring that the language succeeds at its goals instead.
>
> We have a few drafts in the works, but it requires a fair amount of work to get right, and getting it wrong is costly, so we won't be adding one in the near future. Don't suggest logos, because we need to be careful about how we create one.
