### ISSUE TITLE
Change name of PatternMatch

### ISSUE THREAD

**Issue by jsiek** [carbon-language/carbon-lang#354]
one suggestion: BindPatternVariables

There's also a suggestion to make PatternMatch a method of Dictionary.
But PatternMatch is primarily a switch statement over values... which
suggests that it should be a method of the Value class.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
