### ISSUE TITLE
Bazel explorer installation error

### ISSUE THREAD

**Issue by TabletBoii** [carbon-language/carbon-lang#3540]
### Description of the bug:

When i tried to build carbon explorer with command bazel run //explorer -- ./explorer/testdata/print/format_only.carbon, i got an error "FATAL failure at explorer/syntax/prelude.cpp:22: Failed to parse prelude:"

### What did you do, or what's a simple way to reproduce the bug?

I followed the instruction on https://github.com/carbon-language/carbon-lang?tab=readme-ov-file

### Any other information, logs, or outputs that you want to share?

I used Ubuntu 22.04.3 LTS via wsl on Windows Version 22H2 (build 19045.3570)
Backtrace: #0 0x000055a4fd671a7d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x993a7d)
 #1 0x000055a4fd67207b PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #2 0x000055a4fd66f136 llvm::sys::RunSignalHandlers() (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x991136)
 #3 0x000055a4fd672e75 SignalHandler(int) Signals.cpp:0:0
 #4 0x00007f43a2e3f520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f43a2e939fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x00007f43a2e3f476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007f43a2e257f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x000055a4fd5e0025 (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x902025)
 #9 0x000055a4fd0f1995 (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x413995)
#10 0x000055a4fd4e7e39 Carbon::AddPrelude(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Carbon::Arena*, std::__1::vector<Carbon::Declaration*, std::__1::allocator<Carbon::Declaration*> >*, int*) (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x809e39)
#11 0x000055a4fd10b2c0 Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0::operator()() const parse_and_execute.cpp:0:0
#12 0x000055a4fd10b985 decltype(fp()) Carbon::RunWithExtraStack<Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0>(Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0)::'lambda'()::operator()() const parse_and_execute.cpp:0:0
#13 0x000055a4fd10b955 void llvm::function_ref<void ()>::callback_fn<decltype(fp()) Carbon::RunWithExtraStack<Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0>(Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0)::'lambda'()>(long) parse_and_execute.cpp:0:0
#14 0x000055a4fd4e7c49 llvm::function_ref<void ()>::operator()() const (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x809c49)
#15 0x000055a4fd4e7c23 Carbon::Internal::RunWithExtraStackHelper(llvm::function_ref<void ()>)::$_0::operator()() const stack_space.cpp:0:0
#16 0x000055a4fd4e7bd5 void llvm::function_ref<void ()>::callback_fn<Carbon::Internal::RunWithExtraStackHelper(llvm::function_ref<void ()>)::$_0>(long) stack_space.cpp:0:0
#17 0x000055a4fd4e7c49 llvm::function_ref<void ()>::operator()() const (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x809c49)
#18 0x000055a4fd62c60a llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/tablet_boii/.cache/bazel/_bazel_tablet_boii/7d1f50a12a38f087963456a7cf585fcd/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x94e60a)
#19 0x000055a4fd62ca8f RunSafelyOnThread_Dispatch(void*) CrashRecoveryContext.cpp:0:0
#20 0x000055a4fd62d339 auto void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...)::operator()<void (*&)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*&>(auto&&, auto&&...) const CrashRecoveryContext.cpp:0:0
#21 0x000055a4fd62d2b5 decltype(static_cast<auto>(fp)(static_cast<auto>(fp0)...)) std::__1::__invoke_constexpr<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...), void (*&)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*&>(auto&&, auto&&...) CrashRecoveryContext.cpp:0:0
#22 0x000055a4fd62d263 decltype(auto) std::__1::__apply_tuple_impl<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...), std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&, 0ul, 1ul>(auto&&, std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&, std::__1::__tuple_indices<0ul, 1ul>) CrashRecoveryContext.cpp:0:0
#23 0x000055a4fd62d1e2 decltype(auto) std::__1::apply<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...), std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&>(auto&&, std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&) CrashRecoveryContext.cpp:0:0
#24 0x000055a4fd62d17c void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*) CrashRecoveryContext.cpp:0:0
#25 0x000055a4fd62cf15 void* llvm::thread::ThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*) CrashRecoveryContext.cpp:0:0
#26 0x00007f43a2e91ac3 (/lib/x86_64-linux-gnu/libc.so.6+0x94ac3)
#27 0x00007f43a2f23660 (/lib/x86_64-linux-gnu/libc.so.6+0x126660)
FATAL failure at explorer/syntax/prelude.cpp:22: Failed to parse prelude:
prelude.carbon:0: Error opening file: No such file or directory
Aborted

**Comment by chandlerc** [comment]
Thanks for reporting, this is the same core issue as #3541 and should also be fixed #3544.
