### ISSUE TITLE
Does Lambdas' introduction of ref and copy resolve the open question in values.md?

### ISSUE THREAD

**Issue by CJ-Johnson** [carbon-language/carbon-lang#3859]
### Summary of issue:

[/docs/design/values.md#value-representation-and-customization](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/values.md)

> Open question: The syntax for this is just placeholder, using a placeholder keyword. It isn't final at all and likely will need to change to read well.

Can `const Self` be replaced with `const copy`? Can `const Self*` be replaced with `const ref`?

See Lambdas proposal at https://github.com/carbon-language/carbon-lang/pull/3848

**Comment by justzh** [comment]
Yes it does because the altimeter requires it.

**Comment by geoffromer** [comment]
It seems like it would be confusing if in this context `const copy` and `const ref` are self-contained expressions that refer to types, while in an implicit parameter list they are introducers or modifiers for a larger syntactic construct that refers to a variable (or a whole set of variables, in the case of the default capture mode).

It does seem like there's some commonality in the underlying semantics, but I'm not sure how to surface that in the syntax. When/if the design for function calls, `extend adapt`, etc. gets to a point where we can define reference types in terms of those concepts, I think we'll be in a much better position to sort this out.

**Comment by CJ-Johnson** [comment]
Since we decided to go a different direction for now, I think it makes sense to close this issue.
