### ISSUE TITLE
Getting-Started package issue

### ISSUE THREAD

**Issue by keys-i** [carbon-language/carbon-lang#3896]
### Description of the bug:

bazel is not a package of Ubuntu

### Link to documentation:

https://github.com/carbon-language/carbon-lang

### What should it say instead?

bazel-bootstrap \

### Any other information, logs, or outputs that you want to share?

I tried running this on Ubuntu 23.10 which told me to use bazel-bootstrap

**Comment by jonmeow** [comment]
Thanks. Note that bazel-bootstrap is not the same, and will conflict with a correct bazel install [both try to install /usr/bin/bazel]. We should fix notes, but in the meantime bazel's install instructions are at https://bazel.build/install/ubuntu#install-on-ubuntu; I'd suggest either setting up bazel's apt repo ([commands here](https://bazel.build/install/ubuntu#add-dis-uri)), or downloading bazelisk.

**Comment by jonmeow** [comment]
Instructions updated by #4129
