### ISSUE TITLE
I have updated this file to use bazel internally. But I could not convert this into bazel.

### ISSUE THREAD

**Issue by PramodNeel** [carbon-language/carbon-lang#3961]
I have updated this file to use bazel internally. But I could not convert this into bazel.

_Originally posted by @maan2003 in https://github.com/carbon-language/carbon-lang/pull/2902#discussion_r1244388614_

**Comment by jonmeow** [comment]
It's not clear to me what's being asked here -- this is just a copy of a resolved review comment. I'm closing this issue; please provide more detail if you had a question.
