### ISSUE TITLE
Update sample code in README

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#3969]
### Description of the bug:

The examples in the README need to be updated to reflect the change to package syntax from proposal https://github.com/carbon-language/carbon-lang/pull/3927 .

### Link to documentation:

https://github.com/carbon-language/carbon-lang/blob/trunk/README.md

### What should it say instead?

`package <something> api;` should just be `package <something>;`

**Comment by ryoari** [comment]
Hi @josh11b, I'm interested in this issue and have started working on updating the README to reflect the changes from proposal [#3927](https://github.com/carbon-language/carbon-lang/pull/3927). I'll make sure to update all relevant examples and submit a pull request soon.
