### ISSUE TITLE
How to compile a shared library .so

### ISSUE THREAD

**Issue by panjea** [carbon-language/carbon-lang#3997]
### Description of the bug:

It is not clear how to call the compiler to build a shared library .so.
It is not even clear where the compiler is, and what it is called.
I was expecting this command:
```
/usr/local/bin/bazelisk-linux-amd64 run //explorer -- ./explorer/testdata/print/format_only.carbon
```
To have built something like `carbonc` which i can call directly on .carbon files.

Where is bazelisk putting the compiler?
Under `carbon-lang/bazel-bin` i see explorer, is explorer the name of the carbon compiler?

**Comment by chandlerc** [comment]
Please see our project status: https://github.com/carbon-language/carbon-lang#project-status

This is an early, experimental project. The explorer provides a way to demo the semantics of Carbon.

We are working on a compiler in the `toolchain` tree, but it is not quite far enough along to compile Carbon code into interesting things like shared libraries. We're working right now on getting all of the *basic* functionality (language designs, standard library, linking) into the compiler. Shared libraries are a (very) long way away.
