### ISSUE TITLE
Error while building docker image as part of devcontainer

### ISSUE THREAD

**Issue by nirmal-j-patel** [carbon-language/carbon-lang#4065]
When use VS Code to open the carbon-lang directory inside the devcontainer, I get the following error during image build:

```
[2024-06-19T20:19:22.284Z] Errors were encountered while processing:

 /tmp/apt-dpkg-install-nzc56z/31-libclang-rt-15-dev_1%3a15.0.7~++20231019083512+8dfdcc7b7bf6-1~exp1~20231019203551.119_amd64.deb

 /tmp/apt-dpkg-install-nzc56z/38-libpolly-15-dev_1%3a15.0.7~++20231019083512+8dfdcc7b7bf6-1~exp1~20231019203551.119_amd64.deb
[2024-06-19T20:19:22.407Z] E: Sub-process /usr/bin/dpkg returned an error code (1)
[2024-06-19T20:19:28.922Z] Error: building at STEP "RUN ./llvm.sh 15 all": while running runtime: exit status 100
```

I can attempt to update the base ubuntu image and clang versions and send a pull request if this is a valid issue.

**Comment by shubhamsolo** [comment]
I've encountered the same error while building the image in the devcontainer:

```
[2024-06-19T20:19:22.284Z] Errors were encountered while processing:
 /tmp/apt-dpkg-install-nzc56z/31-libclang-rt-15-dev_1%3a15.0.7~++20231019083512+8dfdcc7b7bf6-1~exp1~20231019203551.119_amd64.deb
 /tmp/apt-dpkg-install-nzc56z/38-libpolly-15-dev_1%3a15.0.7~++20231019083512+8dfdcc7b7bf6-1~exp1~20231019203551.119_amd64.deb
[2024-06-19T20:19:22.407Z] E: Sub-process /usr/bin/dpkg returned an error code (1)
[2024-06-19T20:19:28.922Z] Error: building at STEP "RUN ./llvm.sh 15 all": while running runtime: exit status 100
```
To resolve this, I propose updating the base Ubuntu image and Clang versions used in the build. If this is a valid approach, I can make the necessary changes and submit a pull request for review.

Please let me know if this solution is acceptable, and I'll proceed accordingly.

Thanks!

Shubham Solanki

**Comment by jonmeow** [comment]
We'd be happy to take a PR in this area. I think these images just don't see much use, so I'm not surprised they've been broken.

**Comment by nirmal-j-patel** [comment]
@shubhamsolo please let me know if you are still interested in attempting this.
