### ISSUE TITLE
stale files in `bazel-bin/toolchain/install/prefix_root/lib/carbon/core` can cause autoupdate to fail

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#4208]
The autoupdate script uses `bazel run //toolchain/testing:file_test --autoupdate`, which runs in a non-hermetic mode that can see files left behind in `bazel-bin/...`. This causes some strange failures. To reproduce:

- Add a .carbon file to core/prelude/
- Run autoupdate, or build the driver, or run the tests. This causes the file to be copied into `bazel-bin/toolchain/install/prefix_root`.
- Remove the .carbon file again
- Rerun autoupdate

Result: when scanning for prelude files, the file in prefix_root is found. But then when running tests, the prelude is loaded from the top of the workspace instead, and the .carbon file is not found. Net result: all the non-no_prelude tests fail with an "No such file or directory" error.

**Comment by chandlerc** [comment]
A theory was that this had to do with changing directory after we collect the list of files, but that's not the issue.

The thing left behind is actually a dangling symlink, so listing the directory finds it but it fails when we try to open it.

Still pondering whether there is an effective way to return to hermeticity here...

**Comment by jonmeow** [comment]
I think this was fixed by #4291 (prelude manifest)
