### ISSUE TITLE
Recovered parse errors should fail compilation

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#4259]
### Description of the bug:

Some errors, such as missing or additional whitespace next to an operator, are recovered by the compiler. In this case, the compiler outputs a diagnostic, but no parse nodes are marked as having an error, and so the compilation succeeds.

### What did you do, or what's a simple way to reproduce the bug?

This problem can be seen in any of the files starting with `recover_` in the
[`toolchain/parse/testdata/operators/` directory](https://github.com/carbon-language/carbon-lang/tree/trunk/toolchain/parse/testdata/operators).

### What did you expect to happen?

 Those tests should only pass with a filename (or split filename) starting with `fail_`. We need some way to indicate an error in the parse output (like I believe exists for the lex output) even when there are no nodes with an error in the output parse tree.

### What actually happened?

Those files have diagnostics with a `CHECK:STDERR` prefix, but the parse stage succeeds.

**Comment by jonmeow** [comment]
There are a few problems here, notably that pattern matching doesn't correctly diagnose issues. Since this is a bit more nuanced, I don't think it's a good first issue. I'll just take care of it.
