### ISSUE TITLE
Commit access cleanup

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#4274]
I'm looking at cleaning up [commit access](https://github.com/orgs/carbon-language/teams/commit-access) that hasn't been used for the past six months, per the new [commit access policy](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/commit_access.md). GitHub doesn't have a great way to notify people, so trying this...

@fowles @mattgodbolt @camio @jsiek @tkoeppe @Pixep @pmqtt @pk19604014 

If any of you are planning to resume commits to Carbon soon, please let me know, either directly or by responding here. Otherwise, I'll remove commit access in a week (Wednesday Sep 11). If things change and you resume making commits, you can ask for commit access to be restored. We're just trying to make sure that we don't have idle permissions hanging around.

Note, GitHub will probably email when I make the actual changes.

**Comment by pk19604014** [comment]
Thanks for the heads up, ok to remove me for now.
  Pasha.

**Comment by camio** [comment]
Okay to remove me as well.

**Comment by jonmeow** [comment]
This is now done. Please let me know if there are issues.
