### ISSUE TITLE
Should statements be expressions?

### ISSUE THREAD

**Issue by austern** [carbon-language/carbon-lang#430]
Some languages make it easy to treat some or all statements as expressions. Examples:

In Rust, compound statements are expressions. All of the following are legal Rust:
```
let x = { 1; 2 }; // The value is 2
let x = { 1; 2; }; // The value is (), the value of the unit type
let x = if true { 1 } else { 2 }; // The value is 1
let x = while (p) { do_something(); } // The value is ()
let x = match result { Ok(val) => val, Err(_) => -1 };
```

Standard C++ doesn't treat compound statements as expressions, but one can emulate it with just a bit of syntactic noise by means of an immediately-evaluated zero-argument lambda.
```
const int x = []{ std::cout << "foo\n"; return 5; }();
```

The GNU C++ statement-expression extension allows nesting compound statements within expressions. The following is legal in C++ with GNU extensions, although not in standard C++:
```
const int x = ({ std::cout << "foo\n"; 5; });
```

Should (some? all?) statements in Carbon be treated as expressions?

Pros:
- This is a common need in C++, as evidenced by the GNU extension and by the immediately-evaluated-lambda idiom.
- Rust's use of `if`/`else` and `match` within expressions is a more readable replacement for C++'s chained `?:` ternary operator.

Cons:
- Sometimes, as with Rust's while loops, there's no interesting value to ascribe to an expression
- We may need to answer questions about scope that we could otherwise avoid
- Depending on how the feature is implemented, we might end up with two things that look very similar but have very different meanings, as with Rust's `{ 1; 2 }` versus `{ 1; 2; }`

**Comment by isometric** [comment]
> ... possibly ending up being an addition of `thing3()` with whatever comes next, because we can't commit to the interpretation of the first `{` until much later. 

I'm not sure I see why this is a problem? This seems like something we'd want, and would apply to the other proposals thus far too. 

I think the GCC syntax seems the best thus far, string a nice balance between clarity/visibility to the user over missing semicolon and  but if the goal is to make it look like pulling a value of of an anonymous struct maybe something like this:

`var x = { var foo = 2; }.foo`

or alternatively the reverse of a function call:

`var x = { var foo = 2; }(bar(foo))`
