### ISSUE TITLE
Cannot compile toolchain

### ISSUE THREAD

**Issue by BhJaipal** [carbon-language/carbon-lang#4344]
### Description of the bug:

While I was tring to build carbon language toolchain and explorer error occured and it failed

### What did you do, or what's a simple way to reproduce the bug?

bazel run //toolchain

### What did you expect to happen?

I expected it to compile successfully

### What actually happened?

An error occured
jaipal001@pop-os:~/.carbon-lang$ bazel run //toolchain
INFO: Invocation ID: 59d6aa8e-a3f3-4174-80b3-8fd2893a5ae2
INFO: Analyzed target //toolchain:toolchain (0 packages loaded, 0 targets configured).
ERROR: /home/jaipal001/.carbon-lang/common/BUILD:38:11: Compiling common/command_line.cpp failed: (Exit 1): clang++ failed: error executing CppCompile command (from target //common:command_line) /usr/lib/llvm-14/bin/clang++ -no-canonical-prefixes -fcolor-diagnostics -Werror -Wall -Wextra -Wthread-safety -Wself-assign -Wimplicit-fallthrough -Wctad-maybe-unsupported -Wextra-semi ... (remaining 105 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from common/command_line.cpp:5:
In file included from ./common/command_line.h:11:
In file included from ./common/check.h:8:
./common/check_internal.h:40:24: error: unknown attribute 'noinline' ignored [-Werror,-Wunknown-attributes]
[[noreturn, gnu::cold, clang::noinline]] auto CheckFail(Ts&&... values)
                       ^~~~~~~~~~~~~~~
1 error generated.
Target //toolchain/install:run_carbon failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21.486s, Critical Path: 21.21s
INFO: 128 processes: 14 internal, 114 linux-sandbox.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

### Any other information, logs, or outputs that you want to share?

Error:
jaipal001@pop-os:~/.carbon-lang$ bazel run //toolchain
INFO: Invocation ID: 59d6aa8e-a3f3-4174-80b3-8fd2893a5ae2
INFO: Analyzed target //toolchain:toolchain (0 packages loaded, 0 targets configured).
ERROR: /home/jaipal001/.carbon-lang/common/BUILD:38:11: Compiling common/command_line.cpp failed: (Exit 1): clang++ failed: error executing CppCompile command (from target //common:command_line) /usr/lib/llvm-14/bin/clang++ -no-canonical-prefixes -fcolor-diagnostics -Werror -Wall -Wextra -Wthread-safety -Wself-assign -Wimplicit-fallthrough -Wctad-maybe-unsupported -Wextra-semi ... (remaining 105 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from common/command_line.cpp:5:
In file included from ./common/command_line.h:11:
In file included from ./common/check.h:8:
./common/check_internal.h:40:24: error: unknown attribute 'noinline' ignored [-Werror,-Wunknown-attributes]
[[noreturn, gnu::cold, clang::noinline]] auto CheckFail(Ts&&... values)
                       ^~~~~~~~~~~~~~~
1 error generated.
Target //toolchain/install:run_carbon failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21.486s, Critical Path: 21.21s
INFO: 128 processes: 14 internal, 114 linux-sandbox.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

**Comment by jonmeow** [comment]
I see you're using LLVM 14: `/usr/lib/llvm-14/bin/clang++`

We require at least LLVM 16 to compile. Please see https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#old-clang-versions for more information on this as well as some resolution advice.

I'm closing this since using a more recent version of LLVM will resolve the issue.

**Comment by BhJaipal** [comment]
> I see you're using LLVM 14: `/usr/lib/llvm-14/bin/clang++`
> 
> We require at least LLVM 16 to compile. Please see https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#old-clang-versions for more information on this as well as some resolution advice.
> 
> I'm closing this since using a more recent version of LLVM will resolve the issue.

Ok

**Comment by BhJaipal** [comment]
> I see you're using LLVM 14: `/usr/lib/llvm-14/bin/clang++`
> 
> We require at least LLVM 16 to compile. Please see https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#old-clang-versions for more information on this as well as some resolution advice.
> 
> I'm closing this since using a more recent version of LLVM will resolve the issue.

I have installed llvm 16, what to do next because it still gives same error  run

**Comment by geoffromer** [comment]
Does the error message still indicate it's using llvm 14?

It might be better to discuss this on the #build-help channel of our Discord server, since it's not clear this is a Carbon bug.

**Comment by BhJaipal** [comment]
> Does the error message still indicate it's using llvm 14?
> 
> It might be better to discuss this on the #build-help channel of our Discord server, since it's not clear this is a Carbon bug.

Maybe not, I did some environment variables changes then it use llvm 16 but still clang instead instead of clang++
So, I have decided, I will instead wait for its official debian release, when it's out, I will surely use it
