### ISSUE TITLE
do we want variable-arity operators?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#451]
In (at least) three cases, we may wish to consider treating traditionally infix binary operators as variable-arity operators. The cases are:

1) Comparisons

```
if (a <= b <= c) {}
if (a == b == c) {}
if (a <= b == c <= d) {}
```

Options:

a) We pick a precedence and associativity rule, and compare the `Bool` result of one operator with the operand of another operator. [This is the traditional / C++ choice.]
b) We treat these operators as being non-associative / having incomparable precedence, and reject these examples unless parentheses are added. [This is the current approach in #168.]
c) We treat comparison operators as being variable-arity (with the same operator), so the above are desugared into something like:
```
if (LessEqualCompare((a, b, c))) {} // call method of suitable interface passing a 3-tuple
if (EqualEqualCompare((a, b, c))) {} // call method of suitable interface passing a 3-tuple
```
The third `if` statement would be ill-formed.
d) We treat comparison operators as being variable-arity, and desugar them into chained binary operators, so the above are desugared into something like:
```
if (a <= b and b <= c) {}
if (a == b and b == c) {}
if (a <= b and b == c and c <= d) {}
```
... except that the operands are each evaluated once before any comparisons are performed. [This is the Python choice.]

Note in particular that the variable-arity option is not the same as treating `<=` and friends as operators with a funny return type with a custom `<=` operator. For example, these are not equivalent:

```
if (a == b == c) {} // are a, b, and c equal?
if ((a == b) == c) {} // is the result of comparing a and b the boolean value c?
```

2) Commas for tuple formation

We can consider allowing an unparenthesized comma expression to form a tuple, and thereby uniformly use parentheses only for grouping. For example:

```
var (Int, Int, Int) x;
x = 1, 2, 3; // OK, assuming ',' is higher precedence than '='
```

Then `,` would be a variable-arity operator that forms tuples of arity >= 2. `()` and `(a,)` would be syntactic special cases that require parentheses.

a) Don't do this; the parentheses are part of the tuple syntax. [This is the Haskell choice.]
b) Do this; the parentheses surrounding `(a, b, c)` are optional. [This is the Python choice.]

3) Chained assignment

```
x = y = z;
```

There are multiple ways this could work:

a) This is two uses of a right-associative binary `=` operator. This code converts `z` to the type of `y` and stores to `y`, then [loads from `y` and] converts the result to the type of `x` and stores to `x`. [This is the traditional choice; C++ reloads `y` whereas C does not. This is also the current approach in #168.]
b) This is ill-formed. We don't support chained assignment.
c) This is one use of a variable-arity `=` operator. The value `z` is stored to both `x` and `y`. [This is the Python choice.]

**Comment by josh11b** [comment]
It seems we have in practice adopted 1B, for example in #702 . I recommend affirming that decision and closing this issue.

**Comment by chandlerc** [comment]
Yep, leads have consensus on https://github.com/carbon-language/carbon-lang/issues/451#issuecomment-1311179479
