### ISSUE TITLE
Function parameters and match bindings are not Declarations in the grammar

### ISSUE THREAD

**Issue by dabrahams** [carbon-language/carbon-lang#456]
It's workaround-able, but it would be nicer for the interpreter if they all had Declaration AST nodes.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
