### ISSUE TITLE
Replace some (all?) type equality with subtyping

### ISSUE THREAD

**Issue by jsiek** [carbon-language/carbon-lang#495]
To have some fairly normal examples of implicit conversions, perhaps we should add
floating point numbers to the executable semantics and an implicit conversion such as
```
Int <: Float
```

A more esoteric example of subtyping is dealing with the ambiguity regarding tuples and tuple types:
```
(Type,Type) <: Type
```

**Comment by zygoloid** [comment]
> A more esoteric example of subtyping is dealing with the ambiguity regarding tuples and tuple types:
> 
> ```
> (Type,Type) <: Type
> ```

#2360 proposes modeling this as an implicit conversion, and #2357 implemented this in explorer.

**Comment by chandlerc** [comment]
> > A more esoteric example of subtyping is dealing with the ambiguity regarding tuples and tuple types:
> > ```
> > (Type,Type) <: Type
> > ```
> 
> #2360 proposes modeling this as an implicit conversion, and #2357 implemented this in explorer.

@zygoloid Should this issue be closed then? Or is there more work we should look into here?

**Comment by zygoloid** [comment]
I think the other concrete suggestion here is supporting conversion from int to float. That's already [permitted by the design](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/expressions/implicit_conversions.md#data-types) and I think there's no significant concern that we'd forget to do this when we add floating-point types to explorer, so I think this is safe to close.
