### ISSUE TITLE
Should some values be self-typed? If so, which ones?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#508]
There are a number of contexts in which we have suggested that certain values should have unique types. Moreover, there have been suggestions that we can define the type of certain values as being the same entity as value itself (notably, we say the type of the empty tuple `()` is the empty tuple `()`). We could employ this lifting of values to the type level in general for values that should have unique types, forming in each case a type with exactly one value, where that value is the type itself.

The cases to which we might want to apply this include:

* The empty tuple (and tuples whose elements are all on this list, such as `((), (), ())`)
* Numeric literals (and perhaps string literals?)
* Functions

Examples:

```
// Tuples.
var () x = ();
fn f() -> () {
  return ();
}
```

```
// Numeric literals.
fn F(1: _) {}
fn Run() {
  F(1); // OK
  F(2); // type error
}
// OK, n is initialized with value 0 of type 0, which is in range.
// There is no possibility of overflow in such expressions.
var Int n = 123456789 * 123456789 - 123456789 * 123456789;
```

```
// Functions.
fn IsEven(Int n) -> Bool { return n mod 2 == 0; }
fn PrintIf(List(Int) list, (Type$$ Pred) predicate) {
  for (Int n : list) {
    if (predicate(n)) {
      Print(n);
    }
  }
}
fn Run() {
  List(Int) mylist = {1, 2, 3};
  // Specializes PrintIf for IsEven, no runtime dispatch
  PrintIf(mylist, IsEven);
}
```

Note that this has a potential foundational concern: repeatedly asking for the type of a value, and then that type's type, and so on, will not in general converge to `Type`, but I'm not sure that's a fundamental problem. (I think it's plausible that we'll want to model `Type` as an interface rather than as a type-type.)

So there are two questions here:

1) Do we want unique types for numeric literals and functions?
2) Do we want self-types for some or all of those cases?

**Comment by OlaFosheimGrostad** [comment]
I don't know if this is helpful, but I've always thought that literals should be though of in classical mathematical terms (Peano) as pure syntactical expressions. So 1 is just a shorthand for 'successor(zero)', you can do the same for all basic language constructs (think in terms of functional languages or  term-rewriting languages such as Pure and Maude) with an applicative transform to a canonical representation (normalization). Then you have a mapping to the implementation from the canonical form. If you combine this with flow-typing you might get something interesting (i.e. you apply constraints through flow-typing, reducing the set of corresponding concrete implementation types and if there is more than one left in the end, maybe you can use a priority scheme).

Ole-Johan Dahl's 1990s introduction-level book "Verifiable Programming" shows this for basic programming language types as showed in this [simple presentation without the verification aspect](https://www.mn.uio.no/ifi/english/about/ole-johan-dahl/bibliography/value-types-and-object-classes.pdf) .

(Anyway, I am somewhat disappointed that "simplified" term-rewriting and flow-typing isn't used more in mainstream metaprogramming/generic programming. Even something limited, such  as XQuery/XSLT could be quite potent.)

**Comment by josh11b** [comment]
Proposal #2360 offers an answer to this question: only `Type` is self-typed, but some values may be converted to their type. So the type of `()` is not `()` but `() as Type`.

**Comment by josh11b** [comment]
There is also the question: "Do we want unique types for numeric literals and functions?"
#144 answers this question for numeric literals with "yes": the type of int literal `N` is `IntLiteral(N)`, which has type `Type`. We have been applying this approach to other kinds of literals as well, for example `RealLiteral(...)` for floating-point types.

There last remaining question is whether functions have a unique type.

**Comment by chandlerc** [comment]
> There is also the question: "Do we want unique types for numeric literals and functions?" #144 answers this question for numeric literals with "yes": the type of int literal `N` is `IntLiteral(N)`, which has type `Type`. We have been applying this approach to other kinds of literals as well, for example `RealLiteral(...)` for floating-point types.

Agreed, in practice I think we've decided "yes" here, but we should confirm that.

> 
> There last remaining question is whether functions have a unique type.

I don't think we have an answer here, but I also don't think we need one in *this* issue. I'd suggest following up with a fresh question there once we have a better idea of how callable stuff should work.

**Comment by chandlerc** [comment]
Confirmed with leads, and we're happy with the answers summarized here:
https://github.com/carbon-language/carbon-lang/issues/508#issuecomment-1310532783
https://github.com/carbon-language/carbon-lang/issues/508#issuecomment-1310598321
https://github.com/carbon-language/carbon-lang/issues/508#issuecomment-1312222800
