### ISSUE TITLE
should we have validity rules based on indentation?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#521]
A famous source of errors in C-family languages is for the indentation of code to misleadingly not match the meaning of the code as understood by the compiler. This often occurs due to unbraced constructs, such as

```
if (cond)
  f();
  g();

h();
```

An incautious reader may, based on the indentation, think that the call to `g()` is guarded by `cond`.

One possible way to try to solve this problem is by requiring braces on all control constructs. However, that is an imprecise proxy for solving the issue, and it's still possible to write code whose apparent behavior deviates from its actual behavior.

```
if (cond) {
  f();
}
  g();

h();
```

(The misplaced `}` is relatively obvious here, but may not be so obvious in a larger example.) Another issue with the approach of requiring braces is that it will be off-putting for some existing C++ developers.

Another possible approach, and the one I'd like feedback on here, is directly using the indentation of the code to check that the apparent meaning matches the actual meaning.

[For example (though I'm not asking about this specific rule, just the indentation-sensitivity approach in general): certain constructs (in particular, braces spanning more than one line) introduce a new indentation level, which must be more indented than that of the enclosing such construct. All top-level children of such a construct are required to be on a new line, with their first token indented to that enclosing construct's indentation level, and all other lines within each such child are required to be more indented.]

Using indentation in this way has additional benefits:

* For error recovery, and especially in cases where we don't yet realize we're recovering from an error, we can accurately match up brackets and braces. For example, when a close brace is missing, C++ compilers will often produce only garbage diagnostics about a function definition occurring in another function, and never actually tell you you're missing a close brace. If we put a hard requirement on indentation, we can diagnose the missing close brace and say exactly where it's missing.
* For code completion and similar tooling tasks, we are in general parsing a block of code with a known hole in it. We don't in general know what unbalanced brackets might belong in that hole, making it hard to work out how to interpret parts of the program after the cursor -- but in general we might need to parse those in order to find names that might be mentioned. (In C++, this failure mode occurs when attempting to code-complete a member name inside the definition of a class, where the member is declared later.)

Note that the correct indentation would always be recoverable from the original tokens (you can lose formatting over email, then you only need to run the carbon formatting tool over the source before it becomes valid again), but we would not in general expect that attempting to compile a misindented-program would succeed with only warnings.

**Comment by jonmeow** [comment]
Filed #1999 to try to track a proposal for this.
