### ISSUE TITLE
what syntax should we use for pointer types?

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#523]
C and C++ use prefix `*` for dereference, infix `*` for multiplication, and use syntax that superficially resembles using postfix `*` for forming pointer types (although it's actually a prefix `*` applied to a declarator).

_From a comment by @josh11b in https://github.com/carbon-language/carbon-lang/issues/520#issuecomment-832783466_:

> In general it seems like we are pushing towards single meanings for operator symbols and keywords, so wanting to support multiple meanings for `*` is mostly to be consistent with C/C++. [...] I think we should be asking "given that we want to use binary `*` for multiplication, how should we designate pointer types and dereference?" I think there are a lot of options to consider there:
>
> - Use prefix `*` for dereference, postfix `*` for forming pointer types, and use whitespace to disambiguate whether operators are prefix, postfix, or infix.
> - Use prefix `*` for dereference, postfix `*` for forming pointer types, and use precedence rules to disambiguate.
> - Use prefix `*` for dereference, postfix `*` for forming pointer types, but assume we are not going to have any binary operators on pointer types, and use that to disambiguate (not sure this works, but maybe?).
> - Use prefix `*` for dereference, prefix `&` for forming pointer types (analogy to "type of the tuple is the tuple of the types" here is "type of a pointer is a pointer to the type").
> - Use prefix `*` for dereference, `Ptr(T)` for forming pointer types.
> - Use `^` for some pointer operations, stop using it for binary xor.
> - (Probably a lot of other choices.)

**Comment by josh11b** [comment]
I've tried to capture the various options for different pointer syntaxes in [this doc](https://docs.google.com/document/d/1gsP74fLykZBCWZKQua9VP0GnQcADCkn5-TIC1JbUvdA/edit?usp=sharing&resourcekey=0-8MsUybUvHDCuejrzadrbMg).
[Note: link updated 2022-07-22]

**Comment by nigeltao** [comment]
> I've tried to capture the various options for different pointer syntaxes in [this doc](https://docs.google.com/document/d/1r2DSq_STYuyJi7PMkpm5tkgBJRIzQ8WwhtaeEd3sry0/edit#).

FWIW, this doc is not publicly accessible.

**Comment by geoffromer** [comment]
> > I've tried to capture the various options for different pointer syntaxes in [this doc](https://docs.google.com/document/d/1r2DSq_STYuyJi7PMkpm5tkgBJRIzQ8WwhtaeEd3sry0/edit#).
> 
> FWIW, this doc is not publicly accessible.

Here's a [publically accessible mirror](https://docs.google.com/document/d/1gsP74fLykZBCWZKQua9VP0GnQcADCkn5-TIC1JbUvdA/edit?usp=sharing&resourcekey=0-8MsUybUvHDCuejrzadrbMg)
