### ISSUE TITLE
Function types with non-type parameter types allowed in patterns

### ISSUE THREAD

**Issue by dabrahams** [carbon-language/carbon-lang#526]
In the C++ implementation, I think this should fail to compile:
```
fn f(fnty(Int x)) => 0;
fn main -> Int { return 0 }
```
but it doesn't.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
