### ISSUE TITLE
Matching pattern languages

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#528]
We have so far been trying to design a single pattern syntax to be used across variable declarations, function declarations, and match statements. This is turning out to be a big constraint, and we have been bumping into the problems with this approach recently. This approach is only common in functional languages with very different needs. I think it is time to ask the question of whether we should treat these as separate problems in order to better address their individual needs.

Lets look at what each context needs:

- `fn` function declaration
    - Most important: specifying the types of parameters
    - And then: name binding, defaults/optional, labels
    - Concern with "consistent pattern grammar" approach: `fn F(Int)` doesn't match user's expectations
    - Exotic: Matching or destructuring values. Rare for users to want this (not available in C/C++) and interfere with solving the `fn F(Int)` problem.
- `var` variable declaration
    - Most important: name binding
    - And then: types, destructuring tuples/structs optionally with renaming
- `match` statements
    - Most important: dispatch based on runtime values
    - Most common: equal to value, in range, in set
        - These cases correspond to C/C++ `switch` and don't need name bindings or types
    - Sum type dispatch would use name binding
    - Dynamic type tests would use both types and name binding
    - Cases are refutable and ordered
- `guard` statements
    - Most important: unwrapping optional and/or result types
    - Refutable patterns like match statements, but focused on the sum type and dynamic type cases that need name bindings

My contention is that these are pretty different use cases, each with unique concerns to accommodate.

**Comment by josh11b** [comment]
What I've heard so far:

- We'd like the syntax to be consistent, but different subsets are allowed in different contexts.
- We aren't going to allow refutable patterns in `fn`/`var`/`let`, and that is going to eliminate a class of bugs / surprises.
- [A thread on #syntax starting 2022-09-16](https://discord.com/channels/655572317891461132/709488742942900284/1020559817045192746) considered separating the expression and pattern grammars. In particular, the only unintroduced pattern is a bound name _identifier_ `:` _expression_.

**Comment by zygoloid** [comment]
Some of these questions have been answered by approved proposal #2188. In particular:

- We have a grammar for patterns, and #2188 says it applies to all the contexts that are in scope here.
- We have rules that disallow refutable patterns in most contexts.
- We have determined that for now, [expression patterns will not have an introducer](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p2188.md#introducer-syntax-for-expression-patterns), although the leads are open to reconsidering.

I think the remaining question here is, do we have syntactic restrictions on some of these pattern contexts? That is, do we allow only a subset of the pattern grammar, depending on which kind of pattern we're parsing? And if so, what are the restrictions that we impose? We've spun some of that out into separate questions:

- #578 explores whether to allow expression patterns in function parameters.
- #1229 asks what kinds of patterns can appear in a class parameter list.

I think given the discussion on those issues, we can answer the remaining question as: yes, we may have additional restrictions for some or all pattern contexts, depending on the needs of that context. We'll decide what restrictions make sense for different contexts separately.

**Comment by chandlerc** [comment]
Agreed and calling this decided.
