### ISSUE TITLE
pick names for fixed-size integer types

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#543]
We should have names for integer types with fixed widths. For the moment I'm only considering signed, two's-complement integer types that are expected to match native machine register widths: at least 8, 16, 32, and 64 bit varieties should be supported. Some possible options:

1) Follow C++ LP64 convention: `char` is the 8-bit type, `short` is the 16-bit type, `int` is the 32-bit type, `long` is the 64-bit type.
2) Use `int` with a length suffix: `int8`, `int16`, `int32`, `int64`. This somewhat mimics the `intN_t` typedefs from C++.
3) Use `i` with a length suffix: `i8`, `i16`, `i32`, `i64`. This follows Rust (and LLVM).

Orthogonally, but not independently: (A) capitalize the first letter, (b) do not capitalize the first letter.

**Comment by jonmeow** [comment]
Filed #1998 to track turning this into a proposal.
