### ISSUE TITLE
Multicharacter bitwise operators?

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#545]
This subject came up when discussing pointer syntax https://github.com/carbon-language/carbon-lang/issues/523 and [this doc](https://docs.google.com/document/d/1r2DSq_STYuyJi7PMkpm5tkgBJRIzQ8WwhtaeEd3sry0/edit#), but there is plenty of need to free up symbols for other constructs:

- lambdas
- ownership/lifetimes
- parameter passing (references? rvalues/move?)
- sum types (might benefit from using `|` and/or `?`)
- error handling (which might be interested in `?` and/or `!`)
- generics
- we want to reserve backtick (`` ` ``) for markdown / documentation
- attributes/annotations (maybe `@`?)
- coroutines
- metaprogramming
- etc.

Note that Carbon goals and design decisions (such as reducing ambiguity and types as values) discourage reusing operators for multiple purposes.

We have a few opportunities to free up a few symbols already:

- by eliminating the preprocessor we free up `#` and `\`
- we will likely do something to free up `?` and `:` from the ternary conditional operator (though `:` is likely pretty spoken for already in #542 )
- `$` and `@` aren't in use, and appears to generally be available on keyboards that can type our keywords
- we might use `not` instead of `!`

The bitwise operators were historically also used as boolean operators (search [this history](https://www.bell-labs.com/usr/dmr/www/chist.html) for "Neonatal C") which explains why they were given short names and low precedence.

A non-exhaustive list of possible ways of spelling bitwise operators in Carbon:
- `a \& b`, `a \| b`, `a \^ b`, `\~ b`
- `a &: b`, `a |: b`, `a ^: b`, `~: b`
- `a .&. b`, `a .|. b`, `a .^. b`, `.~. b`
- `a .*. b`, `a .+. b`, `a .!=. b`, `.!. b`
- `a /\ b`, `a \/ b`, `a (+) b`, `-|a`
- keywords?

Note: I'm ignoring `<<` and `>>` since they are already multiple characters.

**Question:** Should we keep the 1-character symbols for the bitwise operators (`&`, `|`, `^`, `~`) or switch to multiple-character bitwise operators?

Note: I am not asking to actually determine the spelling of bitwise operators if we do switch, except in so far as that would help decide the question.

A third choice would be to combine the `^` and `~` operators, and use a single symbol for both (prefix usage would be complement and infix would be xor).

Advantages of switching to multiple characters:

- Have good uses for these symbols: `&` for combining interfaces and address-of, `|` for sum types and/or lambdas and/or another kind of bracket, `~` for move (C++ uses `~` for destructors, which is suggestive of ending the lifetime), and `^` might be used with pointers.
- I believe the bitwise operators to be used relatively rarely, though I don't have good statistics. When I tried to estimate this, I got <3% of C++ files use bitwise `&` and <0.6% use bitwise `^`, but I have low confidence in those numbers. (Let me know if collecting usage statistics would be valuable for making this decision, if I spend some time on it I can get some higher-confidence numbers.)

Advantages of preserving:

- Familiarity for C++ programmers.
- My guess is that in files that use bitwise operators, they may be used a lot. Similarly, people who use these operators may use them a lot.
- Being taken seriously by users for low-level performance-oriented code.

**Comment by jonmeow** [comment]
I believe this was included in #1191 and no longer needs to be tracked as "Needs proposal".
