### ISSUE TITLE
Generic syntax to replace provisional `$`s

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#565]
Right now, I am using this provisional syntax in my generics proposals:
- `x: T` - dynamic parameter
- `x:$ T` - generic parameter
- `x:$$ T` - template parameter

In a discussion with @mconst , we thought that this alternative would be better:
- `dynamic x: T` - dynamic parameter
- `generic x: T` - generic parameter
- `template x: T` - template parameter
- `x: T` - dynamic or generic parameter based on context

The rules for determining whether `x: T` was dynamic or generic would be:
- For a variable declaration in the body of a function or struct: `dynamic`
- For a parameter in the declaration of a type or interface: `generic`
- For a parameter in a function signature:
    - If the parameter is used in an expression in a type position in this function signature declaration: `generic`
    - Otherwise: `dynamic`

An example of this last rule:
```
// Before:
fn F[T: Type, U:$ Type, N:$ UInt]
    (p: T*, a: Array(U, N), M:$ Int, V:$$ Type) -> V;

// After:
fn F[dynamic T: Type, U: Type, N: UInt]
    (p: T*, a: Array(U, N), generic M: Int, template V: Type) -> V;
```

Benefits of this approach:
- The unusual case of a type parameter being passed in dynamically gets highlighted.
- Any template parameter is highlighted.
- Use of `:` by itself is usually what you want. Particularly this syntax avoids asking the user to know that they have to do something different for type parameters.
- Use of keywords instead of symbols makes it more self-explanatory and easier to find in search engines.

The main downside of this approach is that it is context sensitive, but the scope of the context is limited to the current declaration. It also uses more characters in cases where you need to specify a keyword.

We would still need a syntax for declaring associated types and constants in an interface body, I propose `const name: type`, optionally followed by an `= default`.
```
// Before:
interface Addable(RHS:$ Type = Self) {
  var AddResult:$ Type = Self;
  method (me: Self) Add(rhs: RHS) -> AddResult;
}

// After:
interface Addable(RHS: Type = Self) {
  const AddResult: Type = Self;
  method (me: Self) Add(rhs: RHS) -> AddResult;
}
```
I'm hesitant to use `var` here (though we could, with a `generic` default) because `var` would have a different interpretation when implementing this interface in a `struct` definition, and generally elsewhere `var` would default to `dynamic`.

**Comment by m13253** [comment]
(Cross posting with [#1425](https://github.com/carbon-language/carbon-lang/discussions/1425#discussioncomment-3223288))

In my own opinion, the first time I saw `[T:! Comparable & Movable]`, I thought `!` means negation (“**not** comparable”).
If we use `!` here, what symbol should we use, if in the future we need to implement, for **type negation**?

Have we discussed other symbols on the keyboard?
```carbon
[T:# Comparable & Movable]
[T:% Comparable & Movable]
[T:^ Comparable & Movable]
[T:@ Comparable & Movable]
```

My personal reasons:
1. The `#` symbol is familiar to C programmers to indicate preprocessor directives. I think it makes sense to indicate compile-time constraints.
2. The `%` symbol is used in `printf` for placeholders, which also makes sense to indicate type placeholders.
3. The `^` symbol doesn't cause ambiguity since `xor` operator is binary and never occurs at the beginning.
4. I don't have specific reasons for `@`. But it looks good.

**Comment by YagaoDirac** [comment]
Let me copy my comment from the discussion thread. Link:
https://github.com/carbon-language/carbon-lang/discussions/1425

Let me give you a maybe final answer. In the code
fn Partition[/Notice the scope here/T:! Comparable & Movable](s: Slice(T))
-> i64 {
}
In the scope I emphasis, it's not possible to do any "logic not", and the type has to be figured out in compile time. Or, Carbon does runtime type deduction and create types on the fly????
If I guess the correct answer, then the "!" is simply not needed.
Even if you are to retain it, in your official example, you should write it like
fn Partition[T: !Comparable & Movable](s: Slice(T))
-> i64 {
}
The space should be in front of !.

**Comment by josh11b** [comment]
I think this discussion belongs better in #1425 than here, since this issue is old and closed.
