### ISSUE TITLE
Value patterns as function parameters

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#578]
Right now there is a gotcha in our current strategy for using pattern matching for function parameters:
```
fn F(Int);
```
may only be called by `F(Int)`, not `F(1)` or `F(2)`. This is a significant and confusing divergence from C++. There was some discussion of this in [the #syntax discord channel](https://discord.com/channels/655572317891461132/709488742942900284/833812947196313730).

I'd like to propose to change things in two ways:
1. Either the above declaration of `F` is illegal or it means that `F` takes an argument of type `Int`, like it would in C++.
2. We have some other syntax for saying "match this value."

We might forbid value patterns in function declarations entirely, but there are some rare situations where they are useful. For example, it is useful for using a later type parameter in an earlier parameter's type, as in:
```
fn DoACast[U:$ Type, T:$ ConvertibleTo(U)](x: T, U) -> U {
  return x as U;
}
var i: Int32 = 0;
var f: Float64 = DoACast(i, Float64);
```

I propose for 2 that we mark value patterns with an `==` prefix, as in:
```
fn DoACast[U:$ Type, T:$ ConvertibleTo(U)](x: T, ==U) -> U { ... }
```
The question of whether this would also be used in `match` statements as in:
```
match (i) {
  case ==0 => { ... }
  case ==1 => { ... }
  default => { ... }
}
```
is the subject of #528 .

**Comment by josh11b** [comment]
This is related to the question in #528 . In particular, both would be addressed by an introducer to match a value, as suggested in [this thread on #syntax starting 2022-09-16](https://discord.com/channels/655572317891461132/709488742942900284/1020559817045192746).

**Comment by zygoloid** [comment]
The status quo, as of #2188, is that a declaration such as:
```
fn F(i32);
```
is ill-formed, because `i32` is a refutable pattern. I believe that addresses the original concern here. We should keep this issue in mind when adding support for function overloading, which may reintroduce the problem depending on how we approach it, but for now it seems like the issue has been addressed.

**Comment by zygoloid** [comment]
For [this use case](https://github.com/carbon-language/carbon-lang/issues/578#issuecomment-982904691), we can use something like this:

```
fn DoACast[T:! type](x: T, U:! type where T is ConvertibleTo(.Self)) -> U {
  return x as U;
}
```

**Comment by josh11b** [comment]
There is another example from https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/generics/details.md#parameterized-interfaces 

```carbon
// Doesn't work, no support for `singleton_type_of`
fn PeekAtTopOfStackParameterized
    [T:! type, StackType:! StackParameterized(T)]
    (s: StackType*, _:! singleton_type_of(T)) -> T { ... }
```

This corresponds to the C++ code:

```c++
// Called `PeekAtTopOfStackParameterized<MyType>(&MyStack)`
template<typename T, StackParameterized<T> StackType>
auto PeekAtTopOfStackParameterized(StackType* s) -> T { ... }
```

We discussed a couple possible workarounds:

```carbon
fn PeekAtTopOfStackParameterized[StackType:! type]
    (s: StackType*, T:! type where StackType is StackParameterized(.Self)) -> T {
  let ActualStackType:! StackParameterized(T) = StackType;
  let actual_s: ActualStackType* = s;
  ...
}
```

```carbon
fn PeekAtTopOfStackParameterizedImpl
    (T:! type, StackType:! StackParameterized(T), s: StackType*) -> T {
  ...
}
fn PeekAtTopOfStackParameterized[StackType:! type]
    (s: StackType*, T:! type where StackType is StackParameterized(T)) -> T {
  return PeekAtTopOfStackParameterizedImpl(T, StackType, s);
}
```

We rejected this approach in https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p2188.md#type-pattern-matching :

```carbon
fn PeekAtTopOfStackParameterized
  (T:! type, s: (StackType:! StackParameterized(T))*) -> T {  ...}
```

Two ways we could in the future support this use case would be:

```carbon
fn PeekAtTopOfStackParameterized
  (T:! type, s: (some StackParameterized(T))*) -> T {  ...}
```

```carbon
// Called `PeekAtTopOfStackParameterized(MyType)(&MyStack)`:
fn PeekAtTopOfStackParameterized(T:! type) =>
    lambda [StackType:! StackParameterized(T)](s: StackType*) -> T {
  ...
}
```
