### ISSUE TITLE
Operation order in struct/class assignment/initialization

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#686]
This question was introduced in #561 .

**Open question:** What operations and in what order happen for assignment and initialization?

-   Is assignment just destruction followed by initialization? Is that destruction completed for the whole object before initializing, or is it interleaved field-by-field?
-   When initializing to a literal value, is a temporary containing the literal value constructed first or are the fields initialized directly? The latter approach supports types that can't be moved or copied, such as mutex.
-   Perhaps some operations are _not_ ordered with respect to each other?

**Comment by josh11b** [comment]
As far as I'm aware, this question still needs to be answered. Is https://github.com/carbon-language/carbon-lang/issues/686#issuecomment-888694676 an acceptable answer?

**Comment by chandlerc** [comment]
Confirmed with leads and we're good with the correct thing @zygoloid describes here:

> I think it's fine from a correctness standpoint to implement assignment as instead:
> 
> * initialize a temporary object from the right-hand side
> * destroy the destination
> * move the right-hand side into the left-hand side
> 
> ... and allow types to override that behavior if they can do better, either because they have a buffer they can reuse, or because they know it's safe and worthwhile to reinitialize in place and avoid the extra move operation.

And then allow customizing assignment when a different approach would be more efficient.

Marking as closed with this answer, but this one we do still need a proposal for (and I think for assignment more generally).

**Comment by josh11b** [comment]
> Marking as closed with this answer, but this one we do still need a proposal for (and I think for assignment more generally).

FYI, proposal #2511 implements assignment statements, but did not incorporate the decision of this issue. Issue #2489 is tracking that work.
