### ISSUE TITLE
Default comparison for data classes

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#710]
I think we agree that data classes (including struct types) should support equality comparisons if all of its field types do. This comparison should at least support values with the same type, including field order.
```
var s: {.x: i32, .y: i32} = {.x = 3, .y = 4};
Assert(s == {.x = 3, .y = 4});
```

**Question 1:** Should this also be supported if the fields are the same, but in a different order?
```
Assert(s == {.y = 4, .x = 3});
```

**Question 2:** Should data classes support ordering comparisons (`<`, `<=`, `>`, `>=`) using lexicographical order? Clearly the field orders would have to match in this case.
```
Assert(s < {.x = 5, .y = 2});
```

**Context:** proposals #561 on basic classes and #702 on comparisons, and Discord discussion starting with https://discord.com/channels/655572317891461132/708431657849585705/872603493242908772

**Comment by jonmeow** [comment]
I think #1178 maybe addressed the need for a proposal here?

**Comment by chandlerc** [comment]
> I think #1178 maybe addressed the need for a proposal here?

@zygoloid or @josh11b to confirm.

**Comment by josh11b** [comment]
Confirmed, #981 and #1178 addressed this.
