### ISSUE TITLE
Implement packages and libraries

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#742]
Tracking issue for implementing the `package` and `import` keywords, for packages and libraries.

ref: https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design/code_and_name_organization

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
