### ISSUE TITLE
Implement raw string literals

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#745]
Tracking issue for implementing raw string literals. Note it may be good to implement block string literals first (#744) so that raw string literals can then be done covering both simple and block string literals.

ref: #199

**Comment by jonmeow** [comment]
I'm closing this, as it's mostly done, at least as originally intended.

**Comment by KarthikeyaThotak** [comment]
Hello Guys, I am new to this contributing to open source projects. I would like to work in this branch. Thank you in advance.

**Comment by jonmeow** [comment]
@User-Alpine First, not everyone here likes being called a "guy".

But this is a closed issue. I'd suggest redirecting to either the Getting Started GitHub discussion topic, or #getting-started on Discord.
