### ISSUE TITLE
Implement prelude logic

### ISSUE THREAD

**Issue by jonmeow** [carbon-language/carbon-lang#766]
Tracking issue for implementing prelude logic for adding symbols... this should depend on #742 as it's going to be very similar.

Once done we should probably have all tests use a standard prelude which may grow over time, particularly because things like i32 will end up there, and code wouldn't function well without that.

**Comment by jonmeow** [comment]
data/prelude.carbon is part of this, but should probably be changed in how it works (the current state is primitive but functional).

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
