### ISSUE TITLE
Implicit/inferred generic type constraints

### ISSUE THREAD

**Issue by josh11b** [carbon-language/carbon-lang#809]
Question: Should the following compile, or should the compiler require that the user explicitly list all of `HashSet`'s requirements for `KeyType`?

```
class HashSet(KeyType:! Hashable & HasEquals & Movable);
fn Contains[KeyType:! Type](needle: KeyType, haystack: HashSet(KeyType)) -> Bool;
fn Print[KeyType:! Printable](set_to_print: HashSet(KeyType));
```

- Swift supports this: [1](https://www.swiftbysundell.com/tips/inferred-generic-type-constraints/), [2](https://github.com/apple/swift/blob/main/docs/Generics.rst#constraint-inference)
- Inside `Contains`, `KeyType` would satisfy those interfaces but it would be like the interfaces were implemented externally, without including the names from those interfaces as unqualified members of `KeyType`
- This would only be for function signatures, not interfaces where there are additional considerations.

### Implicit constraint option

Advantages:

- More concise, benefiting readers and writers of the code.
- Doesn't included redundant information, following the ["don't repeat yourself" principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- Callers providing a `haystack` value of type `HashSet(KeyType)` already establishes that they have satisfied the constraints.
- Allows `HashSet` to evolve its requirements with fewer changes to the code.

Disadvantages:

- This may introduce additional complications once we allow specializations of `HashSet`, which might possibly allow `HashSet(T)` for some `T` that doesn't satisfy the general requirements.
- Less explicit.

### Opt-in

Another choice would be to have an explicit mark indicating that the requirements should be determined automatically for an indicated generic type parameter.
```
fn Contains[KeyType:! implicit_requirements]
           (needle: KeyType, haystack: HashSet(KeyType)) -> Bool;
fn Print[KeyType:! Printable & implicit_requirements]
           (set_to_print: HashSet(KeyType));
```

We might use the keyword `auto` here, but I worry that is more closely associated with template semantics.

### No implicit constraints

Users would be expected to list all requirements.

**Comment by jonmeow** [comment]
I think this may not still need a proposal, looks like #818 was probably filling that need.

**Comment by chandlerc** [comment]
> I think this may not still need a proposal, looks like #818 was probably filling that need.

@josh11b to confirm.

**Comment by josh11b** [comment]
> > I think this may not still need a proposal, looks like #818 was probably filling that need.
> 
> @josh11b to confirm.

Confirmed, #818 addressed this.
